{ DO NOT EDIT — generated by pascal_bindgen.
  source: /usr/include/GL/gl.h
}

unit gl_fpc;

{$mode objfpc}{$H+}
{$PACKRECORDS C}

interface

uses
  ctypes;

type
  Pcdouble = ^cdouble;
  Pcfloat = ^cfloat;
  Pcint = ^cint;
  Pcshort = ^cshort;
  Pcuchar = ^cuchar;
  Pcuint = ^cuint;
  Pcushort = ^cushort;
  PGLboolean = ^GLboolean;
  PGLdouble = ^GLdouble;
  PGLfloat = ^GLfloat;
  PGLint = ^GLint;
  PGLubyte = ^GLubyte;
  PGLuint = ^GLuint;
  PGLushort = ^GLushort;
  PGLvoid = ^GLvoid;
  PPGLvoid = ^PGLvoid;
  GLenum = cuint;  { gl.h:116 }
  GLboolean = cuchar;  { gl.h:117 }
  GLbitfield = cuint;  { gl.h:118 }
  GLvoid = Pointer;  { gl.h:119 }
  GLbyte = cschar;  { gl.h:120 }
  GLshort = cshort;  { gl.h:121 }
  GLint = cint;  { gl.h:122 }
  GLubyte = cuchar;  { gl.h:123 }
  GLushort = cushort;  { gl.h:124 }
  GLuint = cuint;  { gl.h:125 }
  GLsizei = cint;  { gl.h:126 }
  GLfloat = cfloat;  { gl.h:127 }
  GLclampf = cfloat;  { gl.h:128 }
  GLdouble = cdouble;  { gl.h:129 }
  GLclampd = cdouble;  { gl.h:130 }
  PFNGLDRAWRANGEELEMENTSPROC = procedure(arg1: cuint; arg2: cuint; arg3: cuint; arg4: cint; arg5: cuint; arg6: Pointer); cdecl;  { gl.h:1511 }
  PFNGLTEXIMAGE3DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: cuint; arg9: cuint; arg10: Pointer); cdecl;  { gl.h:1512 }
  PFNGLTEXSUBIMAGE3DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: cint; arg9: cuint; arg10: cuint; arg11: Pointer); cdecl;  { gl.h:1513 }
  PFNGLCOPYTEXSUBIMAGE3DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: cint; arg9: cint); cdecl;  { gl.h:1514 }
  PFNGLACTIVETEXTUREPROC = procedure(arg1: cuint); cdecl;  { gl.h:1912 }
  PFNGLSAMPLECOVERAGEPROC = procedure(arg1: cfloat; arg2: cuchar); cdecl;  { gl.h:1913 }
  PFNGLCOMPRESSEDTEXIMAGE3DPROC = procedure(arg1: cuint; arg2: cint; arg3: cuint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: cint; arg9: Pointer); cdecl;  { gl.h:1914 }
  PFNGLCOMPRESSEDTEXIMAGE2DPROC = procedure(arg1: cuint; arg2: cint; arg3: cuint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: Pointer); cdecl;  { gl.h:1915 }
  PFNGLCOMPRESSEDTEXIMAGE1DPROC = procedure(arg1: cuint; arg2: cint; arg3: cuint; arg4: cint; arg5: cint; arg6: cint; arg7: Pointer); cdecl;  { gl.h:1916 }
  PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint; arg6: cint; arg7: cint; arg8: cint; arg9: cuint; arg10: cint; arg11: Pointer); cdecl;  { gl.h:1917 }
  PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint; arg6: cint; arg7: cuint; arg8: cint; arg9: Pointer); cdecl;  { gl.h:1918 }
  PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cuint; arg6: cint; arg7: Pointer); cdecl;  { gl.h:1919 }
  PFNGLGETCOMPRESSEDTEXIMAGEPROC = procedure(arg1: cuint; arg2: cint; arg3: Pointer); cdecl;  { gl.h:1920 }
  PFNGLACTIVETEXTUREARBPROC = procedure(arg1: cuint); cdecl;  { gl.h:2001 }
  PFNGLCLIENTACTIVETEXTUREARBPROC = procedure(arg1: cuint); cdecl;  { gl.h:2002 }
  PFNGLMULTITEXCOORD1DARBPROC = procedure(arg1: cuint; arg2: cdouble); cdecl;  { gl.h:2003 }
  PFNGLMULTITEXCOORD1DVARBPROC = procedure(arg1: cuint; arg2: Pcdouble); cdecl;  { gl.h:2004 }
  PFNGLMULTITEXCOORD1FARBPROC = procedure(arg1: cuint; arg2: cfloat); cdecl;  { gl.h:2005 }
  PFNGLMULTITEXCOORD1FVARBPROC = procedure(arg1: cuint; arg2: Pcfloat); cdecl;  { gl.h:2006 }
  PFNGLMULTITEXCOORD1IARBPROC = procedure(arg1: cuint; arg2: cint); cdecl;  { gl.h:2007 }
  PFNGLMULTITEXCOORD1IVARBPROC = procedure(arg1: cuint; arg2: Pcint); cdecl;  { gl.h:2008 }
  PFNGLMULTITEXCOORD1SARBPROC = procedure(arg1: cuint; arg2: cshort); cdecl;  { gl.h:2009 }
  PFNGLMULTITEXCOORD1SVARBPROC = procedure(arg1: cuint; arg2: Pcshort); cdecl;  { gl.h:2010 }
  PFNGLMULTITEXCOORD2DARBPROC = procedure(arg1: cuint; arg2: cdouble; arg3: cdouble); cdecl;  { gl.h:2011 }
  PFNGLMULTITEXCOORD2DVARBPROC = procedure(arg1: cuint; arg2: Pcdouble); cdecl;  { gl.h:2012 }
  PFNGLMULTITEXCOORD2FARBPROC = procedure(arg1: cuint; arg2: cfloat; arg3: cfloat); cdecl;  { gl.h:2013 }
  PFNGLMULTITEXCOORD2FVARBPROC = procedure(arg1: cuint; arg2: Pcfloat); cdecl;  { gl.h:2014 }
  PFNGLMULTITEXCOORD2IARBPROC = procedure(arg1: cuint; arg2: cint; arg3: cint); cdecl;  { gl.h:2015 }
  PFNGLMULTITEXCOORD2IVARBPROC = procedure(arg1: cuint; arg2: Pcint); cdecl;  { gl.h:2016 }
  PFNGLMULTITEXCOORD2SARBPROC = procedure(arg1: cuint; arg2: cshort; arg3: cshort); cdecl;  { gl.h:2017 }
  PFNGLMULTITEXCOORD2SVARBPROC = procedure(arg1: cuint; arg2: Pcshort); cdecl;  { gl.h:2018 }
  PFNGLMULTITEXCOORD3DARBPROC = procedure(arg1: cuint; arg2: cdouble; arg3: cdouble; arg4: cdouble); cdecl;  { gl.h:2019 }
  PFNGLMULTITEXCOORD3DVARBPROC = procedure(arg1: cuint; arg2: Pcdouble); cdecl;  { gl.h:2020 }
  PFNGLMULTITEXCOORD3FARBPROC = procedure(arg1: cuint; arg2: cfloat; arg3: cfloat; arg4: cfloat); cdecl;  { gl.h:2021 }
  PFNGLMULTITEXCOORD3FVARBPROC = procedure(arg1: cuint; arg2: Pcfloat); cdecl;  { gl.h:2022 }
  PFNGLMULTITEXCOORD3IARBPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint); cdecl;  { gl.h:2023 }
  PFNGLMULTITEXCOORD3IVARBPROC = procedure(arg1: cuint; arg2: Pcint); cdecl;  { gl.h:2024 }
  PFNGLMULTITEXCOORD3SARBPROC = procedure(arg1: cuint; arg2: cshort; arg3: cshort; arg4: cshort); cdecl;  { gl.h:2025 }
  PFNGLMULTITEXCOORD3SVARBPROC = procedure(arg1: cuint; arg2: Pcshort); cdecl;  { gl.h:2026 }
  PFNGLMULTITEXCOORD4DARBPROC = procedure(arg1: cuint; arg2: cdouble; arg3: cdouble; arg4: cdouble; arg5: cdouble); cdecl;  { gl.h:2027 }
  PFNGLMULTITEXCOORD4DVARBPROC = procedure(arg1: cuint; arg2: Pcdouble); cdecl;  { gl.h:2028 }
  PFNGLMULTITEXCOORD4FARBPROC = procedure(arg1: cuint; arg2: cfloat; arg3: cfloat; arg4: cfloat; arg5: cfloat); cdecl;  { gl.h:2029 }
  PFNGLMULTITEXCOORD4FVARBPROC = procedure(arg1: cuint; arg2: Pcfloat); cdecl;  { gl.h:2030 }
  PFNGLMULTITEXCOORD4IARBPROC = procedure(arg1: cuint; arg2: cint; arg3: cint; arg4: cint; arg5: cint); cdecl;  { gl.h:2031 }
  PFNGLMULTITEXCOORD4IVARBPROC = procedure(arg1: cuint; arg2: Pcint); cdecl;  { gl.h:2032 }
  PFNGLMULTITEXCOORD4SARBPROC = procedure(arg1: cuint; arg2: cshort; arg3: cshort; arg4: cshort; arg5: cshort); cdecl;  { gl.h:2033 }
  PFNGLMULTITEXCOORD4SVARBPROC = procedure(arg1: cuint; arg2: Pcshort); cdecl;  { gl.h:2034 }
  PFNGLBLENDEQUATIONSEPARATEATIPROC = procedure(arg1: cuint; arg2: cuint); cdecl;  { gl.h:2078 }
  PFNGLEGLIMAGETARGETTEXTURE2DOESPROC = procedure(arg1: cuint; arg2: Pointer); cdecl;  { gl.h:2094 }
  PFNGLEGLIMAGETARGETRENDERBUFFERSTORAGEOESPROC = procedure(arg1: cuint; arg2: Pointer); cdecl;  { gl.h:2095 }

const
  GL_VERSION_1_1 = 1;  { gl.h:107 }
  GL_VERSION_1_2 = 1;  { gl.h:108 }
  GL_VERSION_1_3 = 1;  { gl.h:109 }
  GL_ARB_imaging = 1;  { gl.h:110 }
  GL_FALSE = 0;  { gl.h:139 }
  GL_TRUE = 1;  { gl.h:140 }
  GL_BYTE = $1400;  { gl.h:143 }
  GL_UNSIGNED_BYTE = $1401;  { gl.h:144 }
  GL_SHORT = $1402;  { gl.h:145 }
  GL_UNSIGNED_SHORT = $1403;  { gl.h:146 }
  GL_INT = $1404;  { gl.h:147 }
  GL_UNSIGNED_INT = $1405;  { gl.h:148 }
  GL_FLOAT = $1406;  { gl.h:149 }
  GL_2_BYTES = $1407;  { gl.h:150 }
  GL_3_BYTES = $1408;  { gl.h:151 }
  GL_4_BYTES = $1409;  { gl.h:152 }
  GL_DOUBLE = $140A;  { gl.h:153 }
  GL_POINTS = $0000;  { gl.h:156 }
  GL_LINES = $0001;  { gl.h:157 }
  GL_LINE_LOOP = $0002;  { gl.h:158 }
  GL_LINE_STRIP = $0003;  { gl.h:159 }
  GL_TRIANGLES = $0004;  { gl.h:160 }
  GL_TRIANGLE_STRIP = $0005;  { gl.h:161 }
  GL_TRIANGLE_FAN = $0006;  { gl.h:162 }
  GL_QUADS = $0007;  { gl.h:163 }
  GL_QUAD_STRIP = $0008;  { gl.h:164 }
  GL_POLYGON = $0009;  { gl.h:165 }
  GL_VERTEX_ARRAY = $8074;  { gl.h:168 }
  GL_NORMAL_ARRAY = $8075;  { gl.h:169 }
  GL_COLOR_ARRAY = $8076;  { gl.h:170 }
  GL_INDEX_ARRAY = $8077;  { gl.h:171 }
  GL_TEXTURE_COORD_ARRAY = $8078;  { gl.h:172 }
  GL_EDGE_FLAG_ARRAY = $8079;  { gl.h:173 }
  GL_VERTEX_ARRAY_SIZE = $807A;  { gl.h:174 }
  GL_VERTEX_ARRAY_TYPE = $807B;  { gl.h:175 }
  GL_VERTEX_ARRAY_STRIDE = $807C;  { gl.h:176 }
  GL_NORMAL_ARRAY_TYPE = $807E;  { gl.h:177 }
  GL_NORMAL_ARRAY_STRIDE = $807F;  { gl.h:178 }
  GL_COLOR_ARRAY_SIZE = $8081;  { gl.h:179 }
  GL_COLOR_ARRAY_TYPE = $8082;  { gl.h:180 }
  GL_COLOR_ARRAY_STRIDE = $8083;  { gl.h:181 }
  GL_INDEX_ARRAY_TYPE = $8085;  { gl.h:182 }
  GL_INDEX_ARRAY_STRIDE = $8086;  { gl.h:183 }
  GL_TEXTURE_COORD_ARRAY_SIZE = $8088;  { gl.h:184 }
  GL_TEXTURE_COORD_ARRAY_TYPE = $8089;  { gl.h:185 }
  GL_TEXTURE_COORD_ARRAY_STRIDE = $808A;  { gl.h:186 }
  GL_EDGE_FLAG_ARRAY_STRIDE = $808C;  { gl.h:187 }
  GL_VERTEX_ARRAY_POINTER = $808E;  { gl.h:188 }
  GL_NORMAL_ARRAY_POINTER = $808F;  { gl.h:189 }
  GL_COLOR_ARRAY_POINTER = $8090;  { gl.h:190 }
  GL_INDEX_ARRAY_POINTER = $8091;  { gl.h:191 }
  GL_TEXTURE_COORD_ARRAY_POINTER = $8092;  { gl.h:192 }
  GL_EDGE_FLAG_ARRAY_POINTER = $8093;  { gl.h:193 }
  GL_V2F = $2A20;  { gl.h:194 }
  GL_V3F = $2A21;  { gl.h:195 }
  GL_C4UB_V2F = $2A22;  { gl.h:196 }
  GL_C4UB_V3F = $2A23;  { gl.h:197 }
  GL_C3F_V3F = $2A24;  { gl.h:198 }
  GL_N3F_V3F = $2A25;  { gl.h:199 }
  GL_C4F_N3F_V3F = $2A26;  { gl.h:200 }
  GL_T2F_V3F = $2A27;  { gl.h:201 }
  GL_T4F_V4F = $2A28;  { gl.h:202 }
  GL_T2F_C4UB_V3F = $2A29;  { gl.h:203 }
  GL_T2F_C3F_V3F = $2A2A;  { gl.h:204 }
  GL_T2F_N3F_V3F = $2A2B;  { gl.h:205 }
  GL_T2F_C4F_N3F_V3F = $2A2C;  { gl.h:206 }
  GL_T4F_C4F_N3F_V4F = $2A2D;  { gl.h:207 }
  GL_MATRIX_MODE = $0BA0;  { gl.h:210 }
  GL_MODELVIEW = $1700;  { gl.h:211 }
  GL_PROJECTION = $1701;  { gl.h:212 }
  GL_TEXTURE = $1702;  { gl.h:213 }
  GL_POINT_SMOOTH = $0B10;  { gl.h:216 }
  GL_POINT_SIZE = $0B11;  { gl.h:217 }
  GL_POINT_SIZE_GRANULARITY = $0B13;  { gl.h:218 }
  GL_POINT_SIZE_RANGE = $0B12;  { gl.h:219 }
  GL_LINE_SMOOTH = $0B20;  { gl.h:222 }
  GL_LINE_STIPPLE = $0B24;  { gl.h:223 }
  GL_LINE_STIPPLE_PATTERN = $0B25;  { gl.h:224 }
  GL_LINE_STIPPLE_REPEAT = $0B26;  { gl.h:225 }
  GL_LINE_WIDTH = $0B21;  { gl.h:226 }
  GL_LINE_WIDTH_GRANULARITY = $0B23;  { gl.h:227 }
  GL_LINE_WIDTH_RANGE = $0B22;  { gl.h:228 }
  GL_POINT = $1B00;  { gl.h:231 }
  GL_LINE = $1B01;  { gl.h:232 }
  GL_FILL = $1B02;  { gl.h:233 }
  GL_CW = $0900;  { gl.h:234 }
  GL_CCW = $0901;  { gl.h:235 }
  GL_FRONT = $0404;  { gl.h:236 }
  GL_BACK = $0405;  { gl.h:237 }
  GL_POLYGON_MODE = $0B40;  { gl.h:238 }
  GL_POLYGON_SMOOTH = $0B41;  { gl.h:239 }
  GL_POLYGON_STIPPLE = $0B42;  { gl.h:240 }
  GL_EDGE_FLAG = $0B43;  { gl.h:241 }
  GL_CULL_FACE = $0B44;  { gl.h:242 }
  GL_CULL_FACE_MODE = $0B45;  { gl.h:243 }
  GL_FRONT_FACE = $0B46;  { gl.h:244 }
  GL_POLYGON_OFFSET_FACTOR = $8038;  { gl.h:245 }
  GL_POLYGON_OFFSET_UNITS = $2A00;  { gl.h:246 }
  GL_POLYGON_OFFSET_POINT = $2A01;  { gl.h:247 }
  GL_POLYGON_OFFSET_LINE = $2A02;  { gl.h:248 }
  GL_POLYGON_OFFSET_FILL = $8037;  { gl.h:249 }
  GL_COMPILE = $1300;  { gl.h:252 }
  GL_COMPILE_AND_EXECUTE = $1301;  { gl.h:253 }
  GL_LIST_BASE = $0B32;  { gl.h:254 }
  GL_LIST_INDEX = $0B33;  { gl.h:255 }
  GL_LIST_MODE = $0B30;  { gl.h:256 }
  GL_NEVER = $0200;  { gl.h:259 }
  GL_LESS = $0201;  { gl.h:260 }
  GL_EQUAL = $0202;  { gl.h:261 }
  GL_LEQUAL = $0203;  { gl.h:262 }
  GL_GREATER = $0204;  { gl.h:263 }
  GL_NOTEQUAL = $0205;  { gl.h:264 }
  GL_GEQUAL = $0206;  { gl.h:265 }
  GL_ALWAYS = $0207;  { gl.h:266 }
  GL_DEPTH_TEST = $0B71;  { gl.h:267 }
  GL_DEPTH_BITS = $0D56;  { gl.h:268 }
  GL_DEPTH_CLEAR_VALUE = $0B73;  { gl.h:269 }
  GL_DEPTH_FUNC = $0B74;  { gl.h:270 }
  GL_DEPTH_RANGE = $0B70;  { gl.h:271 }
  GL_DEPTH_WRITEMASK = $0B72;  { gl.h:272 }
  GL_DEPTH_COMPONENT = $1902;  { gl.h:273 }
  GL_LIGHTING = $0B50;  { gl.h:276 }
  GL_LIGHT0 = $4000;  { gl.h:277 }
  GL_LIGHT1 = $4001;  { gl.h:278 }
  GL_LIGHT2 = $4002;  { gl.h:279 }
  GL_LIGHT3 = $4003;  { gl.h:280 }
  GL_LIGHT4 = $4004;  { gl.h:281 }
  GL_LIGHT5 = $4005;  { gl.h:282 }
  GL_LIGHT6 = $4006;  { gl.h:283 }
  GL_LIGHT7 = $4007;  { gl.h:284 }
  GL_SPOT_EXPONENT = $1205;  { gl.h:285 }
  GL_SPOT_CUTOFF = $1206;  { gl.h:286 }
  GL_CONSTANT_ATTENUATION = $1207;  { gl.h:287 }
  GL_LINEAR_ATTENUATION = $1208;  { gl.h:288 }
  GL_QUADRATIC_ATTENUATION = $1209;  { gl.h:289 }
  GL_AMBIENT = $1200;  { gl.h:290 }
  GL_DIFFUSE = $1201;  { gl.h:291 }
  GL_SPECULAR = $1202;  { gl.h:292 }
  GL_SHININESS = $1601;  { gl.h:293 }
  GL_EMISSION = $1600;  { gl.h:294 }
  GL_POSITION = $1203;  { gl.h:295 }
  GL_SPOT_DIRECTION = $1204;  { gl.h:296 }
  GL_AMBIENT_AND_DIFFUSE = $1602;  { gl.h:297 }
  GL_COLOR_INDEXES = $1603;  { gl.h:298 }
  GL_LIGHT_MODEL_TWO_SIDE = $0B52;  { gl.h:299 }
  GL_LIGHT_MODEL_LOCAL_VIEWER = $0B51;  { gl.h:300 }
  GL_LIGHT_MODEL_AMBIENT = $0B53;  { gl.h:301 }
  GL_FRONT_AND_BACK = $0408;  { gl.h:302 }
  GL_SHADE_MODEL = $0B54;  { gl.h:303 }
  GL_FLAT = $1D00;  { gl.h:304 }
  GL_SMOOTH = $1D01;  { gl.h:305 }
  GL_COLOR_MATERIAL = $0B57;  { gl.h:306 }
  GL_COLOR_MATERIAL_FACE = $0B55;  { gl.h:307 }
  GL_COLOR_MATERIAL_PARAMETER = $0B56;  { gl.h:308 }
  GL_NORMALIZE = $0BA1;  { gl.h:309 }
  GL_CLIP_PLANE0 = $3000;  { gl.h:312 }
  GL_CLIP_PLANE1 = $3001;  { gl.h:313 }
  GL_CLIP_PLANE2 = $3002;  { gl.h:314 }
  GL_CLIP_PLANE3 = $3003;  { gl.h:315 }
  GL_CLIP_PLANE4 = $3004;  { gl.h:316 }
  GL_CLIP_PLANE5 = $3005;  { gl.h:317 }
  GL_ACCUM_RED_BITS = $0D58;  { gl.h:320 }
  GL_ACCUM_GREEN_BITS = $0D59;  { gl.h:321 }
  GL_ACCUM_BLUE_BITS = $0D5A;  { gl.h:322 }
  GL_ACCUM_ALPHA_BITS = $0D5B;  { gl.h:323 }
  GL_ACCUM_CLEAR_VALUE = $0B80;  { gl.h:324 }
  GL_ACCUM = $0100;  { gl.h:325 }
  GL_ADD = $0104;  { gl.h:326 }
  GL_LOAD = $0101;  { gl.h:327 }
  GL_MULT = $0103;  { gl.h:328 }
  GL_RETURN = $0102;  { gl.h:329 }
  GL_ALPHA_TEST = $0BC0;  { gl.h:332 }
  GL_ALPHA_TEST_REF = $0BC2;  { gl.h:333 }
  GL_ALPHA_TEST_FUNC = $0BC1;  { gl.h:334 }
  GL_BLEND = $0BE2;  { gl.h:337 }
  GL_BLEND_SRC = $0BE1;  { gl.h:338 }
  GL_BLEND_DST = $0BE0;  { gl.h:339 }
  GL_ZERO = 0;  { gl.h:340 }
  GL_ONE = 1;  { gl.h:341 }
  GL_SRC_COLOR = $0300;  { gl.h:342 }
  GL_ONE_MINUS_SRC_COLOR = $0301;  { gl.h:343 }
  GL_SRC_ALPHA = $0302;  { gl.h:344 }
  GL_ONE_MINUS_SRC_ALPHA = $0303;  { gl.h:345 }
  GL_DST_ALPHA = $0304;  { gl.h:346 }
  GL_ONE_MINUS_DST_ALPHA = $0305;  { gl.h:347 }
  GL_DST_COLOR = $0306;  { gl.h:348 }
  GL_ONE_MINUS_DST_COLOR = $0307;  { gl.h:349 }
  GL_SRC_ALPHA_SATURATE = $0308;  { gl.h:350 }
  GL_FEEDBACK = $1C01;  { gl.h:353 }
  GL_RENDER = $1C00;  { gl.h:354 }
  GL_SELECT = $1C02;  { gl.h:355 }
  GL_2D = $0600;  { gl.h:358 }
  GL_3D = $0601;  { gl.h:359 }
  GL_3D_COLOR = $0602;  { gl.h:360 }
  GL_3D_COLOR_TEXTURE = $0603;  { gl.h:361 }
  GL_4D_COLOR_TEXTURE = $0604;  { gl.h:362 }
  GL_POINT_TOKEN = $0701;  { gl.h:363 }
  GL_LINE_TOKEN = $0702;  { gl.h:364 }
  GL_LINE_RESET_TOKEN = $0707;  { gl.h:365 }
  GL_POLYGON_TOKEN = $0703;  { gl.h:366 }
  GL_BITMAP_TOKEN = $0704;  { gl.h:367 }
  GL_DRAW_PIXEL_TOKEN = $0705;  { gl.h:368 }
  GL_COPY_PIXEL_TOKEN = $0706;  { gl.h:369 }
  GL_PASS_THROUGH_TOKEN = $0700;  { gl.h:370 }
  GL_FEEDBACK_BUFFER_POINTER = $0DF0;  { gl.h:371 }
  GL_FEEDBACK_BUFFER_SIZE = $0DF1;  { gl.h:372 }
  GL_FEEDBACK_BUFFER_TYPE = $0DF2;  { gl.h:373 }
  GL_SELECTION_BUFFER_POINTER = $0DF3;  { gl.h:376 }
  GL_SELECTION_BUFFER_SIZE = $0DF4;  { gl.h:377 }
  GL_FOG = $0B60;  { gl.h:380 }
  GL_FOG_MODE = $0B65;  { gl.h:381 }
  GL_FOG_DENSITY = $0B62;  { gl.h:382 }
  GL_FOG_COLOR = $0B66;  { gl.h:383 }
  GL_FOG_INDEX = $0B61;  { gl.h:384 }
  GL_FOG_START = $0B63;  { gl.h:385 }
  GL_FOG_END = $0B64;  { gl.h:386 }
  GL_LINEAR = $2601;  { gl.h:387 }
  GL_EXP = $0800;  { gl.h:388 }
  GL_EXP2 = $0801;  { gl.h:389 }
  GL_LOGIC_OP = $0BF1;  { gl.h:392 }
  GL_INDEX_LOGIC_OP = $0BF1;  { gl.h:393 }
  GL_COLOR_LOGIC_OP = $0BF2;  { gl.h:394 }
  GL_LOGIC_OP_MODE = $0BF0;  { gl.h:395 }
  GL_CLEAR = $1500;  { gl.h:396 }
  GL_SET = $150F;  { gl.h:397 }
  GL_COPY = $1503;  { gl.h:398 }
  GL_COPY_INVERTED = $150C;  { gl.h:399 }
  GL_NOOP = $1505;  { gl.h:400 }
  GL_INVERT = $150A;  { gl.h:401 }
  GL_AND = $1501;  { gl.h:402 }
  GL_NAND = $150E;  { gl.h:403 }
  GL_OR = $1507;  { gl.h:404 }
  GL_NOR = $1508;  { gl.h:405 }
  GL_XOR = $1506;  { gl.h:406 }
  GL_EQUIV = $1509;  { gl.h:407 }
  GL_AND_REVERSE = $1502;  { gl.h:408 }
  GL_AND_INVERTED = $1504;  { gl.h:409 }
  GL_OR_REVERSE = $150B;  { gl.h:410 }
  GL_OR_INVERTED = $150D;  { gl.h:411 }
  GL_STENCIL_BITS = $0D57;  { gl.h:414 }
  GL_STENCIL_TEST = $0B90;  { gl.h:415 }
  GL_STENCIL_CLEAR_VALUE = $0B91;  { gl.h:416 }
  GL_STENCIL_FUNC = $0B92;  { gl.h:417 }
  GL_STENCIL_VALUE_MASK = $0B93;  { gl.h:418 }
  GL_STENCIL_FAIL = $0B94;  { gl.h:419 }
  GL_STENCIL_PASS_DEPTH_FAIL = $0B95;  { gl.h:420 }
  GL_STENCIL_PASS_DEPTH_PASS = $0B96;  { gl.h:421 }
  GL_STENCIL_REF = $0B97;  { gl.h:422 }
  GL_STENCIL_WRITEMASK = $0B98;  { gl.h:423 }
  GL_STENCIL_INDEX = $1901;  { gl.h:424 }
  GL_KEEP = $1E00;  { gl.h:425 }
  GL_REPLACE = $1E01;  { gl.h:426 }
  GL_INCR = $1E02;  { gl.h:427 }
  GL_DECR = $1E03;  { gl.h:428 }
  GL_NONE = 0;  { gl.h:431 }
  GL_LEFT = $0406;  { gl.h:432 }
  GL_RIGHT = $0407;  { gl.h:433 }
  GL_FRONT_LEFT = $0400;  { gl.h:437 }
  GL_FRONT_RIGHT = $0401;  { gl.h:438 }
  GL_BACK_LEFT = $0402;  { gl.h:439 }
  GL_BACK_RIGHT = $0403;  { gl.h:440 }
  GL_AUX0 = $0409;  { gl.h:441 }
  GL_AUX1 = $040A;  { gl.h:442 }
  GL_AUX2 = $040B;  { gl.h:443 }
  GL_AUX3 = $040C;  { gl.h:444 }
  GL_COLOR_INDEX = $1900;  { gl.h:445 }
  GL_RED = $1903;  { gl.h:446 }
  GL_GREEN = $1904;  { gl.h:447 }
  GL_BLUE = $1905;  { gl.h:448 }
  GL_ALPHA = $1906;  { gl.h:449 }
  GL_LUMINANCE = $1909;  { gl.h:450 }
  GL_LUMINANCE_ALPHA = $190A;  { gl.h:451 }
  GL_ALPHA_BITS = $0D55;  { gl.h:452 }
  GL_RED_BITS = $0D52;  { gl.h:453 }
  GL_GREEN_BITS = $0D53;  { gl.h:454 }
  GL_BLUE_BITS = $0D54;  { gl.h:455 }
  GL_INDEX_BITS = $0D51;  { gl.h:456 }
  GL_SUBPIXEL_BITS = $0D50;  { gl.h:457 }
  GL_AUX_BUFFERS = $0C00;  { gl.h:458 }
  GL_READ_BUFFER = $0C02;  { gl.h:459 }
  GL_DRAW_BUFFER = $0C01;  { gl.h:460 }
  GL_DOUBLEBUFFER = $0C32;  { gl.h:461 }
  GL_STEREO = $0C33;  { gl.h:462 }
  GL_BITMAP = $1A00;  { gl.h:463 }
  GL_COLOR = $1800;  { gl.h:464 }
  GL_DEPTH = $1801;  { gl.h:465 }
  GL_STENCIL = $1802;  { gl.h:466 }
  GL_DITHER = $0BD0;  { gl.h:467 }
  GL_RGB = $1907;  { gl.h:468 }
  GL_RGBA = $1908;  { gl.h:469 }
  GL_MAX_LIST_NESTING = $0B31;  { gl.h:472 }
  GL_MAX_EVAL_ORDER = $0D30;  { gl.h:473 }
  GL_MAX_LIGHTS = $0D31;  { gl.h:474 }
  GL_MAX_CLIP_PLANES = $0D32;  { gl.h:475 }
  GL_MAX_TEXTURE_SIZE = $0D33;  { gl.h:476 }
  GL_MAX_PIXEL_MAP_TABLE = $0D34;  { gl.h:477 }
  GL_MAX_ATTRIB_STACK_DEPTH = $0D35;  { gl.h:478 }
  GL_MAX_MODELVIEW_STACK_DEPTH = $0D36;  { gl.h:479 }
  GL_MAX_NAME_STACK_DEPTH = $0D37;  { gl.h:480 }
  GL_MAX_PROJECTION_STACK_DEPTH = $0D38;  { gl.h:481 }
  GL_MAX_TEXTURE_STACK_DEPTH = $0D39;  { gl.h:482 }
  GL_MAX_VIEWPORT_DIMS = $0D3A;  { gl.h:483 }
  GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = $0D3B;  { gl.h:484 }
  GL_ATTRIB_STACK_DEPTH = $0BB0;  { gl.h:487 }
  GL_CLIENT_ATTRIB_STACK_DEPTH = $0BB1;  { gl.h:488 }
  GL_COLOR_CLEAR_VALUE = $0C22;  { gl.h:489 }
  GL_COLOR_WRITEMASK = $0C23;  { gl.h:490 }
  GL_CURRENT_INDEX = $0B01;  { gl.h:491 }
  GL_CURRENT_COLOR = $0B00;  { gl.h:492 }
  GL_CURRENT_NORMAL = $0B02;  { gl.h:493 }
  GL_CURRENT_RASTER_COLOR = $0B04;  { gl.h:494 }
  GL_CURRENT_RASTER_DISTANCE = $0B09;  { gl.h:495 }
  GL_CURRENT_RASTER_INDEX = $0B05;  { gl.h:496 }
  GL_CURRENT_RASTER_POSITION = $0B07;  { gl.h:497 }
  GL_CURRENT_RASTER_TEXTURE_COORDS = $0B06;  { gl.h:498 }
  GL_CURRENT_RASTER_POSITION_VALID = $0B08;  { gl.h:499 }
  GL_CURRENT_TEXTURE_COORDS = $0B03;  { gl.h:500 }
  GL_INDEX_CLEAR_VALUE = $0C20;  { gl.h:501 }
  GL_INDEX_MODE = $0C30;  { gl.h:502 }
  GL_INDEX_WRITEMASK = $0C21;  { gl.h:503 }
  GL_MODELVIEW_MATRIX = $0BA6;  { gl.h:504 }
  GL_MODELVIEW_STACK_DEPTH = $0BA3;  { gl.h:505 }
  GL_NAME_STACK_DEPTH = $0D70;  { gl.h:506 }
  GL_PROJECTION_MATRIX = $0BA7;  { gl.h:507 }
  GL_PROJECTION_STACK_DEPTH = $0BA4;  { gl.h:508 }
  GL_RENDER_MODE = $0C40;  { gl.h:509 }
  GL_RGBA_MODE = $0C31;  { gl.h:510 }
  GL_TEXTURE_MATRIX = $0BA8;  { gl.h:511 }
  GL_TEXTURE_STACK_DEPTH = $0BA5;  { gl.h:512 }
  GL_VIEWPORT = $0BA2;  { gl.h:513 }
  GL_AUTO_NORMAL = $0D80;  { gl.h:516 }
  GL_MAP1_COLOR_4 = $0D90;  { gl.h:517 }
  GL_MAP1_INDEX = $0D91;  { gl.h:518 }
  GL_MAP1_NORMAL = $0D92;  { gl.h:519 }
  GL_MAP1_TEXTURE_COORD_1 = $0D93;  { gl.h:520 }
  GL_MAP1_TEXTURE_COORD_2 = $0D94;  { gl.h:521 }
  GL_MAP1_TEXTURE_COORD_3 = $0D95;  { gl.h:522 }
  GL_MAP1_TEXTURE_COORD_4 = $0D96;  { gl.h:523 }
  GL_MAP1_VERTEX_3 = $0D97;  { gl.h:524 }
  GL_MAP1_VERTEX_4 = $0D98;  { gl.h:525 }
  GL_MAP2_COLOR_4 = $0DB0;  { gl.h:526 }
  GL_MAP2_INDEX = $0DB1;  { gl.h:527 }
  GL_MAP2_NORMAL = $0DB2;  { gl.h:528 }
  GL_MAP2_TEXTURE_COORD_1 = $0DB3;  { gl.h:529 }
  GL_MAP2_TEXTURE_COORD_2 = $0DB4;  { gl.h:530 }
  GL_MAP2_TEXTURE_COORD_3 = $0DB5;  { gl.h:531 }
  GL_MAP2_TEXTURE_COORD_4 = $0DB6;  { gl.h:532 }
  GL_MAP2_VERTEX_3 = $0DB7;  { gl.h:533 }
  GL_MAP2_VERTEX_4 = $0DB8;  { gl.h:534 }
  GL_MAP1_GRID_DOMAIN = $0DD0;  { gl.h:535 }
  GL_MAP1_GRID_SEGMENTS = $0DD1;  { gl.h:536 }
  GL_MAP2_GRID_DOMAIN = $0DD2;  { gl.h:537 }
  GL_MAP2_GRID_SEGMENTS = $0DD3;  { gl.h:538 }
  GL_COEFF = $0A00;  { gl.h:539 }
  GL_ORDER = $0A01;  { gl.h:540 }
  GL_DOMAIN = $0A02;  { gl.h:541 }
  GL_PERSPECTIVE_CORRECTION_HINT = $0C50;  { gl.h:544 }
  GL_POINT_SMOOTH_HINT = $0C51;  { gl.h:545 }
  GL_LINE_SMOOTH_HINT = $0C52;  { gl.h:546 }
  GL_POLYGON_SMOOTH_HINT = $0C53;  { gl.h:547 }
  GL_FOG_HINT = $0C54;  { gl.h:548 }
  GL_DONT_CARE = $1100;  { gl.h:549 }
  GL_FASTEST = $1101;  { gl.h:550 }
  GL_NICEST = $1102;  { gl.h:551 }
  GL_SCISSOR_BOX = $0C10;  { gl.h:554 }
  GL_SCISSOR_TEST = $0C11;  { gl.h:555 }
  GL_MAP_COLOR = $0D10;  { gl.h:558 }
  GL_MAP_STENCIL = $0D11;  { gl.h:559 }
  GL_INDEX_SHIFT = $0D12;  { gl.h:560 }
  GL_INDEX_OFFSET = $0D13;  { gl.h:561 }
  GL_RED_SCALE = $0D14;  { gl.h:562 }
  GL_RED_BIAS = $0D15;  { gl.h:563 }
  GL_GREEN_SCALE = $0D18;  { gl.h:564 }
  GL_GREEN_BIAS = $0D19;  { gl.h:565 }
  GL_BLUE_SCALE = $0D1A;  { gl.h:566 }
  GL_BLUE_BIAS = $0D1B;  { gl.h:567 }
  GL_ALPHA_SCALE = $0D1C;  { gl.h:568 }
  GL_ALPHA_BIAS = $0D1D;  { gl.h:569 }
  GL_DEPTH_SCALE = $0D1E;  { gl.h:570 }
  GL_DEPTH_BIAS = $0D1F;  { gl.h:571 }
  GL_PIXEL_MAP_S_TO_S_SIZE = $0CB1;  { gl.h:572 }
  GL_PIXEL_MAP_I_TO_I_SIZE = $0CB0;  { gl.h:573 }
  GL_PIXEL_MAP_I_TO_R_SIZE = $0CB2;  { gl.h:574 }
  GL_PIXEL_MAP_I_TO_G_SIZE = $0CB3;  { gl.h:575 }
  GL_PIXEL_MAP_I_TO_B_SIZE = $0CB4;  { gl.h:576 }
  GL_PIXEL_MAP_I_TO_A_SIZE = $0CB5;  { gl.h:577 }
  GL_PIXEL_MAP_R_TO_R_SIZE = $0CB6;  { gl.h:578 }
  GL_PIXEL_MAP_G_TO_G_SIZE = $0CB7;  { gl.h:579 }
  GL_PIXEL_MAP_B_TO_B_SIZE = $0CB8;  { gl.h:580 }
  GL_PIXEL_MAP_A_TO_A_SIZE = $0CB9;  { gl.h:581 }
  GL_PIXEL_MAP_S_TO_S = $0C71;  { gl.h:582 }
  GL_PIXEL_MAP_I_TO_I = $0C70;  { gl.h:583 }
  GL_PIXEL_MAP_I_TO_R = $0C72;  { gl.h:584 }
  GL_PIXEL_MAP_I_TO_G = $0C73;  { gl.h:585 }
  GL_PIXEL_MAP_I_TO_B = $0C74;  { gl.h:586 }
  GL_PIXEL_MAP_I_TO_A = $0C75;  { gl.h:587 }
  GL_PIXEL_MAP_R_TO_R = $0C76;  { gl.h:588 }
  GL_PIXEL_MAP_G_TO_G = $0C77;  { gl.h:589 }
  GL_PIXEL_MAP_B_TO_B = $0C78;  { gl.h:590 }
  GL_PIXEL_MAP_A_TO_A = $0C79;  { gl.h:591 }
  GL_PACK_ALIGNMENT = $0D05;  { gl.h:592 }
  GL_PACK_LSB_FIRST = $0D01;  { gl.h:593 }
  GL_PACK_ROW_LENGTH = $0D02;  { gl.h:594 }
  GL_PACK_SKIP_PIXELS = $0D04;  { gl.h:595 }
  GL_PACK_SKIP_ROWS = $0D03;  { gl.h:596 }
  GL_PACK_SWAP_BYTES = $0D00;  { gl.h:597 }
  GL_UNPACK_ALIGNMENT = $0CF5;  { gl.h:598 }
  GL_UNPACK_LSB_FIRST = $0CF1;  { gl.h:599 }
  GL_UNPACK_ROW_LENGTH = $0CF2;  { gl.h:600 }
  GL_UNPACK_SKIP_PIXELS = $0CF4;  { gl.h:601 }
  GL_UNPACK_SKIP_ROWS = $0CF3;  { gl.h:602 }
  GL_UNPACK_SWAP_BYTES = $0CF0;  { gl.h:603 }
  GL_ZOOM_X = $0D16;  { gl.h:604 }
  GL_ZOOM_Y = $0D17;  { gl.h:605 }
  GL_TEXTURE_ENV = $2300;  { gl.h:608 }
  GL_TEXTURE_ENV_MODE = $2200;  { gl.h:609 }
  GL_TEXTURE_1D = $0DE0;  { gl.h:610 }
  GL_TEXTURE_2D = $0DE1;  { gl.h:611 }
  GL_TEXTURE_WRAP_S = $2802;  { gl.h:612 }
  GL_TEXTURE_WRAP_T = $2803;  { gl.h:613 }
  GL_TEXTURE_MAG_FILTER = $2800;  { gl.h:614 }
  GL_TEXTURE_MIN_FILTER = $2801;  { gl.h:615 }
  GL_TEXTURE_ENV_COLOR = $2201;  { gl.h:616 }
  GL_TEXTURE_GEN_S = $0C60;  { gl.h:617 }
  GL_TEXTURE_GEN_T = $0C61;  { gl.h:618 }
  GL_TEXTURE_GEN_R = $0C62;  { gl.h:619 }
  GL_TEXTURE_GEN_Q = $0C63;  { gl.h:620 }
  GL_TEXTURE_GEN_MODE = $2500;  { gl.h:621 }
  GL_TEXTURE_BORDER_COLOR = $1004;  { gl.h:622 }
  GL_TEXTURE_WIDTH = $1000;  { gl.h:623 }
  GL_TEXTURE_HEIGHT = $1001;  { gl.h:624 }
  GL_TEXTURE_BORDER = $1005;  { gl.h:625 }
  GL_TEXTURE_COMPONENTS = $1003;  { gl.h:626 }
  GL_TEXTURE_RED_SIZE = $805C;  { gl.h:627 }
  GL_TEXTURE_GREEN_SIZE = $805D;  { gl.h:628 }
  GL_TEXTURE_BLUE_SIZE = $805E;  { gl.h:629 }
  GL_TEXTURE_ALPHA_SIZE = $805F;  { gl.h:630 }
  GL_TEXTURE_LUMINANCE_SIZE = $8060;  { gl.h:631 }
  GL_TEXTURE_INTENSITY_SIZE = $8061;  { gl.h:632 }
  GL_NEAREST_MIPMAP_NEAREST = $2700;  { gl.h:633 }
  GL_NEAREST_MIPMAP_LINEAR = $2702;  { gl.h:634 }
  GL_LINEAR_MIPMAP_NEAREST = $2701;  { gl.h:635 }
  GL_LINEAR_MIPMAP_LINEAR = $2703;  { gl.h:636 }
  GL_OBJECT_LINEAR = $2401;  { gl.h:637 }
  GL_OBJECT_PLANE = $2501;  { gl.h:638 }
  GL_EYE_LINEAR = $2400;  { gl.h:639 }
  GL_EYE_PLANE = $2502;  { gl.h:640 }
  GL_SPHERE_MAP = $2402;  { gl.h:641 }
  GL_DECAL = $2101;  { gl.h:642 }
  GL_MODULATE = $2100;  { gl.h:643 }
  GL_NEAREST = $2600;  { gl.h:644 }
  GL_REPEAT = $2901;  { gl.h:645 }
  GL_CLAMP = $2900;  { gl.h:646 }
  GL_S = $2000;  { gl.h:647 }
  GL_T = $2001;  { gl.h:648 }
  GL_R = $2002;  { gl.h:649 }
  GL_Q = $2003;  { gl.h:650 }
  GL_VENDOR = $1F00;  { gl.h:653 }
  GL_RENDERER = $1F01;  { gl.h:654 }
  GL_VERSION = $1F02;  { gl.h:655 }
  GL_EXTENSIONS = $1F03;  { gl.h:656 }
  GL_NO_ERROR = 0;  { gl.h:659 }
  GL_INVALID_ENUM = $0500;  { gl.h:660 }
  GL_INVALID_VALUE = $0501;  { gl.h:661 }
  GL_INVALID_OPERATION = $0502;  { gl.h:662 }
  GL_STACK_OVERFLOW = $0503;  { gl.h:663 }
  GL_STACK_UNDERFLOW = $0504;  { gl.h:664 }
  GL_OUT_OF_MEMORY = $0505;  { gl.h:665 }
  GL_CURRENT_BIT = $00000001;  { gl.h:668 }
  GL_POINT_BIT = $00000002;  { gl.h:669 }
  GL_LINE_BIT = $00000004;  { gl.h:670 }
  GL_POLYGON_BIT = $00000008;  { gl.h:671 }
  GL_POLYGON_STIPPLE_BIT = $00000010;  { gl.h:672 }
  GL_PIXEL_MODE_BIT = $00000020;  { gl.h:673 }
  GL_LIGHTING_BIT = $00000040;  { gl.h:674 }
  GL_FOG_BIT = $00000080;  { gl.h:675 }
  GL_DEPTH_BUFFER_BIT = $00000100;  { gl.h:676 }
  GL_ACCUM_BUFFER_BIT = $00000200;  { gl.h:677 }
  GL_STENCIL_BUFFER_BIT = $00000400;  { gl.h:678 }
  GL_VIEWPORT_BIT = $00000800;  { gl.h:679 }
  GL_TRANSFORM_BIT = $00001000;  { gl.h:680 }
  GL_ENABLE_BIT = $00002000;  { gl.h:681 }
  GL_COLOR_BUFFER_BIT = $00004000;  { gl.h:682 }
  GL_HINT_BIT = $00008000;  { gl.h:683 }
  GL_EVAL_BIT = $00010000;  { gl.h:684 }
  GL_LIST_BIT = $00020000;  { gl.h:685 }
  GL_TEXTURE_BIT = $00040000;  { gl.h:686 }
  GL_SCISSOR_BIT = $00080000;  { gl.h:687 }
  GL_ALL_ATTRIB_BITS = $FFFFFFFF;  { gl.h:688 }
  GL_PROXY_TEXTURE_1D = $8063;  { gl.h:692 }
  GL_PROXY_TEXTURE_2D = $8064;  { gl.h:693 }
  GL_TEXTURE_PRIORITY = $8066;  { gl.h:694 }
  GL_TEXTURE_RESIDENT = $8067;  { gl.h:695 }
  GL_TEXTURE_BINDING_1D = $8068;  { gl.h:696 }
  GL_TEXTURE_BINDING_2D = $8069;  { gl.h:697 }
  GL_TEXTURE_INTERNAL_FORMAT = $1003;  { gl.h:698 }
  GL_ALPHA4 = $803B;  { gl.h:699 }
  GL_ALPHA8 = $803C;  { gl.h:700 }
  GL_ALPHA12 = $803D;  { gl.h:701 }
  GL_ALPHA16 = $803E;  { gl.h:702 }
  GL_LUMINANCE4 = $803F;  { gl.h:703 }
  GL_LUMINANCE8 = $8040;  { gl.h:704 }
  GL_LUMINANCE12 = $8041;  { gl.h:705 }
  GL_LUMINANCE16 = $8042;  { gl.h:706 }
  GL_LUMINANCE4_ALPHA4 = $8043;  { gl.h:707 }
  GL_LUMINANCE6_ALPHA2 = $8044;  { gl.h:708 }
  GL_LUMINANCE8_ALPHA8 = $8045;  { gl.h:709 }
  GL_LUMINANCE12_ALPHA4 = $8046;  { gl.h:710 }
  GL_LUMINANCE12_ALPHA12 = $8047;  { gl.h:711 }
  GL_LUMINANCE16_ALPHA16 = $8048;  { gl.h:712 }
  GL_INTENSITY = $8049;  { gl.h:713 }
  GL_INTENSITY4 = $804A;  { gl.h:714 }
  GL_INTENSITY8 = $804B;  { gl.h:715 }
  GL_INTENSITY12 = $804C;  { gl.h:716 }
  GL_INTENSITY16 = $804D;  { gl.h:717 }
  GL_R3_G3_B2 = $2A10;  { gl.h:718 }
  GL_RGB4 = $804F;  { gl.h:719 }
  GL_RGB5 = $8050;  { gl.h:720 }
  GL_RGB8 = $8051;  { gl.h:721 }
  GL_RGB10 = $8052;  { gl.h:722 }
  GL_RGB12 = $8053;  { gl.h:723 }
  GL_RGB16 = $8054;  { gl.h:724 }
  GL_RGBA2 = $8055;  { gl.h:725 }
  GL_RGBA4 = $8056;  { gl.h:726 }
  GL_RGB5_A1 = $8057;  { gl.h:727 }
  GL_RGBA8 = $8058;  { gl.h:728 }
  GL_RGB10_A2 = $8059;  { gl.h:729 }
  GL_RGBA12 = $805A;  { gl.h:730 }
  GL_RGBA16 = $805B;  { gl.h:731 }
  GL_CLIENT_PIXEL_STORE_BIT = $00000001;  { gl.h:732 }
  GL_CLIENT_VERTEX_ARRAY_BIT = $00000002;  { gl.h:733 }
  GL_ALL_CLIENT_ATTRIB_BITS = $FFFFFFFF;  { gl.h:734 }
  GL_CLIENT_ALL_ATTRIB_BITS = $FFFFFFFF;  { gl.h:735 }
  GL_RESCALE_NORMAL = $803A;  { gl.h:1446 }
  GL_CLAMP_TO_EDGE = $812F;  { gl.h:1447 }
  GL_MAX_ELEMENTS_VERTICES = $80E8;  { gl.h:1448 }
  GL_MAX_ELEMENTS_INDICES = $80E9;  { gl.h:1449 }
  GL_BGR = $80E0;  { gl.h:1450 }
  GL_BGRA = $80E1;  { gl.h:1451 }
  GL_UNSIGNED_BYTE_3_3_2 = $8032;  { gl.h:1452 }
  GL_UNSIGNED_BYTE_2_3_3_REV = $8362;  { gl.h:1453 }
  GL_UNSIGNED_SHORT_5_6_5 = $8363;  { gl.h:1454 }
  GL_UNSIGNED_SHORT_5_6_5_REV = $8364;  { gl.h:1455 }
  GL_UNSIGNED_SHORT_4_4_4_4 = $8033;  { gl.h:1456 }
  GL_UNSIGNED_SHORT_4_4_4_4_REV = $8365;  { gl.h:1457 }
  GL_UNSIGNED_SHORT_5_5_5_1 = $8034;  { gl.h:1458 }
  GL_UNSIGNED_SHORT_1_5_5_5_REV = $8366;  { gl.h:1459 }
  GL_UNSIGNED_INT_8_8_8_8 = $8035;  { gl.h:1460 }
  GL_UNSIGNED_INT_8_8_8_8_REV = $8367;  { gl.h:1461 }
  GL_UNSIGNED_INT_10_10_10_2 = $8036;  { gl.h:1462 }
  GL_UNSIGNED_INT_2_10_10_10_REV = $8368;  { gl.h:1463 }
  GL_LIGHT_MODEL_COLOR_CONTROL = $81F8;  { gl.h:1464 }
  GL_SINGLE_COLOR = $81F9;  { gl.h:1465 }
  GL_SEPARATE_SPECULAR_COLOR = $81FA;  { gl.h:1466 }
  GL_TEXTURE_MIN_LOD = $813A;  { gl.h:1467 }
  GL_TEXTURE_MAX_LOD = $813B;  { gl.h:1468 }
  GL_TEXTURE_BASE_LEVEL = $813C;  { gl.h:1469 }
  GL_TEXTURE_MAX_LEVEL = $813D;  { gl.h:1470 }
  GL_SMOOTH_POINT_SIZE_RANGE = $0B12;  { gl.h:1471 }
  GL_SMOOTH_POINT_SIZE_GRANULARITY = $0B13;  { gl.h:1472 }
  GL_SMOOTH_LINE_WIDTH_RANGE = $0B22;  { gl.h:1473 }
  GL_SMOOTH_LINE_WIDTH_GRANULARITY = $0B23;  { gl.h:1474 }
  GL_ALIASED_POINT_SIZE_RANGE = $846D;  { gl.h:1475 }
  GL_ALIASED_LINE_WIDTH_RANGE = $846E;  { gl.h:1476 }
  GL_PACK_SKIP_IMAGES = $806B;  { gl.h:1477 }
  GL_PACK_IMAGE_HEIGHT = $806C;  { gl.h:1478 }
  GL_UNPACK_SKIP_IMAGES = $806D;  { gl.h:1479 }
  GL_UNPACK_IMAGE_HEIGHT = $806E;  { gl.h:1480 }
  GL_TEXTURE_3D = $806F;  { gl.h:1481 }
  GL_PROXY_TEXTURE_3D = $8070;  { gl.h:1482 }
  GL_TEXTURE_DEPTH = $8071;  { gl.h:1483 }
  GL_TEXTURE_WRAP_R = $8072;  { gl.h:1484 }
  GL_MAX_3D_TEXTURE_SIZE = $8073;  { gl.h:1485 }
  GL_TEXTURE_BINDING_3D = $806A;  { gl.h:1486 }
  GL_CONSTANT_COLOR = $8001;  { gl.h:1521 }
  GL_ONE_MINUS_CONSTANT_COLOR = $8002;  { gl.h:1522 }
  GL_CONSTANT_ALPHA = $8003;  { gl.h:1523 }
  GL_ONE_MINUS_CONSTANT_ALPHA = $8004;  { gl.h:1524 }
  GL_COLOR_TABLE = $80D0;  { gl.h:1525 }
  GL_POST_CONVOLUTION_COLOR_TABLE = $80D1;  { gl.h:1526 }
  GL_POST_COLOR_MATRIX_COLOR_TABLE = $80D2;  { gl.h:1527 }
  GL_PROXY_COLOR_TABLE = $80D3;  { gl.h:1528 }
  GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = $80D4;  { gl.h:1529 }
  GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = $80D5;  { gl.h:1530 }
  GL_COLOR_TABLE_SCALE = $80D6;  { gl.h:1531 }
  GL_COLOR_TABLE_BIAS = $80D7;  { gl.h:1532 }
  GL_COLOR_TABLE_FORMAT = $80D8;  { gl.h:1533 }
  GL_COLOR_TABLE_WIDTH = $80D9;  { gl.h:1534 }
  GL_COLOR_TABLE_RED_SIZE = $80DA;  { gl.h:1535 }
  GL_COLOR_TABLE_GREEN_SIZE = $80DB;  { gl.h:1536 }
  GL_COLOR_TABLE_BLUE_SIZE = $80DC;  { gl.h:1537 }
  GL_COLOR_TABLE_ALPHA_SIZE = $80DD;  { gl.h:1538 }
  GL_COLOR_TABLE_LUMINANCE_SIZE = $80DE;  { gl.h:1539 }
  GL_COLOR_TABLE_INTENSITY_SIZE = $80DF;  { gl.h:1540 }
  GL_CONVOLUTION_1D = $8010;  { gl.h:1541 }
  GL_CONVOLUTION_2D = $8011;  { gl.h:1542 }
  GL_SEPARABLE_2D = $8012;  { gl.h:1543 }
  GL_CONVOLUTION_BORDER_MODE = $8013;  { gl.h:1544 }
  GL_CONVOLUTION_FILTER_SCALE = $8014;  { gl.h:1545 }
  GL_CONVOLUTION_FILTER_BIAS = $8015;  { gl.h:1546 }
  GL_REDUCE = $8016;  { gl.h:1547 }
  GL_CONVOLUTION_FORMAT = $8017;  { gl.h:1548 }
  GL_CONVOLUTION_WIDTH = $8018;  { gl.h:1549 }
  GL_CONVOLUTION_HEIGHT = $8019;  { gl.h:1550 }
  GL_MAX_CONVOLUTION_WIDTH = $801A;  { gl.h:1551 }
  GL_MAX_CONVOLUTION_HEIGHT = $801B;  { gl.h:1552 }
  GL_POST_CONVOLUTION_RED_SCALE = $801C;  { gl.h:1553 }
  GL_POST_CONVOLUTION_GREEN_SCALE = $801D;  { gl.h:1554 }
  GL_POST_CONVOLUTION_BLUE_SCALE = $801E;  { gl.h:1555 }
  GL_POST_CONVOLUTION_ALPHA_SCALE = $801F;  { gl.h:1556 }
  GL_POST_CONVOLUTION_RED_BIAS = $8020;  { gl.h:1557 }
  GL_POST_CONVOLUTION_GREEN_BIAS = $8021;  { gl.h:1558 }
  GL_POST_CONVOLUTION_BLUE_BIAS = $8022;  { gl.h:1559 }
  GL_POST_CONVOLUTION_ALPHA_BIAS = $8023;  { gl.h:1560 }
  GL_CONSTANT_BORDER = $8151;  { gl.h:1561 }
  GL_REPLICATE_BORDER = $8153;  { gl.h:1562 }
  GL_CONVOLUTION_BORDER_COLOR = $8154;  { gl.h:1563 }
  GL_COLOR_MATRIX = $80B1;  { gl.h:1564 }
  GL_COLOR_MATRIX_STACK_DEPTH = $80B2;  { gl.h:1565 }
  GL_MAX_COLOR_MATRIX_STACK_DEPTH = $80B3;  { gl.h:1566 }
  GL_POST_COLOR_MATRIX_RED_SCALE = $80B4;  { gl.h:1567 }
  GL_POST_COLOR_MATRIX_GREEN_SCALE = $80B5;  { gl.h:1568 }
  GL_POST_COLOR_MATRIX_BLUE_SCALE = $80B6;  { gl.h:1569 }
  GL_POST_COLOR_MATRIX_ALPHA_SCALE = $80B7;  { gl.h:1570 }
  GL_POST_COLOR_MATRIX_RED_BIAS = $80B8;  { gl.h:1571 }
  GL_POST_COLOR_MATRIX_GREEN_BIAS = $80B9;  { gl.h:1572 }
  GL_POST_COLOR_MATRIX_BLUE_BIAS = $80BA;  { gl.h:1573 }
  GL_POST_COLOR_MATRIX_ALPHA_BIAS = $80BB;  { gl.h:1574 }
  GL_HISTOGRAM = $8024;  { gl.h:1575 }
  GL_PROXY_HISTOGRAM = $8025;  { gl.h:1576 }
  GL_HISTOGRAM_WIDTH = $8026;  { gl.h:1577 }
  GL_HISTOGRAM_FORMAT = $8027;  { gl.h:1578 }
  GL_HISTOGRAM_RED_SIZE = $8028;  { gl.h:1579 }
  GL_HISTOGRAM_GREEN_SIZE = $8029;  { gl.h:1580 }
  GL_HISTOGRAM_BLUE_SIZE = $802A;  { gl.h:1581 }
  GL_HISTOGRAM_ALPHA_SIZE = $802B;  { gl.h:1582 }
  GL_HISTOGRAM_LUMINANCE_SIZE = $802C;  { gl.h:1583 }
  GL_HISTOGRAM_SINK = $802D;  { gl.h:1584 }
  GL_MINMAX = $802E;  { gl.h:1585 }
  GL_MINMAX_FORMAT = $802F;  { gl.h:1586 }
  GL_MINMAX_SINK = $8030;  { gl.h:1587 }
  GL_TABLE_TOO_LARGE = $8031;  { gl.h:1588 }
  GL_BLEND_EQUATION = $8009;  { gl.h:1589 }
  GL_MIN = $8007;  { gl.h:1590 }
  GL_MAX = $8008;  { gl.h:1591 }
  GL_FUNC_ADD = $8006;  { gl.h:1592 }
  GL_FUNC_SUBTRACT = $800A;  { gl.h:1593 }
  GL_FUNC_REVERSE_SUBTRACT = $800B;  { gl.h:1594 }
  GL_BLEND_COLOR = $8005;  { gl.h:1595 }
  GL_TEXTURE0 = $84C0;  { gl.h:1714 }
  GL_TEXTURE1 = $84C1;  { gl.h:1715 }
  GL_TEXTURE2 = $84C2;  { gl.h:1716 }
  GL_TEXTURE3 = $84C3;  { gl.h:1717 }
  GL_TEXTURE4 = $84C4;  { gl.h:1718 }
  GL_TEXTURE5 = $84C5;  { gl.h:1719 }
  GL_TEXTURE6 = $84C6;  { gl.h:1720 }
  GL_TEXTURE7 = $84C7;  { gl.h:1721 }
  GL_TEXTURE8 = $84C8;  { gl.h:1722 }
  GL_TEXTURE9 = $84C9;  { gl.h:1723 }
  GL_TEXTURE10 = $84CA;  { gl.h:1724 }
  GL_TEXTURE11 = $84CB;  { gl.h:1725 }
  GL_TEXTURE12 = $84CC;  { gl.h:1726 }
  GL_TEXTURE13 = $84CD;  { gl.h:1727 }
  GL_TEXTURE14 = $84CE;  { gl.h:1728 }
  GL_TEXTURE15 = $84CF;  { gl.h:1729 }
  GL_TEXTURE16 = $84D0;  { gl.h:1730 }
  GL_TEXTURE17 = $84D1;  { gl.h:1731 }
  GL_TEXTURE18 = $84D2;  { gl.h:1732 }
  GL_TEXTURE19 = $84D3;  { gl.h:1733 }
  GL_TEXTURE20 = $84D4;  { gl.h:1734 }
  GL_TEXTURE21 = $84D5;  { gl.h:1735 }
  GL_TEXTURE22 = $84D6;  { gl.h:1736 }
  GL_TEXTURE23 = $84D7;  { gl.h:1737 }
  GL_TEXTURE24 = $84D8;  { gl.h:1738 }
  GL_TEXTURE25 = $84D9;  { gl.h:1739 }
  GL_TEXTURE26 = $84DA;  { gl.h:1740 }
  GL_TEXTURE27 = $84DB;  { gl.h:1741 }
  GL_TEXTURE28 = $84DC;  { gl.h:1742 }
  GL_TEXTURE29 = $84DD;  { gl.h:1743 }
  GL_TEXTURE30 = $84DE;  { gl.h:1744 }
  GL_TEXTURE31 = $84DF;  { gl.h:1745 }
  GL_ACTIVE_TEXTURE = $84E0;  { gl.h:1746 }
  GL_CLIENT_ACTIVE_TEXTURE = $84E1;  { gl.h:1747 }
  GL_MAX_TEXTURE_UNITS = $84E2;  { gl.h:1748 }
  GL_NORMAL_MAP = $8511;  { gl.h:1750 }
  GL_REFLECTION_MAP = $8512;  { gl.h:1751 }
  GL_TEXTURE_CUBE_MAP = $8513;  { gl.h:1752 }
  GL_TEXTURE_BINDING_CUBE_MAP = $8514;  { gl.h:1753 }
  GL_TEXTURE_CUBE_MAP_POSITIVE_X = $8515;  { gl.h:1754 }
  GL_TEXTURE_CUBE_MAP_NEGATIVE_X = $8516;  { gl.h:1755 }
  GL_TEXTURE_CUBE_MAP_POSITIVE_Y = $8517;  { gl.h:1756 }
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = $8518;  { gl.h:1757 }
  GL_TEXTURE_CUBE_MAP_POSITIVE_Z = $8519;  { gl.h:1758 }
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = $851A;  { gl.h:1759 }
  GL_PROXY_TEXTURE_CUBE_MAP = $851B;  { gl.h:1760 }
  GL_MAX_CUBE_MAP_TEXTURE_SIZE = $851C;  { gl.h:1761 }
  GL_COMPRESSED_ALPHA = $84E9;  { gl.h:1763 }
  GL_COMPRESSED_LUMINANCE = $84EA;  { gl.h:1764 }
  GL_COMPRESSED_LUMINANCE_ALPHA = $84EB;  { gl.h:1765 }
  GL_COMPRESSED_INTENSITY = $84EC;  { gl.h:1766 }
  GL_COMPRESSED_RGB = $84ED;  { gl.h:1767 }
  GL_COMPRESSED_RGBA = $84EE;  { gl.h:1768 }
  GL_TEXTURE_COMPRESSION_HINT = $84EF;  { gl.h:1769 }
  GL_TEXTURE_COMPRESSED_IMAGE_SIZE = $86A0;  { gl.h:1770 }
  GL_TEXTURE_COMPRESSED = $86A1;  { gl.h:1771 }
  GL_NUM_COMPRESSED_TEXTURE_FORMATS = $86A2;  { gl.h:1772 }
  GL_COMPRESSED_TEXTURE_FORMATS = $86A3;  { gl.h:1773 }
  GL_MULTISAMPLE = $809D;  { gl.h:1775 }
  GL_SAMPLE_ALPHA_TO_COVERAGE = $809E;  { gl.h:1776 }
  GL_SAMPLE_ALPHA_TO_ONE = $809F;  { gl.h:1777 }
  GL_SAMPLE_COVERAGE = $80A0;  { gl.h:1778 }
  GL_SAMPLE_BUFFERS = $80A8;  { gl.h:1779 }
  GL_SAMPLES = $80A9;  { gl.h:1780 }
  GL_SAMPLE_COVERAGE_VALUE = $80AA;  { gl.h:1781 }
  GL_SAMPLE_COVERAGE_INVERT = $80AB;  { gl.h:1782 }
  GL_MULTISAMPLE_BIT = $20000000;  { gl.h:1783 }
  GL_TRANSPOSE_MODELVIEW_MATRIX = $84E3;  { gl.h:1785 }
  GL_TRANSPOSE_PROJECTION_MATRIX = $84E4;  { gl.h:1786 }
  GL_TRANSPOSE_TEXTURE_MATRIX = $84E5;  { gl.h:1787 }
  GL_TRANSPOSE_COLOR_MATRIX = $84E6;  { gl.h:1788 }
  GL_COMBINE = $8570;  { gl.h:1790 }
  GL_COMBINE_RGB = $8571;  { gl.h:1791 }
  GL_COMBINE_ALPHA = $8572;  { gl.h:1792 }
  GL_SOURCE0_RGB = $8580;  { gl.h:1793 }
  GL_SOURCE1_RGB = $8581;  { gl.h:1794 }
  GL_SOURCE2_RGB = $8582;  { gl.h:1795 }
  GL_SOURCE0_ALPHA = $8588;  { gl.h:1796 }
  GL_SOURCE1_ALPHA = $8589;  { gl.h:1797 }
  GL_SOURCE2_ALPHA = $858A;  { gl.h:1798 }
  GL_OPERAND0_RGB = $8590;  { gl.h:1799 }
  GL_OPERAND1_RGB = $8591;  { gl.h:1800 }
  GL_OPERAND2_RGB = $8592;  { gl.h:1801 }
  GL_OPERAND0_ALPHA = $8598;  { gl.h:1802 }
  GL_OPERAND1_ALPHA = $8599;  { gl.h:1803 }
  GL_OPERAND2_ALPHA = $859A;  { gl.h:1804 }
  GL_RGB_SCALE = $8573;  { gl.h:1805 }
  GL_ADD_SIGNED = $8574;  { gl.h:1806 }
  GL_INTERPOLATE = $8575;  { gl.h:1807 }
  GL_SUBTRACT = $84E7;  { gl.h:1808 }
  GL_CONSTANT = $8576;  { gl.h:1809 }
  GL_PRIMARY_COLOR = $8577;  { gl.h:1810 }
  GL_PREVIOUS = $8578;  { gl.h:1811 }
  GL_DOT3_RGB = $86AE;  { gl.h:1813 }
  GL_DOT3_RGBA = $86AF;  { gl.h:1814 }
  GL_CLAMP_TO_BORDER = $812D;  { gl.h:1816 }
  GL_ARB_multitexture = 1;  { gl.h:1928 }
  GL_TEXTURE0_ARB = $84C0;  { gl.h:1930 }
  GL_TEXTURE1_ARB = $84C1;  { gl.h:1931 }
  GL_TEXTURE2_ARB = $84C2;  { gl.h:1932 }
  GL_TEXTURE3_ARB = $84C3;  { gl.h:1933 }
  GL_TEXTURE4_ARB = $84C4;  { gl.h:1934 }
  GL_TEXTURE5_ARB = $84C5;  { gl.h:1935 }
  GL_TEXTURE6_ARB = $84C6;  { gl.h:1936 }
  GL_TEXTURE7_ARB = $84C7;  { gl.h:1937 }
  GL_TEXTURE8_ARB = $84C8;  { gl.h:1938 }
  GL_TEXTURE9_ARB = $84C9;  { gl.h:1939 }
  GL_TEXTURE10_ARB = $84CA;  { gl.h:1940 }
  GL_TEXTURE11_ARB = $84CB;  { gl.h:1941 }
  GL_TEXTURE12_ARB = $84CC;  { gl.h:1942 }
  GL_TEXTURE13_ARB = $84CD;  { gl.h:1943 }
  GL_TEXTURE14_ARB = $84CE;  { gl.h:1944 }
  GL_TEXTURE15_ARB = $84CF;  { gl.h:1945 }
  GL_TEXTURE16_ARB = $84D0;  { gl.h:1946 }
  GL_TEXTURE17_ARB = $84D1;  { gl.h:1947 }
  GL_TEXTURE18_ARB = $84D2;  { gl.h:1948 }
  GL_TEXTURE19_ARB = $84D3;  { gl.h:1949 }
  GL_TEXTURE20_ARB = $84D4;  { gl.h:1950 }
  GL_TEXTURE21_ARB = $84D5;  { gl.h:1951 }
  GL_TEXTURE22_ARB = $84D6;  { gl.h:1952 }
  GL_TEXTURE23_ARB = $84D7;  { gl.h:1953 }
  GL_TEXTURE24_ARB = $84D8;  { gl.h:1954 }
  GL_TEXTURE25_ARB = $84D9;  { gl.h:1955 }
  GL_TEXTURE26_ARB = $84DA;  { gl.h:1956 }
  GL_TEXTURE27_ARB = $84DB;  { gl.h:1957 }
  GL_TEXTURE28_ARB = $84DC;  { gl.h:1958 }
  GL_TEXTURE29_ARB = $84DD;  { gl.h:1959 }
  GL_TEXTURE30_ARB = $84DE;  { gl.h:1960 }
  GL_TEXTURE31_ARB = $84DF;  { gl.h:1961 }
  GL_ACTIVE_TEXTURE_ARB = $84E0;  { gl.h:1962 }
  GL_CLIENT_ACTIVE_TEXTURE_ARB = $84E1;  { gl.h:1963 }
  GL_MAX_TEXTURE_UNITS_ARB = $84E2;  { gl.h:1964 }
  GL_MESA_packed_depth_stencil = 1;  { gl.h:2061 }
  GL_DEPTH_STENCIL_MESA = $8750;  { gl.h:2063 }
  GL_UNSIGNED_INT_24_8_MESA = $8751;  { gl.h:2064 }
  GL_UNSIGNED_INT_8_24_REV_MESA = $8752;  { gl.h:2065 }
  GL_UNSIGNED_SHORT_15_1_MESA = $8753;  { gl.h:2066 }
  GL_UNSIGNED_SHORT_1_15_REV_MESA = $8754;  { gl.h:2067 }
  GL_ATI_blend_equation_separate = 1;  { gl.h:2073 }
  GL_ALPHA_BLEND_EQUATION_ATI = $883D;  { gl.h:2075 }
  GL_OES_EGL_image = 1;  { gl.h:2089 }

procedure glClearIndex(c: GLfloat); cdecl; external 'libGL' name 'glClearIndex';  { gl.h:743 }
procedure glClearColor(red: GLclampf; green: GLclampf; blue: GLclampf; alpha: GLclampf); cdecl; external 'libGL' name 'glClearColor';  { gl.h:745 }
procedure glClear(mask: GLbitfield); cdecl; external 'libGL' name 'glClear';  { gl.h:747 }
procedure glIndexMask(mask: GLuint); cdecl; external 'libGL' name 'glIndexMask';  { gl.h:749 }
procedure glColorMask(red: GLboolean; green: GLboolean; blue: GLboolean; alpha: GLboolean); cdecl; external 'libGL' name 'glColorMask';  { gl.h:751 }
procedure glAlphaFunc(func: GLenum; ref: GLclampf); cdecl; external 'libGL' name 'glAlphaFunc';  { gl.h:753 }
procedure glBlendFunc(sfactor: GLenum; dfactor: GLenum); cdecl; external 'libGL' name 'glBlendFunc';  { gl.h:755 }
procedure glLogicOp(opcode: GLenum); cdecl; external 'libGL' name 'glLogicOp';  { gl.h:757 }
procedure glCullFace(mode: GLenum); cdecl; external 'libGL' name 'glCullFace';  { gl.h:759 }
procedure glFrontFace(mode: GLenum); cdecl; external 'libGL' name 'glFrontFace';  { gl.h:761 }
procedure glPointSize(size: GLfloat); cdecl; external 'libGL' name 'glPointSize';  { gl.h:763 }
procedure glLineWidth(width: GLfloat); cdecl; external 'libGL' name 'glLineWidth';  { gl.h:765 }
procedure glLineStipple(factor: GLint; pattern: GLushort); cdecl; external 'libGL' name 'glLineStipple';  { gl.h:767 }
procedure glPolygonMode(face: GLenum; mode: GLenum); cdecl; external 'libGL' name 'glPolygonMode';  { gl.h:769 }
procedure glPolygonOffset(factor: GLfloat; units: GLfloat); cdecl; external 'libGL' name 'glPolygonOffset';  { gl.h:771 }
procedure glPolygonStipple(mask: Pcuchar); cdecl; external 'libGL' name 'glPolygonStipple';  { gl.h:773 }
procedure glGetPolygonStipple(mask: PGLubyte); cdecl; external 'libGL' name 'glGetPolygonStipple';  { gl.h:775 }
procedure glEdgeFlag(flag: GLboolean); cdecl; external 'libGL' name 'glEdgeFlag';  { gl.h:777 }
procedure glEdgeFlagv(flag: Pcuchar); cdecl; external 'libGL' name 'glEdgeFlagv';  { gl.h:779 }
procedure glScissor(x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'libGL' name 'glScissor';  { gl.h:781 }
procedure glClipPlane(plane: GLenum; equation: Pcdouble); cdecl; external 'libGL' name 'glClipPlane';  { gl.h:783 }
procedure glGetClipPlane(plane: GLenum; equation: PGLdouble); cdecl; external 'libGL' name 'glGetClipPlane';  { gl.h:785 }
procedure glDrawBuffer(mode: GLenum); cdecl; external 'libGL' name 'glDrawBuffer';  { gl.h:787 }
procedure glReadBuffer(mode: GLenum); cdecl; external 'libGL' name 'glReadBuffer';  { gl.h:789 }
procedure glEnable(cap: GLenum); cdecl; external 'libGL' name 'glEnable';  { gl.h:791 }
procedure glDisable(cap: GLenum); cdecl; external 'libGL' name 'glDisable';  { gl.h:793 }
function glIsEnabled(cap: GLenum): GLboolean; cdecl; external 'libGL' name 'glIsEnabled';  { gl.h:795 }
procedure glEnableClientState(cap: GLenum); cdecl; external 'libGL' name 'glEnableClientState';  { gl.h:798 }
procedure glDisableClientState(cap: GLenum); cdecl; external 'libGL' name 'glDisableClientState';  { gl.h:800 }
procedure glGetBooleanv(pname: GLenum; params: PGLboolean); cdecl; external 'libGL' name 'glGetBooleanv';  { gl.h:803 }
procedure glGetDoublev(pname: GLenum; params: PGLdouble); cdecl; external 'libGL' name 'glGetDoublev';  { gl.h:805 }
procedure glGetFloatv(pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetFloatv';  { gl.h:807 }
procedure glGetIntegerv(pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetIntegerv';  { gl.h:809 }
procedure glPushAttrib(mask: GLbitfield); cdecl; external 'libGL' name 'glPushAttrib';  { gl.h:812 }
procedure glPopAttrib; cdecl; external 'libGL' name 'glPopAttrib';  { gl.h:814 }
procedure glPushClientAttrib(mask: GLbitfield); cdecl; external 'libGL' name 'glPushClientAttrib';  { gl.h:817 }
procedure glPopClientAttrib; cdecl; external 'libGL' name 'glPopClientAttrib';  { gl.h:819 }
function glRenderMode(mode: GLenum): GLint; cdecl; external 'libGL' name 'glRenderMode';  { gl.h:822 }
function glGetError: GLenum; cdecl; external 'libGL' name 'glGetError';  { gl.h:824 }
function glGetString(name: GLenum): Pcuchar; cdecl; external 'libGL' name 'glGetString';  { gl.h:826 }
procedure glFinish; cdecl; external 'libGL' name 'glFinish';  { gl.h:828 }
procedure glFlush; cdecl; external 'libGL' name 'glFlush';  { gl.h:830 }
procedure glHint(target: GLenum; mode: GLenum); cdecl; external 'libGL' name 'glHint';  { gl.h:832 }
procedure glClearDepth(depth: GLclampd); cdecl; external 'libGL' name 'glClearDepth';  { gl.h:839 }
procedure glDepthFunc(func: GLenum); cdecl; external 'libGL' name 'glDepthFunc';  { gl.h:841 }
procedure glDepthMask(flag: GLboolean); cdecl; external 'libGL' name 'glDepthMask';  { gl.h:843 }
procedure glDepthRange(near_val: GLclampd; far_val: GLclampd); cdecl; external 'libGL' name 'glDepthRange';  { gl.h:845 }
procedure glClearAccum(red: GLfloat; green: GLfloat; blue: GLfloat; alpha: GLfloat); cdecl; external 'libGL' name 'glClearAccum';  { gl.h:852 }
procedure glAccum(op: GLenum; value: GLfloat); cdecl; external 'libGL' name 'glAccum';  { gl.h:854 }
procedure glMatrixMode(mode: GLenum); cdecl; external 'libGL' name 'glMatrixMode';  { gl.h:861 }
procedure glOrtho(left: GLdouble; right: GLdouble; bottom: GLdouble; top: GLdouble; near_val: GLdouble; far_val: GLdouble); cdecl; external 'libGL' name 'glOrtho';  { gl.h:863 }
procedure glFrustum(left: GLdouble; right: GLdouble; bottom: GLdouble; top: GLdouble; near_val: GLdouble; far_val: GLdouble); cdecl; external 'libGL' name 'glFrustum';  { gl.h:867 }
procedure glViewport(x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'libGL' name 'glViewport';  { gl.h:871 }
procedure glPushMatrix; cdecl; external 'libGL' name 'glPushMatrix';  { gl.h:874 }
procedure glPopMatrix; cdecl; external 'libGL' name 'glPopMatrix';  { gl.h:876 }
procedure glLoadIdentity; cdecl; external 'libGL' name 'glLoadIdentity';  { gl.h:878 }
procedure glLoadMatrixd(m: Pcdouble); cdecl; external 'libGL' name 'glLoadMatrixd';  { gl.h:880 }
procedure glLoadMatrixf(m: Pcfloat); cdecl; external 'libGL' name 'glLoadMatrixf';  { gl.h:881 }
procedure glMultMatrixd(m: Pcdouble); cdecl; external 'libGL' name 'glMultMatrixd';  { gl.h:883 }
procedure glMultMatrixf(m: Pcfloat); cdecl; external 'libGL' name 'glMultMatrixf';  { gl.h:884 }
procedure glRotated(angle: GLdouble; x: GLdouble; y: GLdouble; z: GLdouble); cdecl; external 'libGL' name 'glRotated';  { gl.h:886 }
procedure glRotatef(angle: GLfloat; x: GLfloat; y: GLfloat; z: GLfloat); cdecl; external 'libGL' name 'glRotatef';  { gl.h:888 }
procedure glScaled(x: GLdouble; y: GLdouble; z: GLdouble); cdecl; external 'libGL' name 'glScaled';  { gl.h:891 }
procedure glScalef(x: GLfloat; y: GLfloat; z: GLfloat); cdecl; external 'libGL' name 'glScalef';  { gl.h:892 }
procedure glTranslated(x: GLdouble; y: GLdouble; z: GLdouble); cdecl; external 'libGL' name 'glTranslated';  { gl.h:894 }
procedure glTranslatef(x: GLfloat; y: GLfloat; z: GLfloat); cdecl; external 'libGL' name 'glTranslatef';  { gl.h:895 }
function glIsList(list: GLuint): GLboolean; cdecl; external 'libGL' name 'glIsList';  { gl.h:902 }
procedure glDeleteLists(list: GLuint; range: GLsizei); cdecl; external 'libGL' name 'glDeleteLists';  { gl.h:904 }
function glGenLists(range: GLsizei): GLuint; cdecl; external 'libGL' name 'glGenLists';  { gl.h:906 }
procedure glNewList(list: GLuint; mode: GLenum); cdecl; external 'libGL' name 'glNewList';  { gl.h:908 }
procedure glEndList; cdecl; external 'libGL' name 'glEndList';  { gl.h:910 }
procedure glCallList(list: GLuint); cdecl; external 'libGL' name 'glCallList';  { gl.h:912 }
procedure glCallLists(n: GLsizei; type_: GLenum; lists: Pointer); cdecl; external 'libGL' name 'glCallLists';  { gl.h:914 }
procedure glListBase(base: GLuint); cdecl; external 'libGL' name 'glListBase';  { gl.h:917 }
procedure glBegin(mode: GLenum); cdecl; external 'libGL' name 'glBegin';  { gl.h:924 }
procedure glEnd; cdecl; external 'libGL' name 'glEnd';  { gl.h:926 }
procedure glVertex2d(x: GLdouble; y: GLdouble); cdecl; external 'libGL' name 'glVertex2d';  { gl.h:929 }
procedure glVertex2f(x: GLfloat; y: GLfloat); cdecl; external 'libGL' name 'glVertex2f';  { gl.h:930 }
procedure glVertex2i(x: GLint; y: GLint); cdecl; external 'libGL' name 'glVertex2i';  { gl.h:931 }
procedure glVertex2s(x: GLshort; y: GLshort); cdecl; external 'libGL' name 'glVertex2s';  { gl.h:932 }
procedure glVertex3d(x: GLdouble; y: GLdouble; z: GLdouble); cdecl; external 'libGL' name 'glVertex3d';  { gl.h:934 }
procedure glVertex3f(x: GLfloat; y: GLfloat; z: GLfloat); cdecl; external 'libGL' name 'glVertex3f';  { gl.h:935 }
procedure glVertex3i(x: GLint; y: GLint; z: GLint); cdecl; external 'libGL' name 'glVertex3i';  { gl.h:936 }
procedure glVertex3s(x: GLshort; y: GLshort; z: GLshort); cdecl; external 'libGL' name 'glVertex3s';  { gl.h:937 }
procedure glVertex4d(x: GLdouble; y: GLdouble; z: GLdouble; w: GLdouble); cdecl; external 'libGL' name 'glVertex4d';  { gl.h:939 }
procedure glVertex4f(x: GLfloat; y: GLfloat; z: GLfloat; w: GLfloat); cdecl; external 'libGL' name 'glVertex4f';  { gl.h:940 }
procedure glVertex4i(x: GLint; y: GLint; z: GLint; w: GLint); cdecl; external 'libGL' name 'glVertex4i';  { gl.h:941 }
procedure glVertex4s(x: GLshort; y: GLshort; z: GLshort; w: GLshort); cdecl; external 'libGL' name 'glVertex4s';  { gl.h:942 }
procedure glVertex2dv(v: Pcdouble); cdecl; external 'libGL' name 'glVertex2dv';  { gl.h:944 }
procedure glVertex2fv(v: Pcfloat); cdecl; external 'libGL' name 'glVertex2fv';  { gl.h:945 }
procedure glVertex2iv(v: Pcint); cdecl; external 'libGL' name 'glVertex2iv';  { gl.h:946 }
procedure glVertex2sv(v: Pcshort); cdecl; external 'libGL' name 'glVertex2sv';  { gl.h:947 }
procedure glVertex3dv(v: Pcdouble); cdecl; external 'libGL' name 'glVertex3dv';  { gl.h:949 }
procedure glVertex3fv(v: Pcfloat); cdecl; external 'libGL' name 'glVertex3fv';  { gl.h:950 }
procedure glVertex3iv(v: Pcint); cdecl; external 'libGL' name 'glVertex3iv';  { gl.h:951 }
procedure glVertex3sv(v: Pcshort); cdecl; external 'libGL' name 'glVertex3sv';  { gl.h:952 }
procedure glVertex4dv(v: Pcdouble); cdecl; external 'libGL' name 'glVertex4dv';  { gl.h:954 }
procedure glVertex4fv(v: Pcfloat); cdecl; external 'libGL' name 'glVertex4fv';  { gl.h:955 }
procedure glVertex4iv(v: Pcint); cdecl; external 'libGL' name 'glVertex4iv';  { gl.h:956 }
procedure glVertex4sv(v: Pcshort); cdecl; external 'libGL' name 'glVertex4sv';  { gl.h:957 }
procedure glNormal3b(nx: GLbyte; ny: GLbyte; nz: GLbyte); cdecl; external 'libGL' name 'glNormal3b';  { gl.h:960 }
procedure glNormal3d(nx: GLdouble; ny: GLdouble; nz: GLdouble); cdecl; external 'libGL' name 'glNormal3d';  { gl.h:961 }
procedure glNormal3f(nx: GLfloat; ny: GLfloat; nz: GLfloat); cdecl; external 'libGL' name 'glNormal3f';  { gl.h:962 }
procedure glNormal3i(nx: GLint; ny: GLint; nz: GLint); cdecl; external 'libGL' name 'glNormal3i';  { gl.h:963 }
procedure glNormal3s(nx: GLshort; ny: GLshort; nz: GLshort); cdecl; external 'libGL' name 'glNormal3s';  { gl.h:964 }
procedure glNormal3bv(v: PAnsiChar); cdecl; external 'libGL' name 'glNormal3bv';  { gl.h:966 }
procedure glNormal3dv(v: Pcdouble); cdecl; external 'libGL' name 'glNormal3dv';  { gl.h:967 }
procedure glNormal3fv(v: Pcfloat); cdecl; external 'libGL' name 'glNormal3fv';  { gl.h:968 }
procedure glNormal3iv(v: Pcint); cdecl; external 'libGL' name 'glNormal3iv';  { gl.h:969 }
procedure glNormal3sv(v: Pcshort); cdecl; external 'libGL' name 'glNormal3sv';  { gl.h:970 }
procedure glIndexd(c: GLdouble); cdecl; external 'libGL' name 'glIndexd';  { gl.h:973 }
procedure glIndexf(c: GLfloat); cdecl; external 'libGL' name 'glIndexf';  { gl.h:974 }
procedure glIndexi(c: GLint); cdecl; external 'libGL' name 'glIndexi';  { gl.h:975 }
procedure glIndexs(c: GLshort); cdecl; external 'libGL' name 'glIndexs';  { gl.h:976 }
procedure glIndexub(c: GLubyte); cdecl; external 'libGL' name 'glIndexub';  { gl.h:977 }
procedure glIndexdv(c: Pcdouble); cdecl; external 'libGL' name 'glIndexdv';  { gl.h:979 }
procedure glIndexfv(c: Pcfloat); cdecl; external 'libGL' name 'glIndexfv';  { gl.h:980 }
procedure glIndexiv(c: Pcint); cdecl; external 'libGL' name 'glIndexiv';  { gl.h:981 }
procedure glIndexsv(c: Pcshort); cdecl; external 'libGL' name 'glIndexsv';  { gl.h:982 }
procedure glIndexubv(c: Pcuchar); cdecl; external 'libGL' name 'glIndexubv';  { gl.h:983 }
procedure glColor3b(red: GLbyte; green: GLbyte; blue: GLbyte); cdecl; external 'libGL' name 'glColor3b';  { gl.h:985 }
procedure glColor3d(red: GLdouble; green: GLdouble; blue: GLdouble); cdecl; external 'libGL' name 'glColor3d';  { gl.h:986 }
procedure glColor3f(red: GLfloat; green: GLfloat; blue: GLfloat); cdecl; external 'libGL' name 'glColor3f';  { gl.h:987 }
procedure glColor3i(red: GLint; green: GLint; blue: GLint); cdecl; external 'libGL' name 'glColor3i';  { gl.h:988 }
procedure glColor3s(red: GLshort; green: GLshort; blue: GLshort); cdecl; external 'libGL' name 'glColor3s';  { gl.h:989 }
procedure glColor3ub(red: GLubyte; green: GLubyte; blue: GLubyte); cdecl; external 'libGL' name 'glColor3ub';  { gl.h:990 }
procedure glColor3ui(red: GLuint; green: GLuint; blue: GLuint); cdecl; external 'libGL' name 'glColor3ui';  { gl.h:991 }
procedure glColor3us(red: GLushort; green: GLushort; blue: GLushort); cdecl; external 'libGL' name 'glColor3us';  { gl.h:992 }
procedure glColor4b(red: GLbyte; green: GLbyte; blue: GLbyte; alpha: GLbyte); cdecl; external 'libGL' name 'glColor4b';  { gl.h:994 }
procedure glColor4d(red: GLdouble; green: GLdouble; blue: GLdouble; alpha: GLdouble); cdecl; external 'libGL' name 'glColor4d';  { gl.h:996 }
procedure glColor4f(red: GLfloat; green: GLfloat; blue: GLfloat; alpha: GLfloat); cdecl; external 'libGL' name 'glColor4f';  { gl.h:998 }
procedure glColor4i(red: GLint; green: GLint; blue: GLint; alpha: GLint); cdecl; external 'libGL' name 'glColor4i';  { gl.h:1000 }
procedure glColor4s(red: GLshort; green: GLshort; blue: GLshort; alpha: GLshort); cdecl; external 'libGL' name 'glColor4s';  { gl.h:1002 }
procedure glColor4ub(red: GLubyte; green: GLubyte; blue: GLubyte; alpha: GLubyte); cdecl; external 'libGL' name 'glColor4ub';  { gl.h:1004 }
procedure glColor4ui(red: GLuint; green: GLuint; blue: GLuint; alpha: GLuint); cdecl; external 'libGL' name 'glColor4ui';  { gl.h:1006 }
procedure glColor4us(red: GLushort; green: GLushort; blue: GLushort; alpha: GLushort); cdecl; external 'libGL' name 'glColor4us';  { gl.h:1008 }
procedure glColor3bv(v: PAnsiChar); cdecl; external 'libGL' name 'glColor3bv';  { gl.h:1012 }
procedure glColor3dv(v: Pcdouble); cdecl; external 'libGL' name 'glColor3dv';  { gl.h:1013 }
procedure glColor3fv(v: Pcfloat); cdecl; external 'libGL' name 'glColor3fv';  { gl.h:1014 }
procedure glColor3iv(v: Pcint); cdecl; external 'libGL' name 'glColor3iv';  { gl.h:1015 }
procedure glColor3sv(v: Pcshort); cdecl; external 'libGL' name 'glColor3sv';  { gl.h:1016 }
procedure glColor3ubv(v: Pcuchar); cdecl; external 'libGL' name 'glColor3ubv';  { gl.h:1017 }
procedure glColor3uiv(v: Pcuint); cdecl; external 'libGL' name 'glColor3uiv';  { gl.h:1018 }
procedure glColor3usv(v: Pcushort); cdecl; external 'libGL' name 'glColor3usv';  { gl.h:1019 }
procedure glColor4bv(v: PAnsiChar); cdecl; external 'libGL' name 'glColor4bv';  { gl.h:1021 }
procedure glColor4dv(v: Pcdouble); cdecl; external 'libGL' name 'glColor4dv';  { gl.h:1022 }
procedure glColor4fv(v: Pcfloat); cdecl; external 'libGL' name 'glColor4fv';  { gl.h:1023 }
procedure glColor4iv(v: Pcint); cdecl; external 'libGL' name 'glColor4iv';  { gl.h:1024 }
procedure glColor4sv(v: Pcshort); cdecl; external 'libGL' name 'glColor4sv';  { gl.h:1025 }
procedure glColor4ubv(v: Pcuchar); cdecl; external 'libGL' name 'glColor4ubv';  { gl.h:1026 }
procedure glColor4uiv(v: Pcuint); cdecl; external 'libGL' name 'glColor4uiv';  { gl.h:1027 }
procedure glColor4usv(v: Pcushort); cdecl; external 'libGL' name 'glColor4usv';  { gl.h:1028 }
procedure glTexCoord1d(s: GLdouble); cdecl; external 'libGL' name 'glTexCoord1d';  { gl.h:1031 }
procedure glTexCoord1f(s: GLfloat); cdecl; external 'libGL' name 'glTexCoord1f';  { gl.h:1032 }
procedure glTexCoord1i(s: GLint); cdecl; external 'libGL' name 'glTexCoord1i';  { gl.h:1033 }
procedure glTexCoord1s(s: GLshort); cdecl; external 'libGL' name 'glTexCoord1s';  { gl.h:1034 }
procedure glTexCoord2d(s: GLdouble; t: GLdouble); cdecl; external 'libGL' name 'glTexCoord2d';  { gl.h:1036 }
procedure glTexCoord2f(s: GLfloat; t: GLfloat); cdecl; external 'libGL' name 'glTexCoord2f';  { gl.h:1037 }
procedure glTexCoord2i(s: GLint; t: GLint); cdecl; external 'libGL' name 'glTexCoord2i';  { gl.h:1038 }
procedure glTexCoord2s(s: GLshort; t: GLshort); cdecl; external 'libGL' name 'glTexCoord2s';  { gl.h:1039 }
procedure glTexCoord3d(s: GLdouble; t: GLdouble; r: GLdouble); cdecl; external 'libGL' name 'glTexCoord3d';  { gl.h:1041 }
procedure glTexCoord3f(s: GLfloat; t: GLfloat; r: GLfloat); cdecl; external 'libGL' name 'glTexCoord3f';  { gl.h:1042 }
procedure glTexCoord3i(s: GLint; t: GLint; r: GLint); cdecl; external 'libGL' name 'glTexCoord3i';  { gl.h:1043 }
procedure glTexCoord3s(s: GLshort; t: GLshort; r: GLshort); cdecl; external 'libGL' name 'glTexCoord3s';  { gl.h:1044 }
procedure glTexCoord4d(s: GLdouble; t: GLdouble; r: GLdouble; q: GLdouble); cdecl; external 'libGL' name 'glTexCoord4d';  { gl.h:1046 }
procedure glTexCoord4f(s: GLfloat; t: GLfloat; r: GLfloat; q: GLfloat); cdecl; external 'libGL' name 'glTexCoord4f';  { gl.h:1047 }
procedure glTexCoord4i(s: GLint; t: GLint; r: GLint; q: GLint); cdecl; external 'libGL' name 'glTexCoord4i';  { gl.h:1048 }
procedure glTexCoord4s(s: GLshort; t: GLshort; r: GLshort; q: GLshort); cdecl; external 'libGL' name 'glTexCoord4s';  { gl.h:1049 }
procedure glTexCoord1dv(v: Pcdouble); cdecl; external 'libGL' name 'glTexCoord1dv';  { gl.h:1051 }
procedure glTexCoord1fv(v: Pcfloat); cdecl; external 'libGL' name 'glTexCoord1fv';  { gl.h:1052 }
procedure glTexCoord1iv(v: Pcint); cdecl; external 'libGL' name 'glTexCoord1iv';  { gl.h:1053 }
procedure glTexCoord1sv(v: Pcshort); cdecl; external 'libGL' name 'glTexCoord1sv';  { gl.h:1054 }
procedure glTexCoord2dv(v: Pcdouble); cdecl; external 'libGL' name 'glTexCoord2dv';  { gl.h:1056 }
procedure glTexCoord2fv(v: Pcfloat); cdecl; external 'libGL' name 'glTexCoord2fv';  { gl.h:1057 }
procedure glTexCoord2iv(v: Pcint); cdecl; external 'libGL' name 'glTexCoord2iv';  { gl.h:1058 }
procedure glTexCoord2sv(v: Pcshort); cdecl; external 'libGL' name 'glTexCoord2sv';  { gl.h:1059 }
procedure glTexCoord3dv(v: Pcdouble); cdecl; external 'libGL' name 'glTexCoord3dv';  { gl.h:1061 }
procedure glTexCoord3fv(v: Pcfloat); cdecl; external 'libGL' name 'glTexCoord3fv';  { gl.h:1062 }
procedure glTexCoord3iv(v: Pcint); cdecl; external 'libGL' name 'glTexCoord3iv';  { gl.h:1063 }
procedure glTexCoord3sv(v: Pcshort); cdecl; external 'libGL' name 'glTexCoord3sv';  { gl.h:1064 }
procedure glTexCoord4dv(v: Pcdouble); cdecl; external 'libGL' name 'glTexCoord4dv';  { gl.h:1066 }
procedure glTexCoord4fv(v: Pcfloat); cdecl; external 'libGL' name 'glTexCoord4fv';  { gl.h:1067 }
procedure glTexCoord4iv(v: Pcint); cdecl; external 'libGL' name 'glTexCoord4iv';  { gl.h:1068 }
procedure glTexCoord4sv(v: Pcshort); cdecl; external 'libGL' name 'glTexCoord4sv';  { gl.h:1069 }
procedure glRasterPos2d(x: GLdouble; y: GLdouble); cdecl; external 'libGL' name 'glRasterPos2d';  { gl.h:1072 }
procedure glRasterPos2f(x: GLfloat; y: GLfloat); cdecl; external 'libGL' name 'glRasterPos2f';  { gl.h:1073 }
procedure glRasterPos2i(x: GLint; y: GLint); cdecl; external 'libGL' name 'glRasterPos2i';  { gl.h:1074 }
procedure glRasterPos2s(x: GLshort; y: GLshort); cdecl; external 'libGL' name 'glRasterPos2s';  { gl.h:1075 }
procedure glRasterPos3d(x: GLdouble; y: GLdouble; z: GLdouble); cdecl; external 'libGL' name 'glRasterPos3d';  { gl.h:1077 }
procedure glRasterPos3f(x: GLfloat; y: GLfloat; z: GLfloat); cdecl; external 'libGL' name 'glRasterPos3f';  { gl.h:1078 }
procedure glRasterPos3i(x: GLint; y: GLint; z: GLint); cdecl; external 'libGL' name 'glRasterPos3i';  { gl.h:1079 }
procedure glRasterPos3s(x: GLshort; y: GLshort; z: GLshort); cdecl; external 'libGL' name 'glRasterPos3s';  { gl.h:1080 }
procedure glRasterPos4d(x: GLdouble; y: GLdouble; z: GLdouble; w: GLdouble); cdecl; external 'libGL' name 'glRasterPos4d';  { gl.h:1082 }
procedure glRasterPos4f(x: GLfloat; y: GLfloat; z: GLfloat; w: GLfloat); cdecl; external 'libGL' name 'glRasterPos4f';  { gl.h:1083 }
procedure glRasterPos4i(x: GLint; y: GLint; z: GLint; w: GLint); cdecl; external 'libGL' name 'glRasterPos4i';  { gl.h:1084 }
procedure glRasterPos4s(x: GLshort; y: GLshort; z: GLshort; w: GLshort); cdecl; external 'libGL' name 'glRasterPos4s';  { gl.h:1085 }
procedure glRasterPos2dv(v: Pcdouble); cdecl; external 'libGL' name 'glRasterPos2dv';  { gl.h:1087 }
procedure glRasterPos2fv(v: Pcfloat); cdecl; external 'libGL' name 'glRasterPos2fv';  { gl.h:1088 }
procedure glRasterPos2iv(v: Pcint); cdecl; external 'libGL' name 'glRasterPos2iv';  { gl.h:1089 }
procedure glRasterPos2sv(v: Pcshort); cdecl; external 'libGL' name 'glRasterPos2sv';  { gl.h:1090 }
procedure glRasterPos3dv(v: Pcdouble); cdecl; external 'libGL' name 'glRasterPos3dv';  { gl.h:1092 }
procedure glRasterPos3fv(v: Pcfloat); cdecl; external 'libGL' name 'glRasterPos3fv';  { gl.h:1093 }
procedure glRasterPos3iv(v: Pcint); cdecl; external 'libGL' name 'glRasterPos3iv';  { gl.h:1094 }
procedure glRasterPos3sv(v: Pcshort); cdecl; external 'libGL' name 'glRasterPos3sv';  { gl.h:1095 }
procedure glRasterPos4dv(v: Pcdouble); cdecl; external 'libGL' name 'glRasterPos4dv';  { gl.h:1097 }
procedure glRasterPos4fv(v: Pcfloat); cdecl; external 'libGL' name 'glRasterPos4fv';  { gl.h:1098 }
procedure glRasterPos4iv(v: Pcint); cdecl; external 'libGL' name 'glRasterPos4iv';  { gl.h:1099 }
procedure glRasterPos4sv(v: Pcshort); cdecl; external 'libGL' name 'glRasterPos4sv';  { gl.h:1100 }
procedure glRectd(x1: GLdouble; y1: GLdouble; x2: GLdouble; y2: GLdouble); cdecl; external 'libGL' name 'glRectd';  { gl.h:1103 }
procedure glRectf(x1: GLfloat; y1: GLfloat; x2: GLfloat; y2: GLfloat); cdecl; external 'libGL' name 'glRectf';  { gl.h:1104 }
procedure glRecti(x1: GLint; y1: GLint; x2: GLint; y2: GLint); cdecl; external 'libGL' name 'glRecti';  { gl.h:1105 }
procedure glRects(x1: GLshort; y1: GLshort; x2: GLshort; y2: GLshort); cdecl; external 'libGL' name 'glRects';  { gl.h:1106 }
procedure glRectdv(v1: Pcdouble; v2: Pcdouble); cdecl; external 'libGL' name 'glRectdv';  { gl.h:1109 }
procedure glRectfv(v1: Pcfloat; v2: Pcfloat); cdecl; external 'libGL' name 'glRectfv';  { gl.h:1110 }
procedure glRectiv(v1: Pcint; v2: Pcint); cdecl; external 'libGL' name 'glRectiv';  { gl.h:1111 }
procedure glRectsv(v1: Pcshort; v2: Pcshort); cdecl; external 'libGL' name 'glRectsv';  { gl.h:1112 }
procedure glVertexPointer(size: GLint; type_: GLenum; stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glVertexPointer';  { gl.h:1119 }
procedure glNormalPointer(type_: GLenum; stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glNormalPointer';  { gl.h:1122 }
procedure glColorPointer(size: GLint; type_: GLenum; stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glColorPointer';  { gl.h:1125 }
procedure glIndexPointer(type_: GLenum; stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glIndexPointer';  { gl.h:1128 }
procedure glTexCoordPointer(size: GLint; type_: GLenum; stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glTexCoordPointer';  { gl.h:1131 }
procedure glEdgeFlagPointer(stride: GLsizei; ptr: Pointer); cdecl; external 'libGL' name 'glEdgeFlagPointer';  { gl.h:1134 }
procedure glGetPointerv(pname: GLenum; params: PPGLvoid); cdecl; external 'libGL' name 'glGetPointerv';  { gl.h:1136 }
procedure glArrayElement(i: GLint); cdecl; external 'libGL' name 'glArrayElement';  { gl.h:1138 }
procedure glDrawArrays(mode: GLenum; first: GLint; count: GLsizei); cdecl; external 'libGL' name 'glDrawArrays';  { gl.h:1140 }
procedure glDrawElements(mode: GLenum; count: GLsizei; type_: GLenum; indices: Pointer); cdecl; external 'libGL' name 'glDrawElements';  { gl.h:1142 }
procedure glInterleavedArrays(format: GLenum; stride: GLsizei; pointer: Pointer); cdecl; external 'libGL' name 'glInterleavedArrays';  { gl.h:1145 }
procedure glShadeModel(mode: GLenum); cdecl; external 'libGL' name 'glShadeModel';  { gl.h:1152 }
procedure glLightf(light: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glLightf';  { gl.h:1154 }
procedure glLighti(light: GLenum; pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glLighti';  { gl.h:1155 }
procedure glLightfv(light: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glLightfv';  { gl.h:1156 }
procedure glLightiv(light: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glLightiv';  { gl.h:1158 }
procedure glGetLightfv(light: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetLightfv';  { gl.h:1161 }
procedure glGetLightiv(light: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetLightiv';  { gl.h:1163 }
procedure glLightModelf(pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glLightModelf';  { gl.h:1166 }
procedure glLightModeli(pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glLightModeli';  { gl.h:1167 }
procedure glLightModelfv(pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glLightModelfv';  { gl.h:1168 }
procedure glLightModeliv(pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glLightModeliv';  { gl.h:1169 }
procedure glMaterialf(face: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glMaterialf';  { gl.h:1171 }
procedure glMateriali(face: GLenum; pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glMateriali';  { gl.h:1172 }
procedure glMaterialfv(face: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glMaterialfv';  { gl.h:1173 }
procedure glMaterialiv(face: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glMaterialiv';  { gl.h:1174 }
procedure glGetMaterialfv(face: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetMaterialfv';  { gl.h:1176 }
procedure glGetMaterialiv(face: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetMaterialiv';  { gl.h:1177 }
procedure glColorMaterial(face: GLenum; mode: GLenum); cdecl; external 'libGL' name 'glColorMaterial';  { gl.h:1179 }
procedure glPixelZoom(xfactor: GLfloat; yfactor: GLfloat); cdecl; external 'libGL' name 'glPixelZoom';  { gl.h:1186 }
procedure glPixelStoref(pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glPixelStoref';  { gl.h:1188 }
procedure glPixelStorei(pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glPixelStorei';  { gl.h:1189 }
procedure glPixelTransferf(pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glPixelTransferf';  { gl.h:1191 }
procedure glPixelTransferi(pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glPixelTransferi';  { gl.h:1192 }
procedure glPixelMapfv(map: GLenum; mapsize: GLsizei; values: Pcfloat); cdecl; external 'libGL' name 'glPixelMapfv';  { gl.h:1194 }
procedure glPixelMapuiv(map: GLenum; mapsize: GLsizei; values: Pcuint); cdecl; external 'libGL' name 'glPixelMapuiv';  { gl.h:1196 }
procedure glPixelMapusv(map: GLenum; mapsize: GLsizei; values: Pcushort); cdecl; external 'libGL' name 'glPixelMapusv';  { gl.h:1198 }
procedure glGetPixelMapfv(map: GLenum; values: PGLfloat); cdecl; external 'libGL' name 'glGetPixelMapfv';  { gl.h:1201 }
procedure glGetPixelMapuiv(map: GLenum; values: PGLuint); cdecl; external 'libGL' name 'glGetPixelMapuiv';  { gl.h:1202 }
procedure glGetPixelMapusv(map: GLenum; values: PGLushort); cdecl; external 'libGL' name 'glGetPixelMapusv';  { gl.h:1203 }
procedure glBitmap(width: GLsizei; height: GLsizei; xorig: GLfloat; yorig: GLfloat; xmove: GLfloat; ymove: GLfloat; bitmap: Pcuchar); cdecl; external 'libGL' name 'glBitmap';  { gl.h:1205 }
procedure glReadPixels(x: GLint; y: GLint; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; pixels: PGLvoid); cdecl; external 'libGL' name 'glReadPixels';  { gl.h:1210 }
procedure glDrawPixels(width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glDrawPixels';  { gl.h:1215 }
procedure glCopyPixels(x: GLint; y: GLint; width: GLsizei; height: GLsizei; type_: GLenum); cdecl; external 'libGL' name 'glCopyPixels';  { gl.h:1219 }
procedure glStencilFunc(func: GLenum; ref: GLint; mask: GLuint); cdecl; external 'libGL' name 'glStencilFunc';  { gl.h:1227 }
procedure glStencilMask(mask: GLuint); cdecl; external 'libGL' name 'glStencilMask';  { gl.h:1229 }
procedure glStencilOp(fail: GLenum; zfail: GLenum; zpass: GLenum); cdecl; external 'libGL' name 'glStencilOp';  { gl.h:1231 }
procedure glClearStencil(s: GLint); cdecl; external 'libGL' name 'glClearStencil';  { gl.h:1233 }
procedure glTexGend(coord: GLenum; pname: GLenum; param: GLdouble); cdecl; external 'libGL' name 'glTexGend';  { gl.h:1241 }
procedure glTexGenf(coord: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glTexGenf';  { gl.h:1242 }
procedure glTexGeni(coord: GLenum; pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glTexGeni';  { gl.h:1243 }
procedure glTexGendv(coord: GLenum; pname: GLenum; params: Pcdouble); cdecl; external 'libGL' name 'glTexGendv';  { gl.h:1245 }
procedure glTexGenfv(coord: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glTexGenfv';  { gl.h:1246 }
procedure glTexGeniv(coord: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glTexGeniv';  { gl.h:1247 }
procedure glGetTexGendv(coord: GLenum; pname: GLenum; params: PGLdouble); cdecl; external 'libGL' name 'glGetTexGendv';  { gl.h:1249 }
procedure glGetTexGenfv(coord: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetTexGenfv';  { gl.h:1250 }
procedure glGetTexGeniv(coord: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetTexGeniv';  { gl.h:1251 }
procedure glTexEnvf(target: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glTexEnvf';  { gl.h:1254 }
procedure glTexEnvi(target: GLenum; pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glTexEnvi';  { gl.h:1255 }
procedure glTexEnvfv(target: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glTexEnvfv';  { gl.h:1257 }
procedure glTexEnviv(target: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glTexEnviv';  { gl.h:1258 }
procedure glGetTexEnvfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetTexEnvfv';  { gl.h:1260 }
procedure glGetTexEnviv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetTexEnviv';  { gl.h:1261 }
procedure glTexParameterf(target: GLenum; pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glTexParameterf';  { gl.h:1264 }
procedure glTexParameteri(target: GLenum; pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glTexParameteri';  { gl.h:1265 }
procedure glTexParameterfv(target: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glTexParameterfv';  { gl.h:1267 }
procedure glTexParameteriv(target: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glTexParameteriv';  { gl.h:1269 }
procedure glGetTexParameterfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetTexParameterfv';  { gl.h:1272 }
procedure glGetTexParameteriv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetTexParameteriv';  { gl.h:1274 }
procedure glGetTexLevelParameterfv(target: GLenum; level: GLint; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetTexLevelParameterfv';  { gl.h:1277 }
procedure glGetTexLevelParameteriv(target: GLenum; level: GLint; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetTexLevelParameteriv';  { gl.h:1279 }
procedure glTexImage1D(target: GLenum; level: GLint; internalFormat: GLint; width: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexImage1D';  { gl.h:1283 }
procedure glTexImage2D(target: GLenum; level: GLint; internalFormat: GLint; width: GLsizei; height: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexImage2D';  { gl.h:1289 }
procedure glGetTexImage(target: GLenum; level: GLint; format: GLenum; type_: GLenum; pixels: PGLvoid); cdecl; external 'libGL' name 'glGetTexImage';  { gl.h:1295 }
procedure glGenTextures(n: GLsizei; textures: PGLuint); cdecl; external 'libGL' name 'glGenTextures';  { gl.h:1302 }
procedure glDeleteTextures(n: GLsizei; textures: Pcuint); cdecl; external 'libGL' name 'glDeleteTextures';  { gl.h:1304 }
procedure glBindTexture(target: GLenum; texture: GLuint); cdecl; external 'libGL' name 'glBindTexture';  { gl.h:1306 }
procedure glPrioritizeTextures(n: GLsizei; textures: Pcuint; priorities: Pcfloat); cdecl; external 'libGL' name 'glPrioritizeTextures';  { gl.h:1308 }
function glAreTexturesResident(n: GLsizei; textures: Pcuint; residences: PGLboolean): GLboolean; cdecl; external 'libGL' name 'glAreTexturesResident';  { gl.h:1312 }
function glIsTexture(texture: GLuint): GLboolean; cdecl; external 'libGL' name 'glIsTexture';  { gl.h:1316 }
procedure glTexSubImage1D(target: GLenum; level: GLint; xoffset: GLint; width: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexSubImage1D';  { gl.h:1319 }
procedure glTexSubImage2D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexSubImage2D';  { gl.h:1325 }
procedure glCopyTexImage1D(target: GLenum; level: GLint; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei; border: GLint); cdecl; external 'libGL' name 'glCopyTexImage1D';  { gl.h:1332 }
procedure glCopyTexImage2D(target: GLenum; level: GLint; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei; height: GLsizei; border: GLint); cdecl; external 'libGL' name 'glCopyTexImage2D';  { gl.h:1338 }
procedure glCopyTexSubImage1D(target: GLenum; level: GLint; xoffset: GLint; x: GLint; y: GLint; width: GLsizei); cdecl; external 'libGL' name 'glCopyTexSubImage1D';  { gl.h:1345 }
procedure glCopyTexSubImage2D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'libGL' name 'glCopyTexSubImage2D';  { gl.h:1350 }
procedure glMap1d(target: GLenum; u1: GLdouble; u2: GLdouble; stride: GLint; order: GLint; points: Pcdouble); cdecl; external 'libGL' name 'glMap1d';  { gl.h:1360 }
procedure glMap1f(target: GLenum; u1: GLfloat; u2: GLfloat; stride: GLint; order: GLint; points: Pcfloat); cdecl; external 'libGL' name 'glMap1f';  { gl.h:1363 }
procedure glMap2d(target: GLenum; u1: GLdouble; u2: GLdouble; ustride: GLint; uorder: GLint; v1: GLdouble; v2: GLdouble; vstride: GLint; vorder: GLint; points: Pcdouble); cdecl; external 'libGL' name 'glMap2d';  { gl.h:1367 }
procedure glMap2f(target: GLenum; u1: GLfloat; u2: GLfloat; ustride: GLint; uorder: GLint; v1: GLfloat; v2: GLfloat; vstride: GLint; vorder: GLint; points: Pcfloat); cdecl; external 'libGL' name 'glMap2f';  { gl.h:1371 }
procedure glGetMapdv(target: GLenum; query: GLenum; v: PGLdouble); cdecl; external 'libGL' name 'glGetMapdv';  { gl.h:1376 }
procedure glGetMapfv(target: GLenum; query: GLenum; v: PGLfloat); cdecl; external 'libGL' name 'glGetMapfv';  { gl.h:1377 }
procedure glGetMapiv(target: GLenum; query: GLenum; v: PGLint); cdecl; external 'libGL' name 'glGetMapiv';  { gl.h:1378 }
procedure glEvalCoord1d(u: GLdouble); cdecl; external 'libGL' name 'glEvalCoord1d';  { gl.h:1380 }
procedure glEvalCoord1f(u: GLfloat); cdecl; external 'libGL' name 'glEvalCoord1f';  { gl.h:1381 }
procedure glEvalCoord1dv(u: Pcdouble); cdecl; external 'libGL' name 'glEvalCoord1dv';  { gl.h:1383 }
procedure glEvalCoord1fv(u: Pcfloat); cdecl; external 'libGL' name 'glEvalCoord1fv';  { gl.h:1384 }
procedure glEvalCoord2d(u: GLdouble; v: GLdouble); cdecl; external 'libGL' name 'glEvalCoord2d';  { gl.h:1386 }
procedure glEvalCoord2f(u: GLfloat; v: GLfloat); cdecl; external 'libGL' name 'glEvalCoord2f';  { gl.h:1387 }
procedure glEvalCoord2dv(u: Pcdouble); cdecl; external 'libGL' name 'glEvalCoord2dv';  { gl.h:1389 }
procedure glEvalCoord2fv(u: Pcfloat); cdecl; external 'libGL' name 'glEvalCoord2fv';  { gl.h:1390 }
procedure glMapGrid1d(un: GLint; u1: GLdouble; u2: GLdouble); cdecl; external 'libGL' name 'glMapGrid1d';  { gl.h:1392 }
procedure glMapGrid1f(un: GLint; u1: GLfloat; u2: GLfloat); cdecl; external 'libGL' name 'glMapGrid1f';  { gl.h:1393 }
procedure glMapGrid2d(un: GLint; u1: GLdouble; u2: GLdouble; vn: GLint; v1: GLdouble; v2: GLdouble); cdecl; external 'libGL' name 'glMapGrid2d';  { gl.h:1395 }
procedure glMapGrid2f(un: GLint; u1: GLfloat; u2: GLfloat; vn: GLint; v1: GLfloat; v2: GLfloat); cdecl; external 'libGL' name 'glMapGrid2f';  { gl.h:1397 }
procedure glEvalPoint1(i: GLint); cdecl; external 'libGL' name 'glEvalPoint1';  { gl.h:1400 }
procedure glEvalPoint2(i: GLint; j: GLint); cdecl; external 'libGL' name 'glEvalPoint2';  { gl.h:1402 }
procedure glEvalMesh1(mode: GLenum; i1: GLint; i2: GLint); cdecl; external 'libGL' name 'glEvalMesh1';  { gl.h:1404 }
procedure glEvalMesh2(mode: GLenum; i1: GLint; i2: GLint; j1: GLint; j2: GLint); cdecl; external 'libGL' name 'glEvalMesh2';  { gl.h:1406 }
procedure glFogf(pname: GLenum; param: GLfloat); cdecl; external 'libGL' name 'glFogf';  { gl.h:1413 }
procedure glFogi(pname: GLenum; param: GLint); cdecl; external 'libGL' name 'glFogi';  { gl.h:1415 }
procedure glFogfv(pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glFogfv';  { gl.h:1417 }
procedure glFogiv(pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glFogiv';  { gl.h:1419 }
procedure glFeedbackBuffer(size: GLsizei; type_: GLenum; buffer: PGLfloat); cdecl; external 'libGL' name 'glFeedbackBuffer';  { gl.h:1426 }
procedure glPassThrough(token: GLfloat); cdecl; external 'libGL' name 'glPassThrough';  { gl.h:1428 }
procedure glSelectBuffer(size: GLsizei; buffer: PGLuint); cdecl; external 'libGL' name 'glSelectBuffer';  { gl.h:1430 }
procedure glInitNames; cdecl; external 'libGL' name 'glInitNames';  { gl.h:1432 }
procedure glLoadName(name: GLuint); cdecl; external 'libGL' name 'glLoadName';  { gl.h:1434 }
procedure glPushName(name: GLuint); cdecl; external 'libGL' name 'glPushName';  { gl.h:1436 }
procedure glPopName; cdecl; external 'libGL' name 'glPopName';  { gl.h:1438 }
procedure glDrawRangeElements(mode: GLenum; start: GLuint; end_: GLuint; count: GLsizei; type_: GLenum; indices: Pointer); cdecl; external 'libGL' name 'glDrawRangeElements';  { gl.h:1488 }
procedure glTexImage3D(target: GLenum; level: GLint; internalFormat: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; border: GLint; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexImage3D';  { gl.h:1491 }
procedure glTexSubImage3D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; format: GLenum; type_: GLenum; pixels: Pointer); cdecl; external 'libGL' name 'glTexSubImage3D';  { gl.h:1498 }
procedure glCopyTexSubImage3D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'libGL' name 'glCopyTexSubImage3D';  { gl.h:1505 }
procedure glColorTable(target: GLenum; internalformat: GLenum; width: GLsizei; format: GLenum; type_: GLenum; table: Pointer); cdecl; external 'libGL' name 'glColorTable';  { gl.h:1598 }
procedure glColorSubTable(target: GLenum; start: GLsizei; count: GLsizei; format: GLenum; type_: GLenum; data: Pointer); cdecl; external 'libGL' name 'glColorSubTable';  { gl.h:1602 }
procedure glColorTableParameteriv(target: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glColorTableParameteriv';  { gl.h:1607 }
procedure glColorTableParameterfv(target: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glColorTableParameterfv';  { gl.h:1610 }
procedure glCopyColorSubTable(target: GLenum; start: GLsizei; x: GLint; y: GLint; width: GLsizei); cdecl; external 'libGL' name 'glCopyColorSubTable';  { gl.h:1613 }
procedure glCopyColorTable(target: GLenum; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei); cdecl; external 'libGL' name 'glCopyColorTable';  { gl.h:1616 }
procedure glGetColorTable(target: GLenum; format: GLenum; type_: GLenum; table: PGLvoid); cdecl; external 'libGL' name 'glGetColorTable';  { gl.h:1619 }
procedure glGetColorTableParameterfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetColorTableParameterfv';  { gl.h:1622 }
procedure glGetColorTableParameteriv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetColorTableParameteriv';  { gl.h:1625 }
procedure glBlendEquation(mode: GLenum); cdecl; external 'libGL' name 'glBlendEquation';  { gl.h:1628 }
procedure glBlendColor(red: GLclampf; green: GLclampf; blue: GLclampf; alpha: GLclampf); cdecl; external 'libGL' name 'glBlendColor';  { gl.h:1630 }
procedure glHistogram(target: GLenum; width: GLsizei; internalformat: GLenum; sink: GLboolean); cdecl; external 'libGL' name 'glHistogram';  { gl.h:1633 }
procedure glResetHistogram(target: GLenum); cdecl; external 'libGL' name 'glResetHistogram';  { gl.h:1636 }
procedure glGetHistogram(target: GLenum; reset: GLboolean; format: GLenum; type_: GLenum; values: PGLvoid); cdecl; external 'libGL' name 'glGetHistogram';  { gl.h:1638 }
procedure glGetHistogramParameterfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetHistogramParameterfv';  { gl.h:1642 }
procedure glGetHistogramParameteriv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetHistogramParameteriv';  { gl.h:1645 }
procedure glMinmax(target: GLenum; internalformat: GLenum; sink: GLboolean); cdecl; external 'libGL' name 'glMinmax';  { gl.h:1648 }
procedure glResetMinmax(target: GLenum); cdecl; external 'libGL' name 'glResetMinmax';  { gl.h:1651 }
procedure glGetMinmax(target: GLenum; reset: GLboolean; format: GLenum; types: GLenum; values: PGLvoid); cdecl; external 'libGL' name 'glGetMinmax';  { gl.h:1653 }
procedure glGetMinmaxParameterfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetMinmaxParameterfv';  { gl.h:1657 }
procedure glGetMinmaxParameteriv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetMinmaxParameteriv';  { gl.h:1660 }
procedure glConvolutionFilter1D(target: GLenum; internalformat: GLenum; width: GLsizei; format: GLenum; type_: GLenum; image: Pointer); cdecl; external 'libGL' name 'glConvolutionFilter1D';  { gl.h:1663 }
procedure glConvolutionFilter2D(target: GLenum; internalformat: GLenum; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; image: Pointer); cdecl; external 'libGL' name 'glConvolutionFilter2D';  { gl.h:1667 }
procedure glConvolutionParameterf(target: GLenum; pname: GLenum; params: GLfloat); cdecl; external 'libGL' name 'glConvolutionParameterf';  { gl.h:1671 }
procedure glConvolutionParameterfv(target: GLenum; pname: GLenum; params: Pcfloat); cdecl; external 'libGL' name 'glConvolutionParameterfv';  { gl.h:1674 }
procedure glConvolutionParameteri(target: GLenum; pname: GLenum; params: GLint); cdecl; external 'libGL' name 'glConvolutionParameteri';  { gl.h:1677 }
procedure glConvolutionParameteriv(target: GLenum; pname: GLenum; params: Pcint); cdecl; external 'libGL' name 'glConvolutionParameteriv';  { gl.h:1680 }
procedure glCopyConvolutionFilter1D(target: GLenum; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei); cdecl; external 'libGL' name 'glCopyConvolutionFilter1D';  { gl.h:1683 }
procedure glCopyConvolutionFilter2D(target: GLenum; internalformat: GLenum; x: GLint; y: GLint; width: GLsizei; height: GLsizei); cdecl; external 'libGL' name 'glCopyConvolutionFilter2D';  { gl.h:1686 }
procedure glGetConvolutionFilter(target: GLenum; format: GLenum; type_: GLenum; image: PGLvoid); cdecl; external 'libGL' name 'glGetConvolutionFilter';  { gl.h:1690 }
procedure glGetConvolutionParameterfv(target: GLenum; pname: GLenum; params: PGLfloat); cdecl; external 'libGL' name 'glGetConvolutionParameterfv';  { gl.h:1693 }
procedure glGetConvolutionParameteriv(target: GLenum; pname: GLenum; params: PGLint); cdecl; external 'libGL' name 'glGetConvolutionParameteriv';  { gl.h:1696 }
procedure glSeparableFilter2D(target: GLenum; internalformat: GLenum; width: GLsizei; height: GLsizei; format: GLenum; type_: GLenum; row: Pointer; column: Pointer); cdecl; external 'libGL' name 'glSeparableFilter2D';  { gl.h:1699 }
procedure glGetSeparableFilter(target: GLenum; format: GLenum; type_: GLenum; row: PGLvoid; column: PGLvoid; span: PGLvoid); cdecl; external 'libGL' name 'glGetSeparableFilter';  { gl.h:1703 }
procedure glActiveTexture(texture: GLenum); cdecl; external 'libGL' name 'glActiveTexture';  { gl.h:1818 }
procedure glClientActiveTexture(texture: GLenum); cdecl; external 'libGL' name 'glClientActiveTexture';  { gl.h:1820 }
procedure glCompressedTexImage1D(target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexImage1D';  { gl.h:1822 }
procedure glCompressedTexImage2D(target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; height: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexImage2D';  { gl.h:1824 }
procedure glCompressedTexImage3D(target: GLenum; level: GLint; internalformat: GLenum; width: GLsizei; height: GLsizei; depth: GLsizei; border: GLint; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexImage3D';  { gl.h:1826 }
procedure glCompressedTexSubImage1D(target: GLenum; level: GLint; xoffset: GLint; width: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexSubImage1D';  { gl.h:1828 }
procedure glCompressedTexSubImage2D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; width: GLsizei; height: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexSubImage2D';  { gl.h:1830 }
procedure glCompressedTexSubImage3D(target: GLenum; level: GLint; xoffset: GLint; yoffset: GLint; zoffset: GLint; width: GLsizei; height: GLsizei; depth: GLsizei; format: GLenum; imageSize: GLsizei; data: Pointer); cdecl; external 'libGL' name 'glCompressedTexSubImage3D';  { gl.h:1832 }
procedure glGetCompressedTexImage(target: GLenum; lod: GLint; img: PGLvoid); cdecl; external 'libGL' name 'glGetCompressedTexImage';  { gl.h:1834 }
procedure glMultiTexCoord1d(target: GLenum; s: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord1d';  { gl.h:1836 }
procedure glMultiTexCoord1dv(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord1dv';  { gl.h:1838 }
procedure glMultiTexCoord1f(target: GLenum; s: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord1f';  { gl.h:1840 }
procedure glMultiTexCoord1fv(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord1fv';  { gl.h:1842 }
procedure glMultiTexCoord1i(target: GLenum; s: GLint); cdecl; external 'libGL' name 'glMultiTexCoord1i';  { gl.h:1844 }
procedure glMultiTexCoord1iv(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord1iv';  { gl.h:1846 }
procedure glMultiTexCoord1s(target: GLenum; s: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord1s';  { gl.h:1848 }
procedure glMultiTexCoord1sv(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord1sv';  { gl.h:1850 }
procedure glMultiTexCoord2d(target: GLenum; s: GLdouble; t: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord2d';  { gl.h:1852 }
procedure glMultiTexCoord2dv(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord2dv';  { gl.h:1854 }
procedure glMultiTexCoord2f(target: GLenum; s: GLfloat; t: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord2f';  { gl.h:1856 }
procedure glMultiTexCoord2fv(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord2fv';  { gl.h:1858 }
procedure glMultiTexCoord2i(target: GLenum; s: GLint; t: GLint); cdecl; external 'libGL' name 'glMultiTexCoord2i';  { gl.h:1860 }
procedure glMultiTexCoord2iv(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord2iv';  { gl.h:1862 }
procedure glMultiTexCoord2s(target: GLenum; s: GLshort; t: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord2s';  { gl.h:1864 }
procedure glMultiTexCoord2sv(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord2sv';  { gl.h:1866 }
procedure glMultiTexCoord3d(target: GLenum; s: GLdouble; t: GLdouble; r: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord3d';  { gl.h:1868 }
procedure glMultiTexCoord3dv(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord3dv';  { gl.h:1870 }
procedure glMultiTexCoord3f(target: GLenum; s: GLfloat; t: GLfloat; r: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord3f';  { gl.h:1872 }
procedure glMultiTexCoord3fv(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord3fv';  { gl.h:1874 }
procedure glMultiTexCoord3i(target: GLenum; s: GLint; t: GLint; r: GLint); cdecl; external 'libGL' name 'glMultiTexCoord3i';  { gl.h:1876 }
procedure glMultiTexCoord3iv(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord3iv';  { gl.h:1878 }
procedure glMultiTexCoord3s(target: GLenum; s: GLshort; t: GLshort; r: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord3s';  { gl.h:1880 }
procedure glMultiTexCoord3sv(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord3sv';  { gl.h:1882 }
procedure glMultiTexCoord4d(target: GLenum; s: GLdouble; t: GLdouble; r: GLdouble; q: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord4d';  { gl.h:1884 }
procedure glMultiTexCoord4dv(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord4dv';  { gl.h:1886 }
procedure glMultiTexCoord4f(target: GLenum; s: GLfloat; t: GLfloat; r: GLfloat; q: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord4f';  { gl.h:1888 }
procedure glMultiTexCoord4fv(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord4fv';  { gl.h:1890 }
procedure glMultiTexCoord4i(target: GLenum; s: GLint; t: GLint; r: GLint; q: GLint); cdecl; external 'libGL' name 'glMultiTexCoord4i';  { gl.h:1892 }
procedure glMultiTexCoord4iv(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord4iv';  { gl.h:1894 }
procedure glMultiTexCoord4s(target: GLenum; s: GLshort; t: GLshort; r: GLshort; q: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord4s';  { gl.h:1896 }
procedure glMultiTexCoord4sv(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord4sv';  { gl.h:1898 }
procedure glLoadTransposeMatrixd(m: Pcdouble); cdecl; external 'libGL' name 'glLoadTransposeMatrixd';  { gl.h:1901 }
procedure glLoadTransposeMatrixf(m: Pcfloat); cdecl; external 'libGL' name 'glLoadTransposeMatrixf';  { gl.h:1903 }
procedure glMultTransposeMatrixd(m: Pcdouble); cdecl; external 'libGL' name 'glMultTransposeMatrixd';  { gl.h:1905 }
procedure glMultTransposeMatrixf(m: Pcfloat); cdecl; external 'libGL' name 'glMultTransposeMatrixf';  { gl.h:1907 }
procedure glSampleCoverage(value: GLclampf; invert: GLboolean); cdecl; external 'libGL' name 'glSampleCoverage';  { gl.h:1909 }
procedure glActiveTextureARB(texture: GLenum); cdecl; external 'libGL' name 'glActiveTextureARB';  { gl.h:1966 }
procedure glClientActiveTextureARB(texture: GLenum); cdecl; external 'libGL' name 'glClientActiveTextureARB';  { gl.h:1967 }
procedure glMultiTexCoord1dARB(target: GLenum; s: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord1dARB';  { gl.h:1968 }
procedure glMultiTexCoord1dvARB(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord1dvARB';  { gl.h:1969 }
procedure glMultiTexCoord1fARB(target: GLenum; s: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord1fARB';  { gl.h:1970 }
procedure glMultiTexCoord1fvARB(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord1fvARB';  { gl.h:1971 }
procedure glMultiTexCoord1iARB(target: GLenum; s: GLint); cdecl; external 'libGL' name 'glMultiTexCoord1iARB';  { gl.h:1972 }
procedure glMultiTexCoord1ivARB(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord1ivARB';  { gl.h:1973 }
procedure glMultiTexCoord1sARB(target: GLenum; s: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord1sARB';  { gl.h:1974 }
procedure glMultiTexCoord1svARB(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord1svARB';  { gl.h:1975 }
procedure glMultiTexCoord2dARB(target: GLenum; s: GLdouble; t: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord2dARB';  { gl.h:1976 }
procedure glMultiTexCoord2dvARB(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord2dvARB';  { gl.h:1977 }
procedure glMultiTexCoord2fARB(target: GLenum; s: GLfloat; t: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord2fARB';  { gl.h:1978 }
procedure glMultiTexCoord2fvARB(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord2fvARB';  { gl.h:1979 }
procedure glMultiTexCoord2iARB(target: GLenum; s: GLint; t: GLint); cdecl; external 'libGL' name 'glMultiTexCoord2iARB';  { gl.h:1980 }
procedure glMultiTexCoord2ivARB(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord2ivARB';  { gl.h:1981 }
procedure glMultiTexCoord2sARB(target: GLenum; s: GLshort; t: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord2sARB';  { gl.h:1982 }
procedure glMultiTexCoord2svARB(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord2svARB';  { gl.h:1983 }
procedure glMultiTexCoord3dARB(target: GLenum; s: GLdouble; t: GLdouble; r: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord3dARB';  { gl.h:1984 }
procedure glMultiTexCoord3dvARB(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord3dvARB';  { gl.h:1985 }
procedure glMultiTexCoord3fARB(target: GLenum; s: GLfloat; t: GLfloat; r: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord3fARB';  { gl.h:1986 }
procedure glMultiTexCoord3fvARB(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord3fvARB';  { gl.h:1987 }
procedure glMultiTexCoord3iARB(target: GLenum; s: GLint; t: GLint; r: GLint); cdecl; external 'libGL' name 'glMultiTexCoord3iARB';  { gl.h:1988 }
procedure glMultiTexCoord3ivARB(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord3ivARB';  { gl.h:1989 }
procedure glMultiTexCoord3sARB(target: GLenum; s: GLshort; t: GLshort; r: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord3sARB';  { gl.h:1990 }
procedure glMultiTexCoord3svARB(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord3svARB';  { gl.h:1991 }
procedure glMultiTexCoord4dARB(target: GLenum; s: GLdouble; t: GLdouble; r: GLdouble; q: GLdouble); cdecl; external 'libGL' name 'glMultiTexCoord4dARB';  { gl.h:1992 }
procedure glMultiTexCoord4dvARB(target: GLenum; v: Pcdouble); cdecl; external 'libGL' name 'glMultiTexCoord4dvARB';  { gl.h:1993 }
procedure glMultiTexCoord4fARB(target: GLenum; s: GLfloat; t: GLfloat; r: GLfloat; q: GLfloat); cdecl; external 'libGL' name 'glMultiTexCoord4fARB';  { gl.h:1994 }
procedure glMultiTexCoord4fvARB(target: GLenum; v: Pcfloat); cdecl; external 'libGL' name 'glMultiTexCoord4fvARB';  { gl.h:1995 }
procedure glMultiTexCoord4iARB(target: GLenum; s: GLint; t: GLint; r: GLint; q: GLint); cdecl; external 'libGL' name 'glMultiTexCoord4iARB';  { gl.h:1996 }
procedure glMultiTexCoord4ivARB(target: GLenum; v: Pcint); cdecl; external 'libGL' name 'glMultiTexCoord4ivARB';  { gl.h:1997 }
procedure glMultiTexCoord4sARB(target: GLenum; s: GLshort; t: GLshort; r: GLshort; q: GLshort); cdecl; external 'libGL' name 'glMultiTexCoord4sARB';  { gl.h:1998 }
procedure glMultiTexCoord4svARB(target: GLenum; v: Pcshort); cdecl; external 'libGL' name 'glMultiTexCoord4svARB';  { gl.h:1999 }
procedure glBlendEquationSeparateATI(modeRGB: GLenum; modeA: GLenum); cdecl; external 'libGL' name 'glBlendEquationSeparateATI';  { gl.h:2077 }

implementation

end.
