// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit alpha_modifier_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpAlphaModifierSurfaceV1Class = class of TWpAlphaModifierSurfaceV1;
  { TWpAlphaModifierSurfaceV1 }
  TWpAlphaModifierSurfaceV1 = class;

  TWpAlphaModifierV1Class = class of TWpAlphaModifierV1;
  { TWpAlphaModifierV1 }
  TWpAlphaModifierV1 = class;

  IWpAlphaModifierV1Requests = interface;

  [TWLIntfAttribute('destroy(),get_surface(no)', '')]
  { TWpAlphaModifierV1 }
  TWpAlphaModifierV1 = class(TWaylandServerResource)
  public type
    TError = (erAlreadyconstructed = 0);
    TDestroyEvent = procedure(Sender: TWpAlphaModifierV1) of object;
    TGetSurfaceEvent = procedure(Sender: TWpAlphaModifierV1; aId: TWpAlphaModifierSurfaceV1; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_SURFACE = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetSurfacePriv: TGetSurfaceEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetSurface(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_SURFACE); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetSurface: TGetSurfaceEvent read FOnGetSurfacePriv write FOnGetSurfacePriv;
  private
    FListeners: array of IWpAlphaModifierV1Requests;
  public
    function AddListener(AIntf: IWpAlphaModifierV1Requests): LongInt;
  end;

  IWpAlphaModifierV1Requests = interface
  ['IWpAlphaModifierV1Requests']
    procedure wp_alpha_modifier_v1_destroy(AWpAlphaModifierV1: TWpAlphaModifierV1);
    procedure wp_alpha_modifier_v1_get_surface(AWpAlphaModifierV1: TWpAlphaModifierV1; aId: TWpAlphaModifierSurfaceV1; aSurface: TWlSurface);
  end;

  IWpAlphaModifierSurfaceV1Requests = interface;

  [TWLIntfAttribute('destroy(),set_multiplier(u)', '')]
  { TWpAlphaModifierSurfaceV1 }
  TWpAlphaModifierSurfaceV1 = class(TWaylandServerResource)
  public type
    TError = (erNosurface = 0);
    TDestroyEvent = procedure(Sender: TWpAlphaModifierSurfaceV1) of object;
    TSetMultiplierEvent = procedure(Sender: TWpAlphaModifierSurfaceV1; aFactor: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_MULTIPLIER = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetMultiplierPriv: TSetMultiplierEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetMultiplier(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MULTIPLIER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetMultiplier: TSetMultiplierEvent read FOnSetMultiplierPriv write FOnSetMultiplierPriv;
  private
    FListeners: array of IWpAlphaModifierSurfaceV1Requests;
  public
    function AddListener(AIntf: IWpAlphaModifierSurfaceV1Requests): LongInt;
  end;

  IWpAlphaModifierSurfaceV1Requests = interface
  ['IWpAlphaModifierSurfaceV1Requests']
    procedure wp_alpha_modifier_surface_v1_destroy(AWpAlphaModifierSurfaceV1: TWpAlphaModifierSurfaceV1);
    procedure wp_alpha_modifier_surface_v1_set_multiplier(AWpAlphaModifierSurfaceV1: TWpAlphaModifierSurfaceV1; aFactor: DWord);
  end;

implementation
uses
  wayland_stream;

class function TWpAlphaModifierV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpAlphaModifierV1.GetInterfaceName: String;
begin
  Result := 'wp_alpha_modifier_v1';
end;

procedure TWpAlphaModifierV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_alpha_modifier_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpAlphaModifierV1.HandleGetSurface(var AMsg: TWaylandEventMessage);
var
  lId: TWpAlphaModifierSurfaceV1;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TWpAlphaModifierSurfaceV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetSurface) then OnGetSurface(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_alpha_modifier_v1_get_surface(Self,lId,lSurface);
  AMsg.SetHandled;
end;

function TWpAlphaModifierV1.AddListener(AIntf: IWpAlphaModifierV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpAlphaModifierSurfaceV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpAlphaModifierSurfaceV1.GetInterfaceName: String;
begin
  Result := 'wp_alpha_modifier_surface_v1';
end;

procedure TWpAlphaModifierSurfaceV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_alpha_modifier_surface_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpAlphaModifierSurfaceV1.HandleSetMultiplier(var AMsg: TWaylandEventMessage);
var
  lFactor: DWord;
  lListenerIdx: Integer;
begin
  lFactor := AMsg.Args.ReadDWord;
  if Assigned(OnSetMultiplier) then OnSetMultiplier(Self,lFactor);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_alpha_modifier_surface_v1_set_multiplier(Self,lFactor);
  AMsg.SetHandled;
end;

function TWpAlphaModifierSurfaceV1.AddListener(AIntf: IWpAlphaModifierSurfaceV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.