// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit commit_timing_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpCommitTimerV1Class = class of TWpCommitTimerV1;
  { TWpCommitTimerV1 }
  TWpCommitTimerV1 = class;

  TWpCommitTimingManagerV1Class = class of TWpCommitTimingManagerV1;
  { TWpCommitTimingManagerV1 }
  TWpCommitTimingManagerV1 = class;

  IWpCommitTimingManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),get_timer(no)', '')]
  { TWpCommitTimingManagerV1 }
  TWpCommitTimingManagerV1 = class(TWaylandServerResource)
  public type
    TError = (erCommittimerexists = 0);
    TDestroyEvent = procedure(Sender: TWpCommitTimingManagerV1) of object;
    TGetTimerEvent = procedure(Sender: TWpCommitTimingManagerV1; aId: TWpCommitTimerV1; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_TIMER = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetTimerPriv: TGetTimerEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetTimer(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_TIMER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetTimer: TGetTimerEvent read FOnGetTimerPriv write FOnGetTimerPriv;
  private
    FListeners: array of IWpCommitTimingManagerV1Requests;
  public
    function AddListener(AIntf: IWpCommitTimingManagerV1Requests): LongInt;
  end;

  IWpCommitTimingManagerV1Requests = interface
  ['IWpCommitTimingManagerV1Requests']
    procedure wp_commit_timing_manager_v1_destroy(AWpCommitTimingManagerV1: TWpCommitTimingManagerV1);
    procedure wp_commit_timing_manager_v1_get_timer(AWpCommitTimingManagerV1: TWpCommitTimingManagerV1; aId: TWpCommitTimerV1; aSurface: TWlSurface);
  end;

  IWpCommitTimerV1Requests = interface;

  [TWLIntfAttribute('set_timestamp(uuu),destroy()', '')]
  { TWpCommitTimerV1 }
  TWpCommitTimerV1 = class(TWaylandServerResource)
  public type
    TError = (erInvalidtimestamp = 0, erTimestampexists = 1, erSurfacedestroyed = 2);
    TSetTimestampEvent = procedure(Sender: TWpCommitTimerV1; aTvSecHi: DWord; aTvSecLo: DWord; aTvNsec: DWord) of object;
    TDestroyEvent = procedure(Sender: TWpCommitTimerV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_SET_TIMESTAMP = 0, _DESTROY = 1);
  private
    FOnSetTimestampPriv: TSetTimestampEvent;
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleSetTimestamp(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_TIMESTAMP); virtual;
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnSetTimestamp: TSetTimestampEvent read FOnSetTimestampPriv write FOnSetTimestampPriv;
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  private
    FListeners: array of IWpCommitTimerV1Requests;
  public
    function AddListener(AIntf: IWpCommitTimerV1Requests): LongInt;
  end;

  IWpCommitTimerV1Requests = interface
  ['IWpCommitTimerV1Requests']
    procedure wp_commit_timer_v1_set_timestamp(AWpCommitTimerV1: TWpCommitTimerV1; aTvSecHi: DWord; aTvSecLo: DWord; aTvNsec: DWord);
    procedure wp_commit_timer_v1_destroy(AWpCommitTimerV1: TWpCommitTimerV1);
  end;

implementation
uses
  wayland_stream;

class function TWpCommitTimingManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpCommitTimingManagerV1.GetInterfaceName: String;
begin
  Result := 'wp_commit_timing_manager_v1';
end;

procedure TWpCommitTimingManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_commit_timing_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpCommitTimingManagerV1.HandleGetTimer(var AMsg: TWaylandEventMessage);
var
  lId: TWpCommitTimerV1;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TWpCommitTimerV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetTimer) then OnGetTimer(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_commit_timing_manager_v1_get_timer(Self,lId,lSurface);
  AMsg.SetHandled;
end;

function TWpCommitTimingManagerV1.AddListener(AIntf: IWpCommitTimingManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpCommitTimerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpCommitTimerV1.GetInterfaceName: String;
begin
  Result := 'wp_commit_timer_v1';
end;

procedure TWpCommitTimerV1.HandleSetTimestamp(var AMsg: TWaylandEventMessage);
var
  lTvSecHi: DWord;
  lTvSecLo: DWord;
  lTvNsec: DWord;
  lListenerIdx: Integer;
begin
  lTvSecHi := AMsg.Args.ReadDWord;
  lTvSecLo := AMsg.Args.ReadDWord;
  lTvNsec := AMsg.Args.ReadDWord;
  if Assigned(OnSetTimestamp) then OnSetTimestamp(Self,lTvSecHi,lTvSecLo,lTvNsec);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_commit_timer_v1_set_timestamp(Self,lTvSecHi,lTvSecLo,lTvNsec);
  AMsg.SetHandled;
end;

procedure TWpCommitTimerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_commit_timer_v1_destroy(Self);
  AMsg.SetHandled;
end;

function TWpCommitTimerV1.AddListener(AIntf: IWpCommitTimerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.