// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit ext_session_lock_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TExtSessionLockSurfaceV1Class = class of TExtSessionLockSurfaceV1;
  { TExtSessionLockSurfaceV1 }
  TExtSessionLockSurfaceV1 = class;

  TExtSessionLockV1Class = class of TExtSessionLockV1;
  { TExtSessionLockV1 }
  TExtSessionLockV1 = class;

  TExtSessionLockManagerV1Class = class of TExtSessionLockManagerV1;
  { TExtSessionLockManagerV1 }
  TExtSessionLockManagerV1 = class;

  IExtSessionLockManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),lock(n)', '')]
  { TExtSessionLockManagerV1 }
  TExtSessionLockManagerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TExtSessionLockManagerV1) of object;
    TLockEvent = procedure(Sender: TExtSessionLockManagerV1; aId: TExtSessionLockV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _LOCK = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnLockPriv: TLockEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleLock(var AMsg: TWaylandEventMessage); message Ord(TRequests._LOCK); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnLock: TLockEvent read FOnLockPriv write FOnLockPriv;
  private
    FListeners: array of IExtSessionLockManagerV1Requests;
  public
    function AddListener(AIntf: IExtSessionLockManagerV1Requests): LongInt;
  end;

  IExtSessionLockManagerV1Requests = interface
  ['IExtSessionLockManagerV1Requests']
    procedure ext_session_lock_manager_v1_destroy(AExtSessionLockManagerV1: TExtSessionLockManagerV1);
    procedure ext_session_lock_manager_v1_lock(AExtSessionLockManagerV1: TExtSessionLockManagerV1; aId: TExtSessionLockV1);
  end;

  IExtSessionLockV1Requests = interface;

  [TWLIntfAttribute('destroy(),get_lock_surface(noo),unlock_and_destroy()', 'locked(),finished()')]
  { TExtSessionLockV1 }
  TExtSessionLockV1 = class(TWaylandServerResource)
  public type
    TError = (erInvaliddestroy = 0, erInvalidunlock = 1, erRole = 2, erDuplicateoutput = 3, erAlreadyconstructed = 4);
    TDestroyEvent = procedure(Sender: TExtSessionLockV1) of object;
    TGetLockSurfaceEvent = procedure(Sender: TExtSessionLockV1; aId: TExtSessionLockSurfaceV1; aSurface: TWlSurface; aOutput: TWlOutput) of object;
    TUnlockAndDestroyEvent = procedure(Sender: TExtSessionLockV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_LOCK_SURFACE = 1, _UNLOCK_AND_DESTROY = 2);
    TEvents = (EV_LOCKED = 0, EV_FINISHED = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetLockSurfacePriv: TGetLockSurfaceEvent;
    FOnUnlockAndDestroyPriv: TUnlockAndDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetLockSurface(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_LOCK_SURFACE); virtual;
    procedure HandleUnlockAndDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._UNLOCK_AND_DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetLockSurface: TGetLockSurfaceEvent read FOnGetLockSurfacePriv write FOnGetLockSurfacePriv;
    property OnUnlockAndDestroy: TUnlockAndDestroyEvent read FOnUnlockAndDestroyPriv write FOnUnlockAndDestroyPriv;
  public
    procedure Locked;
    procedure Finished;
  private
    FListeners: array of IExtSessionLockV1Requests;
  public
    function AddListener(AIntf: IExtSessionLockV1Requests): LongInt;
  end;

  IExtSessionLockV1Requests = interface
  ['IExtSessionLockV1Requests']
    procedure ext_session_lock_v1_destroy(AExtSessionLockV1: TExtSessionLockV1);
    procedure ext_session_lock_v1_get_lock_surface(AExtSessionLockV1: TExtSessionLockV1; aId: TExtSessionLockSurfaceV1; aSurface: TWlSurface; aOutput: TWlOutput);
    procedure ext_session_lock_v1_unlock_and_destroy(AExtSessionLockV1: TExtSessionLockV1);
  end;

  IExtSessionLockSurfaceV1Requests = interface;

  [TWLIntfAttribute('destroy(),ack_configure(u)', 'configure(uuu)')]
  { TExtSessionLockSurfaceV1 }
  TExtSessionLockSurfaceV1 = class(TWaylandServerResource)
  public type
    TError = (erCommitbeforefirstack = 0, erNullbuffer = 1, erDimensionsmismatch = 2, erInvalidserial = 3);
    TDestroyEvent = procedure(Sender: TExtSessionLockSurfaceV1) of object;
    TAckConfigureEvent = procedure(Sender: TExtSessionLockSurfaceV1; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _ACK_CONFIGURE = 1);
    TEvents = (EV_CONFIGURE = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnAckConfigurePriv: TAckConfigureEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleAckConfigure(var AMsg: TWaylandEventMessage); message Ord(TRequests._ACK_CONFIGURE); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnAckConfigure: TAckConfigureEvent read FOnAckConfigurePriv write FOnAckConfigurePriv;
  public
    procedure Configure(aSerial: DWord; aWidth: DWord; aHeight: DWord);
  private
    FListeners: array of IExtSessionLockSurfaceV1Requests;
  public
    function AddListener(AIntf: IExtSessionLockSurfaceV1Requests): LongInt;
  end;

  IExtSessionLockSurfaceV1Requests = interface
  ['IExtSessionLockSurfaceV1Requests']
    procedure ext_session_lock_surface_v1_destroy(AExtSessionLockSurfaceV1: TExtSessionLockSurfaceV1);
    procedure ext_session_lock_surface_v1_ack_configure(AExtSessionLockSurfaceV1: TExtSessionLockSurfaceV1; aSerial: DWord);
  end;

implementation
uses
  wayland_stream;

class function TExtSessionLockManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TExtSessionLockManagerV1.GetInterfaceName: String;
begin
  Result := 'ext_session_lock_manager_v1';
end;

procedure TExtSessionLockManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtSessionLockManagerV1.HandleLock(var AMsg: TWaylandEventMessage);
var
  lId: TExtSessionLockV1;
  lListenerIdx: Integer;
begin
  lId := TExtSessionLockV1.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnLock) then OnLock(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_manager_v1_lock(Self,lId);
  AMsg.SetHandled;
end;

function TExtSessionLockManagerV1.AddListener(AIntf: IExtSessionLockManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TExtSessionLockV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TExtSessionLockV1.GetInterfaceName: String;
begin
  Result := 'ext_session_lock_v1';
end;

procedure TExtSessionLockV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtSessionLockV1.HandleGetLockSurface(var AMsg: TWaylandEventMessage);
var
  lId: TExtSessionLockSurfaceV1;
  lSurface: TWlSurface;
  lOutput: TWlOutput;
  lListenerIdx: Integer;
begin
  lId := TExtSessionLockSurfaceV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  if Assigned(OnGetLockSurface) then OnGetLockSurface(Self,lId,lSurface,lOutput);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_v1_get_lock_surface(Self,lId,lSurface,lOutput);
  AMsg.SetHandled;
end;

procedure TExtSessionLockV1.HandleUnlockAndDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnUnlockAndDestroy) then OnUnlockAndDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_v1_unlock_and_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtSessionLockV1.Locked;
begin
  SendEvent(Ord(TEvents.EV_LOCKED), []);
end;

procedure TExtSessionLockV1.Finished;
begin
  SendEvent(Ord(TEvents.EV_FINISHED), []);
end;

function TExtSessionLockV1.AddListener(AIntf: IExtSessionLockV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TExtSessionLockSurfaceV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TExtSessionLockSurfaceV1.GetInterfaceName: String;
begin
  Result := 'ext_session_lock_surface_v1';
end;

procedure TExtSessionLockSurfaceV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_surface_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtSessionLockSurfaceV1.HandleAckConfigure(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnAckConfigure) then OnAckConfigure(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_session_lock_surface_v1_ack_configure(Self,lSerial);
  AMsg.SetHandled;
end;

procedure TExtSessionLockSurfaceV1.Configure(aSerial: DWord; aWidth: DWord; aHeight: DWord);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aSerial,aWidth,aHeight]);
end;

function TExtSessionLockSurfaceV1.AddListener(AIntf: IExtSessionLockSurfaceV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.