// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit ext_idle_notify_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TExtIdleNotificationV1Class = class of TExtIdleNotificationV1;
  { TExtIdleNotificationV1 }
  TExtIdleNotificationV1 = class;

  TExtIdleNotifierV1Class = class of TExtIdleNotifierV1;
  { TExtIdleNotifierV1 }
  TExtIdleNotifierV1 = class;

  IExtIdleNotifierV1Requests = interface;

  [TWLIntfAttribute('destroy(),get_idle_notification(nuo),get_input_idle_notification(nuo)', '')]
  { TExtIdleNotifierV1 }
  TExtIdleNotifierV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TExtIdleNotifierV1) of object;
    TGetIdleNotificationEvent = procedure(Sender: TExtIdleNotifierV1; aId: TExtIdleNotificationV1; aTimeout: DWord; aSeat: TWlSeat) of object;
    TGetInputIdleNotificationEvent = procedure(Sender: TExtIdleNotifierV1; aId: TExtIdleNotificationV1; aTimeout: DWord; aSeat: TWlSeat) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_IDLE_NOTIFICATION = 1, _GET_INPUT_IDLE_NOTIFICATION = 2);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetIdleNotificationPriv: TGetIdleNotificationEvent;
    FOnGetInputIdleNotificationPriv: TGetInputIdleNotificationEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetIdleNotification(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_IDLE_NOTIFICATION); virtual;
    procedure HandleGetInputIdleNotification(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_INPUT_IDLE_NOTIFICATION); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetIdleNotification: TGetIdleNotificationEvent read FOnGetIdleNotificationPriv write FOnGetIdleNotificationPriv;
    property OnGetInputIdleNotification: TGetInputIdleNotificationEvent read FOnGetInputIdleNotificationPriv write FOnGetInputIdleNotificationPriv;
  private
    FListeners: array of IExtIdleNotifierV1Requests;
  public
    function AddListener(AIntf: IExtIdleNotifierV1Requests): LongInt;
  end;

  IExtIdleNotifierV1Requests = interface
  ['IExtIdleNotifierV1Requests']
    procedure ext_idle_notifier_v1_destroy(AExtIdleNotifierV1: TExtIdleNotifierV1);
    procedure ext_idle_notifier_v1_get_idle_notification(AExtIdleNotifierV1: TExtIdleNotifierV1; aId: TExtIdleNotificationV1; aTimeout: DWord; aSeat: TWlSeat);
    procedure ext_idle_notifier_v1_get_input_idle_notification(AExtIdleNotifierV1: TExtIdleNotifierV1; aId: TExtIdleNotificationV1; aTimeout: DWord; aSeat: TWlSeat);
  end;

  IExtIdleNotificationV1Requests = interface;

  [TWLIntfAttribute('destroy()', 'idled(),resumed()')]
  { TExtIdleNotificationV1 }
  TExtIdleNotificationV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TExtIdleNotificationV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0);
    TEvents = (EV_IDLED = 0, EV_RESUMED = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  public
    procedure Idled;
    procedure Resumed;
  private
    FListeners: array of IExtIdleNotificationV1Requests;
  public
    function AddListener(AIntf: IExtIdleNotificationV1Requests): LongInt;
  end;

  IExtIdleNotificationV1Requests = interface
  ['IExtIdleNotificationV1Requests']
    procedure ext_idle_notification_v1_destroy(AExtIdleNotificationV1: TExtIdleNotificationV1);
  end;

implementation
uses
  wayland_stream;

class function TExtIdleNotifierV1.GetInterfaceVersion: Integer;
begin
  Result := 2;
end;

class function TExtIdleNotifierV1.GetInterfaceName: String;
begin
  Result := 'ext_idle_notifier_v1';
end;

procedure TExtIdleNotifierV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_idle_notifier_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtIdleNotifierV1.HandleGetIdleNotification(var AMsg: TWaylandEventMessage);
var
  lId: TExtIdleNotificationV1;
  lTimeout: DWord;
  lSeat: TWlSeat;
  lListenerIdx: Integer;
begin
  lId := TExtIdleNotificationV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lTimeout := AMsg.Args.ReadDWord;
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  if Assigned(OnGetIdleNotification) then OnGetIdleNotification(Self,lId,lTimeout,lSeat);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_idle_notifier_v1_get_idle_notification(Self,lId,lTimeout,lSeat);
  AMsg.SetHandled;
end;

procedure TExtIdleNotifierV1.HandleGetInputIdleNotification(var AMsg: TWaylandEventMessage);
var
  lId: TExtIdleNotificationV1;
  lTimeout: DWord;
  lSeat: TWlSeat;
  lListenerIdx: Integer;
begin
  lId := TExtIdleNotificationV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lTimeout := AMsg.Args.ReadDWord;
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  if Assigned(OnGetInputIdleNotification) then OnGetInputIdleNotification(Self,lId,lTimeout,lSeat);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_idle_notifier_v1_get_input_idle_notification(Self,lId,lTimeout,lSeat);
  AMsg.SetHandled;
end;

function TExtIdleNotifierV1.AddListener(AIntf: IExtIdleNotifierV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TExtIdleNotificationV1.GetInterfaceVersion: Integer;
begin
  Result := 2;
end;

class function TExtIdleNotificationV1.GetInterfaceName: String;
begin
  Result := 'ext_idle_notification_v1';
end;

procedure TExtIdleNotificationV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].ext_idle_notification_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TExtIdleNotificationV1.Idled;
begin
  SendEvent(Ord(TEvents.EV_IDLED), []);
end;

procedure TExtIdleNotificationV1.Resumed;
begin
  SendEvent(Ord(TEvents.EV_RESUMED), []);
end;

function TExtIdleNotificationV1.AddListener(AIntf: IExtIdleNotificationV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('ext_idle_notifier_v1', TExtIdleNotifierV1);
  RegisterServerInterface('ext_idle_notification_v1', TExtIdleNotificationV1);

end.