// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit pointer_warp_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpPointerWarpV1Class = class of TWpPointerWarpV1;
  { TWpPointerWarpV1 }
  TWpPointerWarpV1 = class;

  IWpPointerWarpV1Requests = interface;

  [TWLIntfAttribute('destroy(),warp_pointer(ooffu)', '')]
  { TWpPointerWarpV1 }
  TWpPointerWarpV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpPointerWarpV1) of object;
    TWarpPointerEvent = procedure(Sender: TWpPointerWarpV1; aSurface: TWlSurface; aPointer: TWlPointer; aX: TWaylandFixed; aY: TWaylandFixed; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _WARP_POINTER = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnWarpPointerPriv: TWarpPointerEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleWarpPointer(var AMsg: TWaylandEventMessage); message Ord(TRequests._WARP_POINTER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnWarpPointer: TWarpPointerEvent read FOnWarpPointerPriv write FOnWarpPointerPriv;
  private
    FListeners: array of IWpPointerWarpV1Requests;
  public
    function AddListener(AIntf: IWpPointerWarpV1Requests): LongInt;
  end;

  IWpPointerWarpV1Requests = interface
  ['IWpPointerWarpV1Requests']
    procedure wp_pointer_warp_v1_destroy(AWpPointerWarpV1: TWpPointerWarpV1);
    procedure wp_pointer_warp_v1_warp_pointer(AWpPointerWarpV1: TWpPointerWarpV1; aSurface: TWlSurface; aPointer: TWlPointer; aX: TWaylandFixed; aY: TWaylandFixed; aSerial: DWord);
  end;

implementation
uses
  wayland_stream;

class function TWpPointerWarpV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpPointerWarpV1.GetInterfaceName: String;
begin
  Result := 'wp_pointer_warp_v1';
end;

procedure TWpPointerWarpV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_pointer_warp_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpPointerWarpV1.HandleWarpPointer(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lPointer: TWlPointer;
  lX: TWaylandFixed;
  lY: TWaylandFixed;
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lPointer := (Client.GetObject(AMsg.Args.ReadDWord) as TWlPointer);
  lX := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lY := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnWarpPointer) then OnWarpPointer(Self,lSurface,lPointer,lX,lY,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_pointer_warp_v1_warp_pointer(Self,lSurface,lPointer,lX,lY,lSerial);
  AMsg.SetHandled;
end;

function TWpPointerWarpV1.AddListener(AIntf: IWpPointerWarpV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('wp_pointer_warp_v1', TWpPointerWarpV1);

end.