// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit security_context_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpSecurityContextV1Class = class of TWpSecurityContextV1;
  { TWpSecurityContextV1 }
  TWpSecurityContextV1 = class;

  TWpSecurityContextManagerV1Class = class of TWpSecurityContextManagerV1;
  { TWpSecurityContextManagerV1 }
  TWpSecurityContextManagerV1 = class;

  IWpSecurityContextManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),create_listener(nhh)', '')]
  { TWpSecurityContextManagerV1 }
  TWpSecurityContextManagerV1 = class(TWaylandServerResource)
  public type
    TError = (erInvalidlistenfd = 1, erNested = 2);
    TDestroyEvent = procedure(Sender: TWpSecurityContextManagerV1) of object;
    TCreateListenerEvent = procedure(Sender: TWpSecurityContextManagerV1; aId: TWpSecurityContextV1; aListenFd: TWaylandFdStream; aCloseFd: TWaylandFdStream) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_LISTENER = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreateListenerPriv: TCreateListenerEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreateListener(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_LISTENER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreateListener: TCreateListenerEvent read FOnCreateListenerPriv write FOnCreateListenerPriv;
  private
    FListeners: array of IWpSecurityContextManagerV1Requests;
  public
    function AddListener(AIntf: IWpSecurityContextManagerV1Requests): LongInt;
  end;

  IWpSecurityContextManagerV1Requests = interface
  ['IWpSecurityContextManagerV1Requests']
    procedure wp_security_context_manager_v1_destroy(AWpSecurityContextManagerV1: TWpSecurityContextManagerV1);
    procedure wp_security_context_manager_v1_create_listener(AWpSecurityContextManagerV1: TWpSecurityContextManagerV1; aId: TWpSecurityContextV1; aListenFd: TWaylandFdStream; aCloseFd: TWaylandFdStream);
  end;

  IWpSecurityContextV1Requests = interface;

  [TWLIntfAttribute('destroy(),set_sandbox_engine(s),set_app_id(s),set_instance_id(s),commit()', '')]
  { TWpSecurityContextV1 }
  TWpSecurityContextV1 = class(TWaylandServerResource)
  public type
    TError = (erAlreadyused = 1, erAlreadyset = 2, erInvalidmetadata = 3);
    TDestroyEvent = procedure(Sender: TWpSecurityContextV1) of object;
    TSetSandboxEngineEvent = procedure(Sender: TWpSecurityContextV1; aName: String) of object;
    TSetAppIdEvent = procedure(Sender: TWpSecurityContextV1; aAppId: String) of object;
    TSetInstanceIdEvent = procedure(Sender: TWpSecurityContextV1; aInstanceId: String) of object;
    TCommitEvent = procedure(Sender: TWpSecurityContextV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_SANDBOX_ENGINE = 1, _SET_APP_ID = 2, _SET_INSTANCE_ID = 3, _COMMIT = 4);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetSandboxEnginePriv: TSetSandboxEngineEvent;
    FOnSetAppIdPriv: TSetAppIdEvent;
    FOnSetInstanceIdPriv: TSetInstanceIdEvent;
    FOnCommitPriv: TCommitEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetSandboxEngine(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_SANDBOX_ENGINE); virtual;
    procedure HandleSetAppId(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_APP_ID); virtual;
    procedure HandleSetInstanceId(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_INSTANCE_ID); virtual;
    procedure HandleCommit(var AMsg: TWaylandEventMessage); message Ord(TRequests._COMMIT); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetSandboxEngine: TSetSandboxEngineEvent read FOnSetSandboxEnginePriv write FOnSetSandboxEnginePriv;
    property OnSetAppId: TSetAppIdEvent read FOnSetAppIdPriv write FOnSetAppIdPriv;
    property OnSetInstanceId: TSetInstanceIdEvent read FOnSetInstanceIdPriv write FOnSetInstanceIdPriv;
    property OnCommit: TCommitEvent read FOnCommitPriv write FOnCommitPriv;
  private
    FListeners: array of IWpSecurityContextV1Requests;
  public
    function AddListener(AIntf: IWpSecurityContextV1Requests): LongInt;
  end;

  IWpSecurityContextV1Requests = interface
  ['IWpSecurityContextV1Requests']
    procedure wp_security_context_v1_destroy(AWpSecurityContextV1: TWpSecurityContextV1);
    procedure wp_security_context_v1_set_sandbox_engine(AWpSecurityContextV1: TWpSecurityContextV1; aName: String);
    procedure wp_security_context_v1_set_app_id(AWpSecurityContextV1: TWpSecurityContextV1; aAppId: String);
    procedure wp_security_context_v1_set_instance_id(AWpSecurityContextV1: TWpSecurityContextV1; aInstanceId: String);
    procedure wp_security_context_v1_commit(AWpSecurityContextV1: TWpSecurityContextV1);
  end;

implementation
uses
  wayland_stream;

class function TWpSecurityContextManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpSecurityContextManagerV1.GetInterfaceName: String;
begin
  Result := 'wp_security_context_manager_v1';
end;

procedure TWpSecurityContextManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpSecurityContextManagerV1.HandleCreateListener(var AMsg: TWaylandEventMessage);
var
  lId: TWpSecurityContextV1;
  lListenFd: TWaylandFdStream;
  lCloseFd: TWaylandFdStream;
  lListenerIdx: Integer;
begin
  lId := TWpSecurityContextV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lListenFd := AMsg.NextFdStream;
  lCloseFd := AMsg.NextFdStream;
  if Assigned(OnCreateListener) then OnCreateListener(Self,lId,lListenFd,lCloseFd);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_manager_v1_create_listener(Self,lId,lListenFd,lCloseFd);
  AMsg.SetHandled;
end;

function TWpSecurityContextManagerV1.AddListener(AIntf: IWpSecurityContextManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpSecurityContextV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpSecurityContextV1.GetInterfaceName: String;
begin
  Result := 'wp_security_context_v1';
end;

procedure TWpSecurityContextV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpSecurityContextV1.HandleSetSandboxEngine(var AMsg: TWaylandEventMessage);
var
  lName: String;
  lListenerIdx: Integer;
begin
  lName := AMsg.Args.ReadString;
  if Assigned(OnSetSandboxEngine) then OnSetSandboxEngine(Self,lName);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_v1_set_sandbox_engine(Self,lName);
  AMsg.SetHandled;
end;

procedure TWpSecurityContextV1.HandleSetAppId(var AMsg: TWaylandEventMessage);
var
  lAppId: String;
  lListenerIdx: Integer;
begin
  lAppId := AMsg.Args.ReadString;
  if Assigned(OnSetAppId) then OnSetAppId(Self,lAppId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_v1_set_app_id(Self,lAppId);
  AMsg.SetHandled;
end;

procedure TWpSecurityContextV1.HandleSetInstanceId(var AMsg: TWaylandEventMessage);
var
  lInstanceId: String;
  lListenerIdx: Integer;
begin
  lInstanceId := AMsg.Args.ReadString;
  if Assigned(OnSetInstanceId) then OnSetInstanceId(Self,lInstanceId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_v1_set_instance_id(Self,lInstanceId);
  AMsg.SetHandled;
end;

procedure TWpSecurityContextV1.HandleCommit(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnCommit) then OnCommit(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_security_context_v1_commit(Self);
  AMsg.SetHandled;
end;

function TWpSecurityContextV1.AddListener(AIntf: IWpSecurityContextV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('wp_security_context_manager_v1', TWpSecurityContextManagerV1);
  RegisterServerInterface('wp_security_context_v1', TWpSecurityContextV1);

end.