// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_system_bell_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TXdgSystemBellV1Class = class of TXdgSystemBellV1;
  { TXdgSystemBellV1 }
  TXdgSystemBellV1 = class;

  IXdgSystemBellV1Requests = interface;

  [TWLIntfAttribute('destroy(),ring(?o)', '')]
  { TXdgSystemBellV1 }
  TXdgSystemBellV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgSystemBellV1) of object;
    TRingEvent = procedure(Sender: TXdgSystemBellV1; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _RING = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnRingPriv: TRingEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleRing(var AMsg: TWaylandEventMessage); message Ord(TRequests._RING); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnRing: TRingEvent read FOnRingPriv write FOnRingPriv;
  private
    FListeners: array of IXdgSystemBellV1Requests;
  public
    function AddListener(AIntf: IXdgSystemBellV1Requests): LongInt;
  end;

  IXdgSystemBellV1Requests = interface
  ['IXdgSystemBellV1Requests']
    procedure xdg_system_bell_v1_destroy(AXdgSystemBellV1: TXdgSystemBellV1);
    procedure xdg_system_bell_v1_ring(AXdgSystemBellV1: TXdgSystemBellV1; aSurface: TWlSurface);
  end;

implementation
uses
  wayland_stream;

class function TXdgSystemBellV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgSystemBellV1.GetInterfaceName: String;
begin
  Result := 'xdg_system_bell_v1';
end;

procedure TXdgSystemBellV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_system_bell_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgSystemBellV1.HandleRing(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnRing) then OnRing(Self,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_system_bell_v1_ring(Self,lSurface);
  AMsg.SetHandled;
end;

function TXdgSystemBellV1.AddListener(AIntf: IXdgSystemBellV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.