// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_toplevel_icon_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server, xdg_shell_server;

type
  TXdgToplevelIconV1Class = class of TXdgToplevelIconV1;
  { TXdgToplevelIconV1 }
  TXdgToplevelIconV1 = class;

  TXdgToplevelIconManagerV1Class = class of TXdgToplevelIconManagerV1;
  { TXdgToplevelIconManagerV1 }
  TXdgToplevelIconManagerV1 = class;

  IXdgToplevelIconManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),create_icon(n),set_icon(o?o)', 'icon_size(i),done()')]
  { TXdgToplevelIconManagerV1 }
  TXdgToplevelIconManagerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgToplevelIconManagerV1) of object;
    TCreateIconEvent = procedure(Sender: TXdgToplevelIconManagerV1; aId: TXdgToplevelIconV1) of object;
    TSetIconEvent = procedure(Sender: TXdgToplevelIconManagerV1; aToplevel: TXdgToplevel; aIcon: TXdgToplevelIconV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_ICON = 1, _SET_ICON = 2);
    TEvents = (EV_ICON_SIZE = 0, EV_DONE = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreateIconPriv: TCreateIconEvent;
    FOnSetIconPriv: TSetIconEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreateIcon(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_ICON); virtual;
    procedure HandleSetIcon(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_ICON); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreateIcon: TCreateIconEvent read FOnCreateIconPriv write FOnCreateIconPriv;
    property OnSetIcon: TSetIconEvent read FOnSetIconPriv write FOnSetIconPriv;
  public
    procedure IconSize(aSize: Integer);
    procedure Done;
  private
    FListeners: array of IXdgToplevelIconManagerV1Requests;
  public
    function AddListener(AIntf: IXdgToplevelIconManagerV1Requests): LongInt;
  end;

  IXdgToplevelIconManagerV1Requests = interface
  ['IXdgToplevelIconManagerV1Requests']
    procedure xdg_toplevel_icon_manager_v1_destroy(AXdgToplevelIconManagerV1: TXdgToplevelIconManagerV1);
    procedure xdg_toplevel_icon_manager_v1_create_icon(AXdgToplevelIconManagerV1: TXdgToplevelIconManagerV1; aId: TXdgToplevelIconV1);
    procedure xdg_toplevel_icon_manager_v1_set_icon(AXdgToplevelIconManagerV1: TXdgToplevelIconManagerV1; aToplevel: TXdgToplevel; aIcon: TXdgToplevelIconV1);
  end;

  IXdgToplevelIconV1Requests = interface;

  [TWLIntfAttribute('destroy(),set_name(s),add_buffer(oi)', '')]
  { TXdgToplevelIconV1 }
  TXdgToplevelIconV1 = class(TWaylandServerResource)
  public type
    TError = (erInvalidbuffer = 1, erImmutable = 2, erNobuffer = 3);
    TDestroyEvent = procedure(Sender: TXdgToplevelIconV1) of object;
    TSetNameEvent = procedure(Sender: TXdgToplevelIconV1; aIconName: String) of object;
    TAddBufferEvent = procedure(Sender: TXdgToplevelIconV1; aBuffer: TWlBuffer; aScale: Integer) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_NAME = 1, _ADD_BUFFER = 2);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetNamePriv: TSetNameEvent;
    FOnAddBufferPriv: TAddBufferEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetName(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_NAME); virtual;
    procedure HandleAddBuffer(var AMsg: TWaylandEventMessage); message Ord(TRequests._ADD_BUFFER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetName: TSetNameEvent read FOnSetNamePriv write FOnSetNamePriv;
    property OnAddBuffer: TAddBufferEvent read FOnAddBufferPriv write FOnAddBufferPriv;
  private
    FListeners: array of IXdgToplevelIconV1Requests;
  public
    function AddListener(AIntf: IXdgToplevelIconV1Requests): LongInt;
  end;

  IXdgToplevelIconV1Requests = interface
  ['IXdgToplevelIconV1Requests']
    procedure xdg_toplevel_icon_v1_destroy(AXdgToplevelIconV1: TXdgToplevelIconV1);
    procedure xdg_toplevel_icon_v1_set_name(AXdgToplevelIconV1: TXdgToplevelIconV1; aIconName: String);
    procedure xdg_toplevel_icon_v1_add_buffer(AXdgToplevelIconV1: TXdgToplevelIconV1; aBuffer: TWlBuffer; aScale: Integer);
  end;

implementation
uses
  wayland_stream;

class function TXdgToplevelIconManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgToplevelIconManagerV1.GetInterfaceName: String;
begin
  Result := 'xdg_toplevel_icon_manager_v1';
end;

procedure TXdgToplevelIconManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelIconManagerV1.HandleCreateIcon(var AMsg: TWaylandEventMessage);
var
  lId: TXdgToplevelIconV1;
  lListenerIdx: Integer;
begin
  lId := TXdgToplevelIconV1.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnCreateIcon) then OnCreateIcon(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_manager_v1_create_icon(Self,lId);
  AMsg.SetHandled;
end;

procedure TXdgToplevelIconManagerV1.HandleSetIcon(var AMsg: TWaylandEventMessage);
var
  lToplevel: TXdgToplevel;
  lIcon: TXdgToplevelIconV1;
  lListenerIdx: Integer;
begin
  lToplevel := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgToplevel);
  lIcon := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgToplevelIconV1);
  if Assigned(OnSetIcon) then OnSetIcon(Self,lToplevel,lIcon);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_manager_v1_set_icon(Self,lToplevel,lIcon);
  AMsg.SetHandled;
end;

procedure TXdgToplevelIconManagerV1.IconSize(aSize: Integer);
begin
  SendEvent(Ord(TEvents.EV_ICON_SIZE), [aSize]);
end;

procedure TXdgToplevelIconManagerV1.Done;
begin
  SendEvent(Ord(TEvents.EV_DONE), []);
end;

function TXdgToplevelIconManagerV1.AddListener(AIntf: IXdgToplevelIconManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgToplevelIconV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgToplevelIconV1.GetInterfaceName: String;
begin
  Result := 'xdg_toplevel_icon_v1';
end;

procedure TXdgToplevelIconV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelIconV1.HandleSetName(var AMsg: TWaylandEventMessage);
var
  lIconName: String;
  lListenerIdx: Integer;
begin
  lIconName := AMsg.Args.ReadString;
  if Assigned(OnSetName) then OnSetName(Self,lIconName);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_v1_set_name(Self,lIconName);
  AMsg.SetHandled;
end;

procedure TXdgToplevelIconV1.HandleAddBuffer(var AMsg: TWaylandEventMessage);
var
  lBuffer: TWlBuffer;
  lScale: Integer;
  lListenerIdx: Integer;
begin
  lBuffer := (Client.GetObject(AMsg.Args.ReadDWord) as TWlBuffer);
  lScale := AMsg.Args.ReadInteger;
  if Assigned(OnAddBuffer) then OnAddBuffer(Self,lBuffer,lScale);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_icon_v1_add_buffer(Self,lBuffer,lScale);
  AMsg.SetHandled;
end;

function TXdgToplevelIconV1.AddListener(AIntf: IXdgToplevelIconV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.