// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit fullscreen_shell_unstable_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpFullscreenShellModeFeedbackV1Class = class of TWpFullscreenShellModeFeedbackV1;
  { TWpFullscreenShellModeFeedbackV1 }
  TWpFullscreenShellModeFeedbackV1 = class;

  TWpFullscreenShellV1Class = class of TWpFullscreenShellV1;
  { TWpFullscreenShellV1 }
  TWpFullscreenShellV1 = class;

  IWpFullscreenShellV1Requests = interface;

  [TWLIntfAttribute('release(),present_surface(?ou?o),present_surface_for_mode(ooin)', 'capability(u)')]
  { TWpFullscreenShellV1 }
  TWpFullscreenShellV1 = class(TWaylandServerResource)
  public type
    TCapability = (caArbitrarymodes = 1, caCursorplane = 2);
    TPresentMethod = (prDefault = 0, prCenter = 1, prZoom = 2, prZoomcrop = 3, prStretch = 4);
    TError = (erInvalidmethod = 0, erRole = 1);
    TReleaseEvent = procedure(Sender: TWpFullscreenShellV1) of object;
    TPresentSurfaceEvent = procedure(Sender: TWpFullscreenShellV1; aSurface: TWlSurface; aMethod: TPresentMethod; aOutput: TWlOutput) of object;
    TPresentSurfaceForModeEvent = procedure(Sender: TWpFullscreenShellV1; aSurface: TWlSurface; aOutput: TWlOutput; aFramerate: Integer; aFeedback: TWpFullscreenShellModeFeedbackV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_RELEASE = 0, _PRESENT_SURFACE = 1, _PRESENT_SURFACE_FOR_MODE = 2);
    TEvents = (EV_CAPABILITY = 0);
  private
    FOnReleasePriv: TReleaseEvent;
    FOnPresentSurfacePriv: TPresentSurfaceEvent;
    FOnPresentSurfaceForModePriv: TPresentSurfaceForModeEvent;
  protected
    procedure HandleRelease(var AMsg: TWaylandEventMessage); message Ord(TRequests._RELEASE); virtual;
    procedure HandlePresentSurface(var AMsg: TWaylandEventMessage); message Ord(TRequests._PRESENT_SURFACE); virtual;
    procedure HandlePresentSurfaceForMode(var AMsg: TWaylandEventMessage); message Ord(TRequests._PRESENT_SURFACE_FOR_MODE); virtual;
  published
    property OnRelease: TReleaseEvent read FOnReleasePriv write FOnReleasePriv;
    property OnPresentSurface: TPresentSurfaceEvent read FOnPresentSurfacePriv write FOnPresentSurfacePriv;
    property OnPresentSurfaceForMode: TPresentSurfaceForModeEvent read FOnPresentSurfaceForModePriv write FOnPresentSurfaceForModePriv;
  public
    procedure Capability(aCapability: TCapability);
  private
    FListeners: array of IWpFullscreenShellV1Requests;
  public
    function AddListener(AIntf: IWpFullscreenShellV1Requests): LongInt;
  end;

  IWpFullscreenShellV1Requests = interface
  ['IWpFullscreenShellV1Requests']
    procedure wp_fullscreen_shell_v1_release(AWpFullscreenShellV1: TWpFullscreenShellV1);
    procedure wp_fullscreen_shell_v1_present_surface(AWpFullscreenShellV1: TWpFullscreenShellV1; aSurface: TWlSurface; aMethod: TWpFullscreenShellV1.TPresentMethod; aOutput: TWlOutput);
    procedure wp_fullscreen_shell_v1_present_surface_for_mode(AWpFullscreenShellV1: TWpFullscreenShellV1; aSurface: TWlSurface; aOutput: TWlOutput; aFramerate: Integer; aFeedback: TWpFullscreenShellModeFeedbackV1);
  end;

  IWpFullscreenShellModeFeedbackV1Requests = interface;

  [TWLIntfAttribute('', 'mode_successful(),mode_failed(),present_cancelled()')]
  { TWpFullscreenShellModeFeedbackV1 }
  TWpFullscreenShellModeFeedbackV1 = class(TWaylandServerResource)
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TEvents = (EV_MODE_SUCCESSFUL = 0, EV_MODE_FAILED = 1, EV_PRESENT_CANCELLED = 2);
  public
    procedure ModeSuccessful;
    procedure ModeFailed;
    procedure PresentCancelled;
  private
    FListeners: array of IWpFullscreenShellModeFeedbackV1Requests;
  public
    function AddListener(AIntf: IWpFullscreenShellModeFeedbackV1Requests): LongInt;
  end;

  IWpFullscreenShellModeFeedbackV1Requests = interface
  ['IWpFullscreenShellModeFeedbackV1Requests']
  end;

implementation
uses
  wayland_stream;

class function TWpFullscreenShellV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpFullscreenShellV1.GetInterfaceName: String;
begin
  Result := 'zwp_fullscreen_shell_v1';
end;

procedure TWpFullscreenShellV1.HandleRelease(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnRelease) then OnRelease(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_fullscreen_shell_v1_release(Self);
  AMsg.SetHandled;
end;

procedure TWpFullscreenShellV1.HandlePresentSurface(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lMethod: TPresentMethod;
  lOutput: TWlOutput;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lMethod := TPresentMethod(AMsg.Args.ReadDWord);
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  if Assigned(OnPresentSurface) then OnPresentSurface(Self,lSurface,lMethod,lOutput);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_fullscreen_shell_v1_present_surface(Self,lSurface,lMethod,lOutput);
  AMsg.SetHandled;
end;

procedure TWpFullscreenShellV1.HandlePresentSurfaceForMode(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lOutput: TWlOutput;
  lFramerate: Integer;
  lFeedback: TWpFullscreenShellModeFeedbackV1;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  lFramerate := AMsg.Args.ReadInteger;
  lFeedback := TWpFullscreenShellModeFeedbackV1.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnPresentSurfaceForMode) then OnPresentSurfaceForMode(Self,lSurface,lOutput,lFramerate,lFeedback);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_fullscreen_shell_v1_present_surface_for_mode(Self,lSurface,lOutput,lFramerate,lFeedback);
  AMsg.SetHandled;
end;

procedure TWpFullscreenShellV1.Capability(aCapability: TCapability);
begin
  SendEvent(Ord(TEvents.EV_CAPABILITY), [DWord(aCapability)]);
end;

function TWpFullscreenShellV1.AddListener(AIntf: IWpFullscreenShellV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpFullscreenShellModeFeedbackV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpFullscreenShellModeFeedbackV1.GetInterfaceName: String;
begin
  Result := 'zwp_fullscreen_shell_mode_feedback_v1';
end;

procedure TWpFullscreenShellModeFeedbackV1.ModeSuccessful;
begin
  SendEvent(Ord(TEvents.EV_MODE_SUCCESSFUL), []);
end;

procedure TWpFullscreenShellModeFeedbackV1.ModeFailed;
begin
  SendEvent(Ord(TEvents.EV_MODE_FAILED), []);
end;

procedure TWpFullscreenShellModeFeedbackV1.PresentCancelled;
begin
  SendEvent(Ord(TEvents.EV_PRESENT_CANCELLED), []);
end;

function TWpFullscreenShellModeFeedbackV1.AddListener(AIntf: IWpFullscreenShellModeFeedbackV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.