// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit idle_inhibit_unstable_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpIdleInhibitorV1Class = class of TWpIdleInhibitorV1;
  { TWpIdleInhibitorV1 }
  TWpIdleInhibitorV1 = class;

  TWpIdleInhibitManagerV1Class = class of TWpIdleInhibitManagerV1;
  { TWpIdleInhibitManagerV1 }
  TWpIdleInhibitManagerV1 = class;

  IWpIdleInhibitManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),create_inhibitor(no)', '')]
  { TWpIdleInhibitManagerV1 }
  TWpIdleInhibitManagerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpIdleInhibitManagerV1) of object;
    TCreateInhibitorEvent = procedure(Sender: TWpIdleInhibitManagerV1; aId: TWpIdleInhibitorV1; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_INHIBITOR = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreateInhibitorPriv: TCreateInhibitorEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreateInhibitor(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_INHIBITOR); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreateInhibitor: TCreateInhibitorEvent read FOnCreateInhibitorPriv write FOnCreateInhibitorPriv;
  private
    FListeners: array of IWpIdleInhibitManagerV1Requests;
  public
    function AddListener(AIntf: IWpIdleInhibitManagerV1Requests): LongInt;
  end;

  IWpIdleInhibitManagerV1Requests = interface
  ['IWpIdleInhibitManagerV1Requests']
    procedure wp_idle_inhibit_manager_v1_destroy(AWpIdleInhibitManagerV1: TWpIdleInhibitManagerV1);
    procedure wp_idle_inhibit_manager_v1_create_inhibitor(AWpIdleInhibitManagerV1: TWpIdleInhibitManagerV1; aId: TWpIdleInhibitorV1; aSurface: TWlSurface);
  end;

  IWpIdleInhibitorV1Requests = interface;

  [TWLIntfAttribute('destroy()', '')]
  { TWpIdleInhibitorV1 }
  TWpIdleInhibitorV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpIdleInhibitorV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  private
    FListeners: array of IWpIdleInhibitorV1Requests;
  public
    function AddListener(AIntf: IWpIdleInhibitorV1Requests): LongInt;
  end;

  IWpIdleInhibitorV1Requests = interface
  ['IWpIdleInhibitorV1Requests']
    procedure wp_idle_inhibitor_v1_destroy(AWpIdleInhibitorV1: TWpIdleInhibitorV1);
  end;

implementation
uses
  wayland_stream;

class function TWpIdleInhibitManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpIdleInhibitManagerV1.GetInterfaceName: String;
begin
  Result := 'zwp_idle_inhibit_manager_v1';
end;

procedure TWpIdleInhibitManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_idle_inhibit_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpIdleInhibitManagerV1.HandleCreateInhibitor(var AMsg: TWaylandEventMessage);
var
  lId: TWpIdleInhibitorV1;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TWpIdleInhibitorV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnCreateInhibitor) then OnCreateInhibitor(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_idle_inhibit_manager_v1_create_inhibitor(Self,lId,lSurface);
  AMsg.SetHandled;
end;

function TWpIdleInhibitManagerV1.AddListener(AIntf: IWpIdleInhibitManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpIdleInhibitorV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpIdleInhibitorV1.GetInterfaceName: String;
begin
  Result := 'zwp_idle_inhibitor_v1';
end;

procedure TWpIdleInhibitorV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_idle_inhibitor_v1_destroy(Self);
  AMsg.SetHandled;
end;

function TWpIdleInhibitorV1.AddListener(AIntf: IWpIdleInhibitorV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('zwp_idle_inhibit_manager_v1', TWpIdleInhibitManagerV1);
  RegisterServerInterface('zwp_idle_inhibitor_v1', TWpIdleInhibitorV1);

end.