// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit pointer_constraints_unstable_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpConfinedPointerV1Class = class of TWpConfinedPointerV1;
  { TWpConfinedPointerV1 }
  TWpConfinedPointerV1 = class;

  TWpLockedPointerV1Class = class of TWpLockedPointerV1;
  { TWpLockedPointerV1 }
  TWpLockedPointerV1 = class;

  TWpPointerConstraintsV1Class = class of TWpPointerConstraintsV1;
  { TWpPointerConstraintsV1 }
  TWpPointerConstraintsV1 = class;

  IWpPointerConstraintsV1Requests = interface;

  [TWLIntfAttribute('destroy(),lock_pointer(noo?ou),confine_pointer(noo?ou)', '')]
  { TWpPointerConstraintsV1 }
  TWpPointerConstraintsV1 = class(TWaylandServerResource)
  public type
    TError = (erAlreadyconstrained = 1);
    TLifetime = (liOneshot = 1, liPersistent = 2);
    TDestroyEvent = procedure(Sender: TWpPointerConstraintsV1) of object;
    TLockPointerEvent = procedure(Sender: TWpPointerConstraintsV1; aId: TWpLockedPointerV1; aSurface: TWlSurface; aPointer: TWlPointer; aRegion: TWlRegion; aLifetime: TLifetime) of object;
    TConfinePointerEvent = procedure(Sender: TWpPointerConstraintsV1; aId: TWpConfinedPointerV1; aSurface: TWlSurface; aPointer: TWlPointer; aRegion: TWlRegion; aLifetime: TLifetime) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _LOCK_POINTER = 1, _CONFINE_POINTER = 2);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnLockPointerPriv: TLockPointerEvent;
    FOnConfinePointerPriv: TConfinePointerEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleLockPointer(var AMsg: TWaylandEventMessage); message Ord(TRequests._LOCK_POINTER); virtual;
    procedure HandleConfinePointer(var AMsg: TWaylandEventMessage); message Ord(TRequests._CONFINE_POINTER); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnLockPointer: TLockPointerEvent read FOnLockPointerPriv write FOnLockPointerPriv;
    property OnConfinePointer: TConfinePointerEvent read FOnConfinePointerPriv write FOnConfinePointerPriv;
  private
    FListeners: array of IWpPointerConstraintsV1Requests;
  public
    function AddListener(AIntf: IWpPointerConstraintsV1Requests): LongInt;
  end;

  IWpPointerConstraintsV1Requests = interface
  ['IWpPointerConstraintsV1Requests']
    procedure wp_pointer_constraints_v1_destroy(AWpPointerConstraintsV1: TWpPointerConstraintsV1);
    procedure wp_pointer_constraints_v1_lock_pointer(AWpPointerConstraintsV1: TWpPointerConstraintsV1; aId: TWpLockedPointerV1; aSurface: TWlSurface; aPointer: TWlPointer; aRegion: TWlRegion; aLifetime: TWpPointerConstraintsV1.TLifetime);
    procedure wp_pointer_constraints_v1_confine_pointer(AWpPointerConstraintsV1: TWpPointerConstraintsV1; aId: TWpConfinedPointerV1; aSurface: TWlSurface; aPointer: TWlPointer; aRegion: TWlRegion; aLifetime: TWpPointerConstraintsV1.TLifetime);
  end;

  IWpLockedPointerV1Requests = interface;

  [TWLIntfAttribute('destroy(),set_cursor_position_hint(ff),set_region(?o)', 'locked(),unlocked()')]
  { TWpLockedPointerV1 }
  TWpLockedPointerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpLockedPointerV1) of object;
    TSetCursorPositionHintEvent = procedure(Sender: TWpLockedPointerV1; aSurfaceX: TWaylandFixed; aSurfaceY: TWaylandFixed) of object;
    TSetRegionEvent = procedure(Sender: TWpLockedPointerV1; aRegion: TWlRegion) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_CURSOR_POSITION_HINT = 1, _SET_REGION = 2);
    TEvents = (EV_LOCKED = 0, EV_UNLOCKED = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetCursorPositionHintPriv: TSetCursorPositionHintEvent;
    FOnSetRegionPriv: TSetRegionEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetCursorPositionHint(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_CURSOR_POSITION_HINT); virtual;
    procedure HandleSetRegion(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_REGION); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetCursorPositionHint: TSetCursorPositionHintEvent read FOnSetCursorPositionHintPriv write FOnSetCursorPositionHintPriv;
    property OnSetRegion: TSetRegionEvent read FOnSetRegionPriv write FOnSetRegionPriv;
  public
    procedure Locked;
    procedure Unlocked;
  private
    FListeners: array of IWpLockedPointerV1Requests;
  public
    function AddListener(AIntf: IWpLockedPointerV1Requests): LongInt;
  end;

  IWpLockedPointerV1Requests = interface
  ['IWpLockedPointerV1Requests']
    procedure wp_locked_pointer_v1_destroy(AWpLockedPointerV1: TWpLockedPointerV1);
    procedure wp_locked_pointer_v1_set_cursor_position_hint(AWpLockedPointerV1: TWpLockedPointerV1; aSurfaceX: TWaylandFixed; aSurfaceY: TWaylandFixed);
    procedure wp_locked_pointer_v1_set_region(AWpLockedPointerV1: TWpLockedPointerV1; aRegion: TWlRegion);
  end;

  IWpConfinedPointerV1Requests = interface;

  [TWLIntfAttribute('destroy(),set_region(?o)', 'confined(),unconfined()')]
  { TWpConfinedPointerV1 }
  TWpConfinedPointerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpConfinedPointerV1) of object;
    TSetRegionEvent = procedure(Sender: TWpConfinedPointerV1; aRegion: TWlRegion) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_REGION = 1);
    TEvents = (EV_CONFINED = 0, EV_UNCONFINED = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetRegionPriv: TSetRegionEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetRegion(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_REGION); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetRegion: TSetRegionEvent read FOnSetRegionPriv write FOnSetRegionPriv;
  public
    procedure Confined;
    procedure Unconfined;
  private
    FListeners: array of IWpConfinedPointerV1Requests;
  public
    function AddListener(AIntf: IWpConfinedPointerV1Requests): LongInt;
  end;

  IWpConfinedPointerV1Requests = interface
  ['IWpConfinedPointerV1Requests']
    procedure wp_confined_pointer_v1_destroy(AWpConfinedPointerV1: TWpConfinedPointerV1);
    procedure wp_confined_pointer_v1_set_region(AWpConfinedPointerV1: TWpConfinedPointerV1; aRegion: TWlRegion);
  end;

implementation
uses
  wayland_stream;

class function TWpPointerConstraintsV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpPointerConstraintsV1.GetInterfaceName: String;
begin
  Result := 'zwp_pointer_constraints_v1';
end;

procedure TWpPointerConstraintsV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_pointer_constraints_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpPointerConstraintsV1.HandleLockPointer(var AMsg: TWaylandEventMessage);
var
  lId: TWpLockedPointerV1;
  lSurface: TWlSurface;
  lPointer: TWlPointer;
  lRegion: TWlRegion;
  lLifetime: TLifetime;
  lListenerIdx: Integer;
begin
  lId := TWpLockedPointerV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lPointer := (Client.GetObject(AMsg.Args.ReadDWord) as TWlPointer);
  lRegion := (Client.GetObject(AMsg.Args.ReadDWord) as TWlRegion);
  lLifetime := TLifetime(AMsg.Args.ReadDWord);
  if Assigned(OnLockPointer) then OnLockPointer(Self,lId,lSurface,lPointer,lRegion,lLifetime);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_pointer_constraints_v1_lock_pointer(Self,lId,lSurface,lPointer,lRegion,lLifetime);
  AMsg.SetHandled;
end;

procedure TWpPointerConstraintsV1.HandleConfinePointer(var AMsg: TWaylandEventMessage);
var
  lId: TWpConfinedPointerV1;
  lSurface: TWlSurface;
  lPointer: TWlPointer;
  lRegion: TWlRegion;
  lLifetime: TLifetime;
  lListenerIdx: Integer;
begin
  lId := TWpConfinedPointerV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lPointer := (Client.GetObject(AMsg.Args.ReadDWord) as TWlPointer);
  lRegion := (Client.GetObject(AMsg.Args.ReadDWord) as TWlRegion);
  lLifetime := TLifetime(AMsg.Args.ReadDWord);
  if Assigned(OnConfinePointer) then OnConfinePointer(Self,lId,lSurface,lPointer,lRegion,lLifetime);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_pointer_constraints_v1_confine_pointer(Self,lId,lSurface,lPointer,lRegion,lLifetime);
  AMsg.SetHandled;
end;

function TWpPointerConstraintsV1.AddListener(AIntf: IWpPointerConstraintsV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpLockedPointerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpLockedPointerV1.GetInterfaceName: String;
begin
  Result := 'zwp_locked_pointer_v1';
end;

procedure TWpLockedPointerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_locked_pointer_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpLockedPointerV1.HandleSetCursorPositionHint(var AMsg: TWaylandEventMessage);
var
  lSurfaceX: TWaylandFixed;
  lSurfaceY: TWaylandFixed;
  lListenerIdx: Integer;
begin
  lSurfaceX := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lSurfaceY := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  if Assigned(OnSetCursorPositionHint) then OnSetCursorPositionHint(Self,lSurfaceX,lSurfaceY);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_locked_pointer_v1_set_cursor_position_hint(Self,lSurfaceX,lSurfaceY);
  AMsg.SetHandled;
end;

procedure TWpLockedPointerV1.HandleSetRegion(var AMsg: TWaylandEventMessage);
var
  lRegion: TWlRegion;
  lListenerIdx: Integer;
begin
  lRegion := (Client.GetObject(AMsg.Args.ReadDWord) as TWlRegion);
  if Assigned(OnSetRegion) then OnSetRegion(Self,lRegion);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_locked_pointer_v1_set_region(Self,lRegion);
  AMsg.SetHandled;
end;

procedure TWpLockedPointerV1.Locked;
begin
  SendEvent(Ord(TEvents.EV_LOCKED), []);
end;

procedure TWpLockedPointerV1.Unlocked;
begin
  SendEvent(Ord(TEvents.EV_UNLOCKED), []);
end;

function TWpLockedPointerV1.AddListener(AIntf: IWpLockedPointerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpConfinedPointerV1.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpConfinedPointerV1.GetInterfaceName: String;
begin
  Result := 'zwp_confined_pointer_v1';
end;

procedure TWpConfinedPointerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_confined_pointer_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpConfinedPointerV1.HandleSetRegion(var AMsg: TWaylandEventMessage);
var
  lRegion: TWlRegion;
  lListenerIdx: Integer;
begin
  lRegion := (Client.GetObject(AMsg.Args.ReadDWord) as TWlRegion);
  if Assigned(OnSetRegion) then OnSetRegion(Self,lRegion);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_confined_pointer_v1_set_region(Self,lRegion);
  AMsg.SetHandled;
end;

procedure TWpConfinedPointerV1.Confined;
begin
  SendEvent(Ord(TEvents.EV_CONFINED), []);
end;

procedure TWpConfinedPointerV1.Unconfined;
begin
  SendEvent(Ord(TEvents.EV_UNCONFINED), []);
end;

function TWpConfinedPointerV1.AddListener(AIntf: IWpConfinedPointerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('zwp_pointer_constraints_v1', TWpPointerConstraintsV1);
  RegisterServerInterface('zwp_locked_pointer_v1', TWpLockedPointerV1);
  RegisterServerInterface('zwp_confined_pointer_v1', TWpConfinedPointerV1);

end.