// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_output_unstable_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TXdgOutputV1Class = class of TXdgOutputV1;
  { TXdgOutputV1 }
  TXdgOutputV1 = class;

  TXdgOutputManagerV1Class = class of TXdgOutputManagerV1;
  { TXdgOutputManagerV1 }
  TXdgOutputManagerV1 = class;

  IXdgOutputManagerV1Requests = interface;

  [TWLIntfAttribute('destroy(),get_xdg_output(no)', '')]
  { TXdgOutputManagerV1 }
  TXdgOutputManagerV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgOutputManagerV1) of object;
    TGetXdgOutputEvent = procedure(Sender: TXdgOutputManagerV1; aId: TXdgOutputV1; aOutput: TWlOutput) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_XDG_OUTPUT = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetXdgOutputPriv: TGetXdgOutputEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetXdgOutput(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_XDG_OUTPUT); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetXdgOutput: TGetXdgOutputEvent read FOnGetXdgOutputPriv write FOnGetXdgOutputPriv;
  private
    FListeners: array of IXdgOutputManagerV1Requests;
  public
    function AddListener(AIntf: IXdgOutputManagerV1Requests): LongInt;
  end;

  IXdgOutputManagerV1Requests = interface
  ['IXdgOutputManagerV1Requests']
    procedure xdg_output_manager_v1_destroy(AXdgOutputManagerV1: TXdgOutputManagerV1);
    procedure xdg_output_manager_v1_get_xdg_output(AXdgOutputManagerV1: TXdgOutputManagerV1; aId: TXdgOutputV1; aOutput: TWlOutput);
  end;

  IXdgOutputV1Requests = interface;

  [TWLIntfAttribute('destroy()', 'logical_position(ii),logical_size(ii),done(),name(s),description(s)')]
  { TXdgOutputV1 }
  TXdgOutputV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgOutputV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0);
    TEvents = (EV_LOGICAL_POSITION = 0, EV_LOGICAL_SIZE = 1, EV_DONE = 2, EV_NAME = 3, EV_DESCRIPTION = 4);
  private
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  public
    procedure LogicalPosition(aX: Integer; aY: Integer);
    procedure LogicalSize(aWidth: Integer; aHeight: Integer);
    procedure Done;
    procedure Name(aName: String);
    procedure Description(aDescription: String);
  private
    FListeners: array of IXdgOutputV1Requests;
  public
    function AddListener(AIntf: IXdgOutputV1Requests): LongInt;
  end;

  IXdgOutputV1Requests = interface
  ['IXdgOutputV1Requests']
    procedure xdg_output_v1_destroy(AXdgOutputV1: TXdgOutputV1);
  end;

implementation
uses
  wayland_stream;

class function TXdgOutputManagerV1.GetInterfaceVersion: Integer;
begin
  Result := 3;
end;

class function TXdgOutputManagerV1.GetInterfaceName: String;
begin
  Result := 'zxdg_output_manager_v1';
end;

procedure TXdgOutputManagerV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_output_manager_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgOutputManagerV1.HandleGetXdgOutput(var AMsg: TWaylandEventMessage);
var
  lId: TXdgOutputV1;
  lOutput: TWlOutput;
  lListenerIdx: Integer;
begin
  lId := TXdgOutputV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  if Assigned(OnGetXdgOutput) then OnGetXdgOutput(Self,lId,lOutput);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_output_manager_v1_get_xdg_output(Self,lId,lOutput);
  AMsg.SetHandled;
end;

function TXdgOutputManagerV1.AddListener(AIntf: IXdgOutputManagerV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgOutputV1.GetInterfaceVersion: Integer;
begin
  Result := 3;
end;

class function TXdgOutputV1.GetInterfaceName: String;
begin
  Result := 'zxdg_output_v1';
end;

procedure TXdgOutputV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_output_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgOutputV1.LogicalPosition(aX: Integer; aY: Integer);
begin
  SendEvent(Ord(TEvents.EV_LOGICAL_POSITION), [aX,aY]);
end;

procedure TXdgOutputV1.LogicalSize(aWidth: Integer; aHeight: Integer);
begin
  SendEvent(Ord(TEvents.EV_LOGICAL_SIZE), [aWidth,aHeight]);
end;

procedure TXdgOutputV1.Done;
begin
  SendEvent(Ord(TEvents.EV_DONE), []);
end;

procedure TXdgOutputV1.Name(aName: String);
begin
  SendEvent(Ord(TEvents.EV_NAME), [aName]);
end;

procedure TXdgOutputV1.Description(aDescription: String);
begin
  SendEvent(Ord(TEvents.EV_DESCRIPTION), [aDescription]);
end;

function TXdgOutputV1.AddListener(AIntf: IXdgOutputV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.