// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_shell_unstable_v6_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TXdgPopupV6Class = class of TXdgPopupV6;
  { TXdgPopupV6 }
  TXdgPopupV6 = class;

  TXdgToplevelV6Class = class of TXdgToplevelV6;
  { TXdgToplevelV6 }
  TXdgToplevelV6 = class;

  TXdgSurfaceV6Class = class of TXdgSurfaceV6;
  { TXdgSurfaceV6 }
  TXdgSurfaceV6 = class;

  TXdgPositionerV6Class = class of TXdgPositionerV6;
  { TXdgPositionerV6 }
  TXdgPositionerV6 = class;

  TXdgShellV6Class = class of TXdgShellV6;
  { TXdgShellV6 }
  TXdgShellV6 = class;

  IXdgShellV6Requests = interface;

  [TWLIntfAttribute('destroy(),create_positioner(n),get_xdg_surface(no),pong(u)', 'ping(u)')]
  { TXdgShellV6 }
  TXdgShellV6 = class(TWaylandServerResource)
  public type
    TError = (erRole = 0, erDefunctsurfaces = 1, erNotthetopmostpopup = 2, erInvalidpopupparent = 3, erInvalidsurfacestate = 4, erInvalidpositioner = 5);
    TDestroyEvent = procedure(Sender: TXdgShellV6) of object;
    TCreatePositionerEvent = procedure(Sender: TXdgShellV6; aId: TXdgPositionerV6) of object;
    TGetXdgSurfaceEvent = procedure(Sender: TXdgShellV6; aId: TXdgSurfaceV6; aSurface: TWlSurface) of object;
    TPongEvent = procedure(Sender: TXdgShellV6; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_POSITIONER = 1, _GET_XDG_SURFACE = 2, _PONG = 3);
    TEvents = (EV_PING = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreatePositionerPriv: TCreatePositionerEvent;
    FOnGetXdgSurfacePriv: TGetXdgSurfaceEvent;
    FOnPongPriv: TPongEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreatePositioner(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_POSITIONER); virtual;
    procedure HandleGetXdgSurface(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_XDG_SURFACE); virtual;
    procedure HandlePong(var AMsg: TWaylandEventMessage); message Ord(TRequests._PONG); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreatePositioner: TCreatePositionerEvent read FOnCreatePositionerPriv write FOnCreatePositionerPriv;
    property OnGetXdgSurface: TGetXdgSurfaceEvent read FOnGetXdgSurfacePriv write FOnGetXdgSurfacePriv;
    property OnPong: TPongEvent read FOnPongPriv write FOnPongPriv;
  public
    procedure Ping(aSerial: DWord);
  private
    FListeners: array of IXdgShellV6Requests;
  public
    function AddListener(AIntf: IXdgShellV6Requests): LongInt;
  end;

  IXdgShellV6Requests = interface
  ['IXdgShellV6Requests']
    procedure xdg_shell_v6_destroy(AXdgShellV6: TXdgShellV6);
    procedure xdg_shell_v6_create_positioner(AXdgShellV6: TXdgShellV6; aId: TXdgPositionerV6);
    procedure xdg_shell_v6_get_xdg_surface(AXdgShellV6: TXdgShellV6; aId: TXdgSurfaceV6; aSurface: TWlSurface);
    procedure xdg_shell_v6_pong(AXdgShellV6: TXdgShellV6; aSerial: DWord);
  end;

  IXdgPositionerV6Requests = interface;

  [TWLIntfAttribute('destroy(),set_size(ii),set_anchor_rect(iiii),set_anchor(u),set_gravity(u),set_constraint_adjustment(u),set_offset(ii)', '')]
  { TXdgPositionerV6 }
  TXdgPositionerV6 = class(TWaylandServerResource)
  public type
    TError = (erInvalidinput = 0);
    { TXdgPositionerV6.TAnchor }
    TAnchor = object(TBitfield)
    public
      property None: Boolean  index 0 read GetValue write SetValue;
      property Top: Boolean  index 1 read GetValue write SetValue;
      property Bottom: Boolean  index 2 read GetValue write SetValue;
      property Left: Boolean  index 4 read GetValue write SetValue;
      property Right: Boolean  index 8 read GetValue write SetValue;
    end;

    { TXdgPositionerV6.TGravity }
    TGravity = object(TBitfield)
    public
      property None: Boolean  index 0 read GetValue write SetValue;
      property Top: Boolean  index 1 read GetValue write SetValue;
      property Bottom: Boolean  index 2 read GetValue write SetValue;
      property Left: Boolean  index 4 read GetValue write SetValue;
      property Right: Boolean  index 8 read GetValue write SetValue;
    end;

    { TXdgPositionerV6.TConstraintAdjustment }
    TConstraintAdjustment = object(TBitfield)
    public
      property None: Boolean  index 0 read GetValue write SetValue;
      property SlideX: Boolean  index 1 read GetValue write SetValue;
      property SlideY: Boolean  index 2 read GetValue write SetValue;
      property FlipX: Boolean  index 4 read GetValue write SetValue;
      property FlipY: Boolean  index 8 read GetValue write SetValue;
      property ResizeX: Boolean  index 16 read GetValue write SetValue;
      property ResizeY: Boolean  index 32 read GetValue write SetValue;
    end;

    TDestroyEvent = procedure(Sender: TXdgPositionerV6) of object;
    TSetSizeEvent = procedure(Sender: TXdgPositionerV6; aWidth: Integer; aHeight: Integer) of object;
    TSetAnchorRectEvent = procedure(Sender: TXdgPositionerV6; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer) of object;
    TSetAnchorEvent = procedure(Sender: TXdgPositionerV6; aAnchor: TAnchor) of object;
    TSetGravityEvent = procedure(Sender: TXdgPositionerV6; aGravity: TGravity) of object;
    TSetConstraintAdjustmentEvent = procedure(Sender: TXdgPositionerV6; aConstraintAdjustment: DWord) of object;
    TSetOffsetEvent = procedure(Sender: TXdgPositionerV6; aX: Integer; aY: Integer) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_SIZE = 1, _SET_ANCHOR_RECT = 2, _SET_ANCHOR = 3, _SET_GRAVITY = 4, _SET_CONSTRAINT_ADJUSTMENT = 5, _SET_OFFSET = 6);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetSizePriv: TSetSizeEvent;
    FOnSetAnchorRectPriv: TSetAnchorRectEvent;
    FOnSetAnchorPriv: TSetAnchorEvent;
    FOnSetGravityPriv: TSetGravityEvent;
    FOnSetConstraintAdjustmentPriv: TSetConstraintAdjustmentEvent;
    FOnSetOffsetPriv: TSetOffsetEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_SIZE); virtual;
    procedure HandleSetAnchorRect(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_ANCHOR_RECT); virtual;
    procedure HandleSetAnchor(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_ANCHOR); virtual;
    procedure HandleSetGravity(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_GRAVITY); virtual;
    procedure HandleSetConstraintAdjustment(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_CONSTRAINT_ADJUSTMENT); virtual;
    procedure HandleSetOffset(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_OFFSET); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetSize: TSetSizeEvent read FOnSetSizePriv write FOnSetSizePriv;
    property OnSetAnchorRect: TSetAnchorRectEvent read FOnSetAnchorRectPriv write FOnSetAnchorRectPriv;
    property OnSetAnchor: TSetAnchorEvent read FOnSetAnchorPriv write FOnSetAnchorPriv;
    property OnSetGravity: TSetGravityEvent read FOnSetGravityPriv write FOnSetGravityPriv;
    property OnSetConstraintAdjustment: TSetConstraintAdjustmentEvent read FOnSetConstraintAdjustmentPriv write FOnSetConstraintAdjustmentPriv;
    property OnSetOffset: TSetOffsetEvent read FOnSetOffsetPriv write FOnSetOffsetPriv;
  private
    FListeners: array of IXdgPositionerV6Requests;
  public
    function AddListener(AIntf: IXdgPositionerV6Requests): LongInt;
  end;

  IXdgPositionerV6Requests = interface
  ['IXdgPositionerV6Requests']
    procedure xdg_positioner_v6_destroy(AXdgPositionerV6: TXdgPositionerV6);
    procedure xdg_positioner_v6_set_size(AXdgPositionerV6: TXdgPositionerV6; aWidth: Integer; aHeight: Integer);
    procedure xdg_positioner_v6_set_anchor_rect(AXdgPositionerV6: TXdgPositionerV6; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure xdg_positioner_v6_set_anchor(AXdgPositionerV6: TXdgPositionerV6; aAnchor: TXdgPositionerV6.TAnchor);
    procedure xdg_positioner_v6_set_gravity(AXdgPositionerV6: TXdgPositionerV6; aGravity: TXdgPositionerV6.TGravity);
    procedure xdg_positioner_v6_set_constraint_adjustment(AXdgPositionerV6: TXdgPositionerV6; aConstraintAdjustment: DWord);
    procedure xdg_positioner_v6_set_offset(AXdgPositionerV6: TXdgPositionerV6; aX: Integer; aY: Integer);
  end;

  IXdgSurfaceV6Requests = interface;

  [TWLIntfAttribute('destroy(),get_toplevel(n),get_popup(noo),set_window_geometry(iiii),ack_configure(u)', 'configure(u)')]
  { TXdgSurfaceV6 }
  TXdgSurfaceV6 = class(TWaylandServerResource)
  public type
    TError = (erNotconstructed = 1, erAlreadyconstructed = 2, erUnconfiguredbuffer = 3);
    TDestroyEvent = procedure(Sender: TXdgSurfaceV6) of object;
    TGetToplevelEvent = procedure(Sender: TXdgSurfaceV6; aId: TXdgToplevelV6) of object;
    TGetPopupEvent = procedure(Sender: TXdgSurfaceV6; aId: TXdgPopupV6; aParent: TXdgSurfaceV6; aPositioner: TXdgPositionerV6) of object;
    TSetWindowGeometryEvent = procedure(Sender: TXdgSurfaceV6; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer) of object;
    TAckConfigureEvent = procedure(Sender: TXdgSurfaceV6; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_TOPLEVEL = 1, _GET_POPUP = 2, _SET_WINDOW_GEOMETRY = 3, _ACK_CONFIGURE = 4);
    TEvents = (EV_CONFIGURE = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetToplevelPriv: TGetToplevelEvent;
    FOnGetPopupPriv: TGetPopupEvent;
    FOnSetWindowGeometryPriv: TSetWindowGeometryEvent;
    FOnAckConfigurePriv: TAckConfigureEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetToplevel(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_TOPLEVEL); virtual;
    procedure HandleGetPopup(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_POPUP); virtual;
    procedure HandleSetWindowGeometry(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_WINDOW_GEOMETRY); virtual;
    procedure HandleAckConfigure(var AMsg: TWaylandEventMessage); message Ord(TRequests._ACK_CONFIGURE); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetToplevel: TGetToplevelEvent read FOnGetToplevelPriv write FOnGetToplevelPriv;
    property OnGetPopup: TGetPopupEvent read FOnGetPopupPriv write FOnGetPopupPriv;
    property OnSetWindowGeometry: TSetWindowGeometryEvent read FOnSetWindowGeometryPriv write FOnSetWindowGeometryPriv;
    property OnAckConfigure: TAckConfigureEvent read FOnAckConfigurePriv write FOnAckConfigurePriv;
  public
    procedure Configure(aSerial: DWord);
  private
    FListeners: array of IXdgSurfaceV6Requests;
  public
    function AddListener(AIntf: IXdgSurfaceV6Requests): LongInt;
  end;

  IXdgSurfaceV6Requests = interface
  ['IXdgSurfaceV6Requests']
    procedure xdg_surface_v6_destroy(AXdgSurfaceV6: TXdgSurfaceV6);
    procedure xdg_surface_v6_get_toplevel(AXdgSurfaceV6: TXdgSurfaceV6; aId: TXdgToplevelV6);
    procedure xdg_surface_v6_get_popup(AXdgSurfaceV6: TXdgSurfaceV6; aId: TXdgPopupV6; aParent: TXdgSurfaceV6; aPositioner: TXdgPositionerV6);
    procedure xdg_surface_v6_set_window_geometry(AXdgSurfaceV6: TXdgSurfaceV6; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure xdg_surface_v6_ack_configure(AXdgSurfaceV6: TXdgSurfaceV6; aSerial: DWord);
  end;

  IXdgToplevelV6Requests = interface;

  [TWLIntfAttribute('destroy(),set_parent(?o),set_title(s),set_app_id(s),show_window_menu(ouii),move(ou),resize(ouu),set_max_size(ii),set_min_size(ii),set_maximized(),unset_maximized(),set_fullscreen(?o),unset_fullscreen(),set_minimized()', 'configure(iia),close()')]
  { TXdgToplevelV6 }
  TXdgToplevelV6 = class(TWaylandServerResource)
  public type
    TResizeEdge = (reNone = 0, reTop = 1, reBottom = 2, reLeft = 4, reTopleft = 5, reBottomleft = 6, reRight = 8, reTopright = 9, reBottomright = 10);
    TState = (stMaximized = 1, stFullscreen = 2, stResizing = 3, stActivated = 4);
    TDestroyEvent = procedure(Sender: TXdgToplevelV6) of object;
    TSetParentEvent = procedure(Sender: TXdgToplevelV6; aParent: TXdgToplevelV6) of object;
    TSetTitleEvent = procedure(Sender: TXdgToplevelV6; aTitle: String) of object;
    TSetAppIdEvent = procedure(Sender: TXdgToplevelV6; aAppId: String) of object;
    TShowWindowMenuEvent = procedure(Sender: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord; aX: Integer; aY: Integer) of object;
    TMoveEvent = procedure(Sender: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord) of object;
    TResizeEvent = procedure(Sender: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord; aEdges: DWord) of object;
    TSetMaxSizeEvent = procedure(Sender: TXdgToplevelV6; aWidth: Integer; aHeight: Integer) of object;
    TSetMinSizeEvent = procedure(Sender: TXdgToplevelV6; aWidth: Integer; aHeight: Integer) of object;
    TSetMaximizedEvent = procedure(Sender: TXdgToplevelV6) of object;
    TUnsetMaximizedEvent = procedure(Sender: TXdgToplevelV6) of object;
    TSetFullscreenEvent = procedure(Sender: TXdgToplevelV6; aOutput: TWlOutput) of object;
    TUnsetFullscreenEvent = procedure(Sender: TXdgToplevelV6) of object;
    TSetMinimizedEvent = procedure(Sender: TXdgToplevelV6) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_PARENT = 1, _SET_TITLE = 2, _SET_APP_ID = 3, _SHOW_WINDOW_MENU = 4, _MOVE = 5, _RESIZE = 6, _SET_MAX_SIZE = 7, _SET_MIN_SIZE = 8, _SET_MAXIMIZED = 9, _UNSET_MAXIMIZED = 10, _SET_FULLSCREEN = 11, _UNSET_FULLSCREEN = 12, _SET_MINIMIZED = 13);
    TEvents = (EV_CONFIGURE = 0, EV_CLOSE = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetParentPriv: TSetParentEvent;
    FOnSetTitlePriv: TSetTitleEvent;
    FOnSetAppIdPriv: TSetAppIdEvent;
    FOnShowWindowMenuPriv: TShowWindowMenuEvent;
    FOnMovePriv: TMoveEvent;
    FOnResizePriv: TResizeEvent;
    FOnSetMaxSizePriv: TSetMaxSizeEvent;
    FOnSetMinSizePriv: TSetMinSizeEvent;
    FOnSetMaximizedPriv: TSetMaximizedEvent;
    FOnUnsetMaximizedPriv: TUnsetMaximizedEvent;
    FOnSetFullscreenPriv: TSetFullscreenEvent;
    FOnUnsetFullscreenPriv: TUnsetFullscreenEvent;
    FOnSetMinimizedPriv: TSetMinimizedEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetParent(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_PARENT); virtual;
    procedure HandleSetTitle(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_TITLE); virtual;
    procedure HandleSetAppId(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_APP_ID); virtual;
    procedure HandleShowWindowMenu(var AMsg: TWaylandEventMessage); message Ord(TRequests._SHOW_WINDOW_MENU); virtual;
    procedure HandleMove(var AMsg: TWaylandEventMessage); message Ord(TRequests._MOVE); virtual;
    procedure HandleResize(var AMsg: TWaylandEventMessage); message Ord(TRequests._RESIZE); virtual;
    procedure HandleSetMaxSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MAX_SIZE); virtual;
    procedure HandleSetMinSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MIN_SIZE); virtual;
    procedure HandleSetMaximized(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MAXIMIZED); virtual;
    procedure HandleUnsetMaximized(var AMsg: TWaylandEventMessage); message Ord(TRequests._UNSET_MAXIMIZED); virtual;
    procedure HandleSetFullscreen(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_FULLSCREEN); virtual;
    procedure HandleUnsetFullscreen(var AMsg: TWaylandEventMessage); message Ord(TRequests._UNSET_FULLSCREEN); virtual;
    procedure HandleSetMinimized(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MINIMIZED); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetParent: TSetParentEvent read FOnSetParentPriv write FOnSetParentPriv;
    property OnSetTitle: TSetTitleEvent read FOnSetTitlePriv write FOnSetTitlePriv;
    property OnSetAppId: TSetAppIdEvent read FOnSetAppIdPriv write FOnSetAppIdPriv;
    property OnShowWindowMenu: TShowWindowMenuEvent read FOnShowWindowMenuPriv write FOnShowWindowMenuPriv;
    property OnMove: TMoveEvent read FOnMovePriv write FOnMovePriv;
    property OnResize: TResizeEvent read FOnResizePriv write FOnResizePriv;
    property OnSetMaxSize: TSetMaxSizeEvent read FOnSetMaxSizePriv write FOnSetMaxSizePriv;
    property OnSetMinSize: TSetMinSizeEvent read FOnSetMinSizePriv write FOnSetMinSizePriv;
    property OnSetMaximized: TSetMaximizedEvent read FOnSetMaximizedPriv write FOnSetMaximizedPriv;
    property OnUnsetMaximized: TUnsetMaximizedEvent read FOnUnsetMaximizedPriv write FOnUnsetMaximizedPriv;
    property OnSetFullscreen: TSetFullscreenEvent read FOnSetFullscreenPriv write FOnSetFullscreenPriv;
    property OnUnsetFullscreen: TUnsetFullscreenEvent read FOnUnsetFullscreenPriv write FOnUnsetFullscreenPriv;
    property OnSetMinimized: TSetMinimizedEvent read FOnSetMinimizedPriv write FOnSetMinimizedPriv;
  public
    procedure Configure(aWidth: Integer; aHeight: Integer; aStates: TBytes);
    procedure Close;
  private
    FListeners: array of IXdgToplevelV6Requests;
  public
    function AddListener(AIntf: IXdgToplevelV6Requests): LongInt;
  end;

  IXdgToplevelV6Requests = interface
  ['IXdgToplevelV6Requests']
    procedure xdg_toplevel_v6_destroy(AXdgToplevelV6: TXdgToplevelV6);
    procedure xdg_toplevel_v6_set_parent(AXdgToplevelV6: TXdgToplevelV6; aParent: TXdgToplevelV6);
    procedure xdg_toplevel_v6_set_title(AXdgToplevelV6: TXdgToplevelV6; aTitle: String);
    procedure xdg_toplevel_v6_set_app_id(AXdgToplevelV6: TXdgToplevelV6; aAppId: String);
    procedure xdg_toplevel_v6_show_window_menu(AXdgToplevelV6: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord; aX: Integer; aY: Integer);
    procedure xdg_toplevel_v6_move(AXdgToplevelV6: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord);
    procedure xdg_toplevel_v6_resize(AXdgToplevelV6: TXdgToplevelV6; aSeat: TWlSeat; aSerial: DWord; aEdges: DWord);
    procedure xdg_toplevel_v6_set_max_size(AXdgToplevelV6: TXdgToplevelV6; aWidth: Integer; aHeight: Integer);
    procedure xdg_toplevel_v6_set_min_size(AXdgToplevelV6: TXdgToplevelV6; aWidth: Integer; aHeight: Integer);
    procedure xdg_toplevel_v6_set_maximized(AXdgToplevelV6: TXdgToplevelV6);
    procedure xdg_toplevel_v6_unset_maximized(AXdgToplevelV6: TXdgToplevelV6);
    procedure xdg_toplevel_v6_set_fullscreen(AXdgToplevelV6: TXdgToplevelV6; aOutput: TWlOutput);
    procedure xdg_toplevel_v6_unset_fullscreen(AXdgToplevelV6: TXdgToplevelV6);
    procedure xdg_toplevel_v6_set_minimized(AXdgToplevelV6: TXdgToplevelV6);
  end;

  IXdgPopupV6Requests = interface;

  [TWLIntfAttribute('destroy(),grab(ou)', 'configure(iiii),popup_done()')]
  { TXdgPopupV6 }
  TXdgPopupV6 = class(TWaylandServerResource)
  public type
    TError = (erInvalidgrab = 0);
    TDestroyEvent = procedure(Sender: TXdgPopupV6) of object;
    TGrabEvent = procedure(Sender: TXdgPopupV6; aSeat: TWlSeat; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GRAB = 1);
    TEvents = (EV_CONFIGURE = 0, EV_POPUP_DONE = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGrabPriv: TGrabEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGrab(var AMsg: TWaylandEventMessage); message Ord(TRequests._GRAB); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGrab: TGrabEvent read FOnGrabPriv write FOnGrabPriv;
  public
    procedure Configure(aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure PopupDone;
  private
    FListeners: array of IXdgPopupV6Requests;
  public
    function AddListener(AIntf: IXdgPopupV6Requests): LongInt;
  end;

  IXdgPopupV6Requests = interface
  ['IXdgPopupV6Requests']
    procedure xdg_popup_v6_destroy(AXdgPopupV6: TXdgPopupV6);
    procedure xdg_popup_v6_grab(AXdgPopupV6: TXdgPopupV6; aSeat: TWlSeat; aSerial: DWord);
  end;

implementation
uses
  wayland_stream;

class function TXdgShellV6.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgShellV6.GetInterfaceName: String;
begin
  Result := 'zxdg_shell_v6';
end;

procedure TXdgShellV6.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_shell_v6_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgShellV6.HandleCreatePositioner(var AMsg: TWaylandEventMessage);
var
  lId: TXdgPositionerV6;
  lListenerIdx: Integer;
begin
  lId := TXdgPositionerV6.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnCreatePositioner) then OnCreatePositioner(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_shell_v6_create_positioner(Self,lId);
  AMsg.SetHandled;
end;

procedure TXdgShellV6.HandleGetXdgSurface(var AMsg: TWaylandEventMessage);
var
  lId: TXdgSurfaceV6;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TXdgSurfaceV6.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetXdgSurface) then OnGetXdgSurface(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_shell_v6_get_xdg_surface(Self,lId,lSurface);
  AMsg.SetHandled;
end;

procedure TXdgShellV6.HandlePong(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnPong) then OnPong(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_shell_v6_pong(Self,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgShellV6.Ping(aSerial: DWord);
begin
  SendEvent(Ord(TEvents.EV_PING), [aSerial]);
end;

function TXdgShellV6.AddListener(AIntf: IXdgShellV6Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgPositionerV6.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgPositionerV6.GetInterfaceName: String;
begin
  Result := 'zxdg_positioner_v6';
end;

procedure TXdgPositionerV6.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetSize) then OnSetSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetAnchorRect(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetAnchorRect) then OnSetAnchorRect(Self,lX,lY,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_anchor_rect(Self,lX,lY,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetAnchor(var AMsg: TWaylandEventMessage);
var
  lAnchor: TAnchor;
  lListenerIdx: Integer;
begin
  lAnchor := TAnchor(AMsg.Args.ReadDWord);
  if Assigned(OnSetAnchor) then OnSetAnchor(Self,lAnchor);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_anchor(Self,lAnchor);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetGravity(var AMsg: TWaylandEventMessage);
var
  lGravity: TGravity;
  lListenerIdx: Integer;
begin
  lGravity := TGravity(AMsg.Args.ReadDWord);
  if Assigned(OnSetGravity) then OnSetGravity(Self,lGravity);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_gravity(Self,lGravity);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetConstraintAdjustment(var AMsg: TWaylandEventMessage);
var
  lConstraintAdjustment: DWord;
  lListenerIdx: Integer;
begin
  lConstraintAdjustment := AMsg.Args.ReadDWord;
  if Assigned(OnSetConstraintAdjustment) then OnSetConstraintAdjustment(Self,lConstraintAdjustment);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_constraint_adjustment(Self,lConstraintAdjustment);
  AMsg.SetHandled;
end;

procedure TXdgPositionerV6.HandleSetOffset(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  if Assigned(OnSetOffset) then OnSetOffset(Self,lX,lY);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_v6_set_offset(Self,lX,lY);
  AMsg.SetHandled;
end;

function TXdgPositionerV6.AddListener(AIntf: IXdgPositionerV6Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgSurfaceV6.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgSurfaceV6.GetInterfaceName: String;
begin
  Result := 'zxdg_surface_v6';
end;

procedure TXdgSurfaceV6.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_v6_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgSurfaceV6.HandleGetToplevel(var AMsg: TWaylandEventMessage);
var
  lId: TXdgToplevelV6;
  lListenerIdx: Integer;
begin
  lId := TXdgToplevelV6.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnGetToplevel) then OnGetToplevel(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_v6_get_toplevel(Self,lId);
  AMsg.SetHandled;
end;

procedure TXdgSurfaceV6.HandleGetPopup(var AMsg: TWaylandEventMessage);
var
  lId: TXdgPopupV6;
  lParent: TXdgSurfaceV6;
  lPositioner: TXdgPositionerV6;
  lListenerIdx: Integer;
begin
  lId := TXdgPopupV6.Create(Client, AMsg.Args.ReadDWord, Version);
  lParent := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgSurfaceV6);
  lPositioner := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgPositionerV6);
  if Assigned(OnGetPopup) then OnGetPopup(Self,lId,lParent,lPositioner);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_v6_get_popup(Self,lId,lParent,lPositioner);
  AMsg.SetHandled;
end;

procedure TXdgSurfaceV6.HandleSetWindowGeometry(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetWindowGeometry) then OnSetWindowGeometry(Self,lX,lY,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_v6_set_window_geometry(Self,lX,lY,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgSurfaceV6.HandleAckConfigure(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnAckConfigure) then OnAckConfigure(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_v6_ack_configure(Self,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgSurfaceV6.Configure(aSerial: DWord);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aSerial]);
end;

function TXdgSurfaceV6.AddListener(AIntf: IXdgSurfaceV6Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgToplevelV6.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgToplevelV6.GetInterfaceName: String;
begin
  Result := 'zxdg_toplevel_v6';
end;

procedure TXdgToplevelV6.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetParent(var AMsg: TWaylandEventMessage);
var
  lParent: TXdgToplevelV6;
  lListenerIdx: Integer;
begin
  lParent := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgToplevelV6);
  if Assigned(OnSetParent) then OnSetParent(Self,lParent);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_parent(Self,lParent);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetTitle(var AMsg: TWaylandEventMessage);
var
  lTitle: String;
  lListenerIdx: Integer;
begin
  lTitle := AMsg.Args.ReadString;
  if Assigned(OnSetTitle) then OnSetTitle(Self,lTitle);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_title(Self,lTitle);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetAppId(var AMsg: TWaylandEventMessage);
var
  lAppId: String;
  lListenerIdx: Integer;
begin
  lAppId := AMsg.Args.ReadString;
  if Assigned(OnSetAppId) then OnSetAppId(Self,lAppId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_app_id(Self,lAppId);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleShowWindowMenu(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lX: Integer;
  lY: Integer;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  if Assigned(OnShowWindowMenu) then OnShowWindowMenu(Self,lSeat,lSerial,lX,lY);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_show_window_menu(Self,lSeat,lSerial,lX,lY);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleMove(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnMove) then OnMove(Self,lSeat,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_move(Self,lSeat,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleResize(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lEdges: DWord;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  lEdges := AMsg.Args.ReadDWord;
  if Assigned(OnResize) then OnResize(Self,lSeat,lSerial,lEdges);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_resize(Self,lSeat,lSerial,lEdges);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetMaxSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetMaxSize) then OnSetMaxSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_max_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetMinSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetMinSize) then OnSetMinSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_min_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetMaximized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnSetMaximized) then OnSetMaximized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_maximized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleUnsetMaximized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnUnsetMaximized) then OnUnsetMaximized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_unset_maximized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetFullscreen(var AMsg: TWaylandEventMessage);
var
  lOutput: TWlOutput;
  lListenerIdx: Integer;
begin
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  if Assigned(OnSetFullscreen) then OnSetFullscreen(Self,lOutput);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_fullscreen(Self,lOutput);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleUnsetFullscreen(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnUnsetFullscreen) then OnUnsetFullscreen(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_unset_fullscreen(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.HandleSetMinimized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnSetMinimized) then OnSetMinimized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_v6_set_minimized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevelV6.Configure(aWidth: Integer; aHeight: Integer; aStates: TBytes);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aWidth,aHeight,Length(aStates),Pointer(aStates)]);
end;

procedure TXdgToplevelV6.Close;
begin
  SendEvent(Ord(TEvents.EV_CLOSE), []);
end;

function TXdgToplevelV6.AddListener(AIntf: IXdgToplevelV6Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgPopupV6.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgPopupV6.GetInterfaceName: String;
begin
  Result := 'zxdg_popup_v6';
end;

procedure TXdgPopupV6.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_popup_v6_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgPopupV6.HandleGrab(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnGrab) then OnGrab(Self,lSeat,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_popup_v6_grab(Self,lSeat,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgPopupV6.Configure(aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aX,aY,aWidth,aHeight]);
end;

procedure TXdgPopupV6.PopupDone;
begin
  SendEvent(Ord(TEvents.EV_POPUP_DONE), []);
end;

function TXdgPopupV6.AddListener(AIntf: IXdgPopupV6Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('zxdg_shell_v6', TXdgShellV6);
  RegisterServerInterface('zxdg_positioner_v6', TXdgPositionerV6);
  RegisterServerInterface('zxdg_surface_v6', TXdgSurfaceV6);
  RegisterServerInterface('zxdg_toplevel_v6', TXdgToplevelV6);
  RegisterServerInterface('zxdg_popup_v6', TXdgPopupV6);

end.