// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_foreign_unstable_v2_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TXdgImportedV2Class = class of TXdgImportedV2;
  { TXdgImportedV2 }
  TXdgImportedV2 = class;

  TXdgImporterV2Class = class of TXdgImporterV2;
  { TXdgImporterV2 }
  TXdgImporterV2 = class;

  TXdgExportedV2Class = class of TXdgExportedV2;
  { TXdgExportedV2 }
  TXdgExportedV2 = class;

  TXdgExporterV2Class = class of TXdgExporterV2;
  { TXdgExporterV2 }
  TXdgExporterV2 = class;

  IXdgExporterV2Requests = interface;

  [TWLIntfAttribute('destroy(),export_toplevel(no)', '')]
  { TXdgExporterV2 }
  TXdgExporterV2 = class(TWaylandServerResource)
  public type
    TError = (erInvalidsurface = 0);
    TDestroyEvent = procedure(Sender: TXdgExporterV2) of object;
    TExportToplevelEvent = procedure(Sender: TXdgExporterV2; aId: TXdgExportedV2; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _EXPORT_TOPLEVEL = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnExportToplevelPriv: TExportToplevelEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleExportToplevel(var AMsg: TWaylandEventMessage); message Ord(TRequests._EXPORT_TOPLEVEL); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnExportToplevel: TExportToplevelEvent read FOnExportToplevelPriv write FOnExportToplevelPriv;
  private
    FListeners: array of IXdgExporterV2Requests;
  public
    function AddListener(AIntf: IXdgExporterV2Requests): LongInt;
  end;

  IXdgExporterV2Requests = interface
  ['IXdgExporterV2Requests']
    procedure xdg_exporter_v2_destroy(AXdgExporterV2: TXdgExporterV2);
    procedure xdg_exporter_v2_export_toplevel(AXdgExporterV2: TXdgExporterV2; aId: TXdgExportedV2; aSurface: TWlSurface);
  end;

  IXdgImporterV2Requests = interface;

  [TWLIntfAttribute('destroy(),import_toplevel(ns)', '')]
  { TXdgImporterV2 }
  TXdgImporterV2 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgImporterV2) of object;
    TImportToplevelEvent = procedure(Sender: TXdgImporterV2; aId: TXdgImportedV2; aHandle: String) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _IMPORT_TOPLEVEL = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnImportToplevelPriv: TImportToplevelEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleImportToplevel(var AMsg: TWaylandEventMessage); message Ord(TRequests._IMPORT_TOPLEVEL); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnImportToplevel: TImportToplevelEvent read FOnImportToplevelPriv write FOnImportToplevelPriv;
  private
    FListeners: array of IXdgImporterV2Requests;
  public
    function AddListener(AIntf: IXdgImporterV2Requests): LongInt;
  end;

  IXdgImporterV2Requests = interface
  ['IXdgImporterV2Requests']
    procedure xdg_importer_v2_destroy(AXdgImporterV2: TXdgImporterV2);
    procedure xdg_importer_v2_import_toplevel(AXdgImporterV2: TXdgImporterV2; aId: TXdgImportedV2; aHandle: String);
  end;

  IXdgExportedV2Requests = interface;

  [TWLIntfAttribute('destroy()', 'handle(s)')]
  { TXdgExportedV2 }
  TXdgExportedV2 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TXdgExportedV2) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0);
    TEvents = (EV_HANDLE = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  public
    procedure Handle(aHandle: String);
  private
    FListeners: array of IXdgExportedV2Requests;
  public
    function AddListener(AIntf: IXdgExportedV2Requests): LongInt;
  end;

  IXdgExportedV2Requests = interface
  ['IXdgExportedV2Requests']
    procedure xdg_exported_v2_destroy(AXdgExportedV2: TXdgExportedV2);
  end;

  IXdgImportedV2Requests = interface;

  [TWLIntfAttribute('destroy(),set_parent_of(o)', 'destroyed()')]
  { TXdgImportedV2 }
  TXdgImportedV2 = class(TWaylandServerResource)
  public type
    TError = (erInvalidsurface = 0);
    TDestroyEvent = procedure(Sender: TXdgImportedV2) of object;
    TSetParentOfEvent = procedure(Sender: TXdgImportedV2; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_PARENT_OF = 1);
    TEvents = (EV_DESTROYED = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetParentOfPriv: TSetParentOfEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetParentOf(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_PARENT_OF); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetParentOf: TSetParentOfEvent read FOnSetParentOfPriv write FOnSetParentOfPriv;
  public
    procedure Destroyed;
  private
    FListeners: array of IXdgImportedV2Requests;
  public
    function AddListener(AIntf: IXdgImportedV2Requests): LongInt;
  end;

  IXdgImportedV2Requests = interface
  ['IXdgImportedV2Requests']
    procedure xdg_imported_v2_destroy(AXdgImportedV2: TXdgImportedV2);
    procedure xdg_imported_v2_set_parent_of(AXdgImportedV2: TXdgImportedV2; aSurface: TWlSurface);
  end;

implementation
uses
  wayland_stream;

class function TXdgExporterV2.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgExporterV2.GetInterfaceName: String;
begin
  Result := 'zxdg_exporter_v2';
end;

procedure TXdgExporterV2.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_exporter_v2_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgExporterV2.HandleExportToplevel(var AMsg: TWaylandEventMessage);
var
  lId: TXdgExportedV2;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TXdgExportedV2.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnExportToplevel) then OnExportToplevel(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_exporter_v2_export_toplevel(Self,lId,lSurface);
  AMsg.SetHandled;
end;

function TXdgExporterV2.AddListener(AIntf: IXdgExporterV2Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgImporterV2.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgImporterV2.GetInterfaceName: String;
begin
  Result := 'zxdg_importer_v2';
end;

procedure TXdgImporterV2.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_importer_v2_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgImporterV2.HandleImportToplevel(var AMsg: TWaylandEventMessage);
var
  lId: TXdgImportedV2;
  lHandle: String;
  lListenerIdx: Integer;
begin
  lId := TXdgImportedV2.Create(Client, AMsg.Args.ReadDWord, Version);
  lHandle := AMsg.Args.ReadString;
  if Assigned(OnImportToplevel) then OnImportToplevel(Self,lId,lHandle);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_importer_v2_import_toplevel(Self,lId,lHandle);
  AMsg.SetHandled;
end;

function TXdgImporterV2.AddListener(AIntf: IXdgImporterV2Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgExportedV2.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgExportedV2.GetInterfaceName: String;
begin
  Result := 'zxdg_exported_v2';
end;

procedure TXdgExportedV2.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_exported_v2_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgExportedV2.Handle(aHandle: String);
begin
  SendEvent(Ord(TEvents.EV_HANDLE), [aHandle]);
end;

function TXdgExportedV2.AddListener(AIntf: IXdgExportedV2Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgImportedV2.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TXdgImportedV2.GetInterfaceName: String;
begin
  Result := 'zxdg_imported_v2';
end;

procedure TXdgImportedV2.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_imported_v2_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgImportedV2.HandleSetParentOf(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnSetParentOf) then OnSetParentOf(Self,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_imported_v2_set_parent_of(Self,lSurface);
  AMsg.SetHandled;
end;

procedure TXdgImportedV2.Destroyed;
begin
  SendEvent(Ord(TEvents.EV_DESTROYED), []);
end;

function TXdgImportedV2.AddListener(AIntf: IXdgImportedV2Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.