// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit linux_dmabuf_v1_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpLinuxDmabufFeedbackV1Class = class of TWpLinuxDmabufFeedbackV1;
  { TWpLinuxDmabufFeedbackV1 }
  TWpLinuxDmabufFeedbackV1 = class;

  TWpLinuxBufferParamsV1Class = class of TWpLinuxBufferParamsV1;
  { TWpLinuxBufferParamsV1 }
  TWpLinuxBufferParamsV1 = class;

  TWpLinuxDmabufV1Class = class of TWpLinuxDmabufV1;
  { TWpLinuxDmabufV1 }
  TWpLinuxDmabufV1 = class;

  IWpLinuxDmabufV1Requests = interface;

  [TWLIntfAttribute('destroy(),create_params(n),get_default_feedback(n),get_surface_feedback(no)', 'format(u),modifier(uuu)')]
  { TWpLinuxDmabufV1 }
  TWpLinuxDmabufV1 = class(TWaylandServerResource)
  public type
    TDestroyEvent = procedure(Sender: TWpLinuxDmabufV1) of object;
    TCreateParamsEvent = procedure(Sender: TWpLinuxDmabufV1; aParamsId: TWpLinuxBufferParamsV1) of object;
    TGetDefaultFeedbackEvent = procedure(Sender: TWpLinuxDmabufV1; aId: TWpLinuxDmabufFeedbackV1) of object;
    TGetSurfaceFeedbackEvent = procedure(Sender: TWpLinuxDmabufV1; aId: TWpLinuxDmabufFeedbackV1; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_PARAMS = 1, _GET_DEFAULT_FEEDBACK = 2, _GET_SURFACE_FEEDBACK = 3);
    TEvents = (EV_FORMAT = 0, EV_MODIFIER = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreateParamsPriv: TCreateParamsEvent;
    FOnGetDefaultFeedbackPriv: TGetDefaultFeedbackEvent;
    FOnGetSurfaceFeedbackPriv: TGetSurfaceFeedbackEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreateParams(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_PARAMS); virtual;
    procedure HandleGetDefaultFeedback(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_DEFAULT_FEEDBACK); virtual;
    procedure HandleGetSurfaceFeedback(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_SURFACE_FEEDBACK); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreateParams: TCreateParamsEvent read FOnCreateParamsPriv write FOnCreateParamsPriv;
    property OnGetDefaultFeedback: TGetDefaultFeedbackEvent read FOnGetDefaultFeedbackPriv write FOnGetDefaultFeedbackPriv;
    property OnGetSurfaceFeedback: TGetSurfaceFeedbackEvent read FOnGetSurfaceFeedbackPriv write FOnGetSurfaceFeedbackPriv;
  public
    procedure Format(aFormat: DWord);
    procedure Modifier(aFormat: DWord; aModifierHi: DWord; aModifierLo: DWord);
  private
    FListeners: array of IWpLinuxDmabufV1Requests;
  public
    function AddListener(AIntf: IWpLinuxDmabufV1Requests): LongInt;
  end;

  IWpLinuxDmabufV1Requests = interface
  ['IWpLinuxDmabufV1Requests']
    procedure wp_linux_dmabuf_v1_destroy(AWpLinuxDmabufV1: TWpLinuxDmabufV1);
    procedure wp_linux_dmabuf_v1_create_params(AWpLinuxDmabufV1: TWpLinuxDmabufV1; aParamsId: TWpLinuxBufferParamsV1);
    procedure wp_linux_dmabuf_v1_get_default_feedback(AWpLinuxDmabufV1: TWpLinuxDmabufV1; aId: TWpLinuxDmabufFeedbackV1);
    procedure wp_linux_dmabuf_v1_get_surface_feedback(AWpLinuxDmabufV1: TWpLinuxDmabufV1; aId: TWpLinuxDmabufFeedbackV1; aSurface: TWlSurface);
  end;

  IWpLinuxBufferParamsV1Requests = interface;

  [TWLIntfAttribute('destroy(),add(huuuuu),create(iiuu),create_immed(niiuu)', 'created(n),failed()')]
  { TWpLinuxBufferParamsV1 }
  TWpLinuxBufferParamsV1 = class(TWaylandServerResource)
  public type
    TError = (erAlreadyused = 0, erPlaneidx = 1, erPlaneset = 2, erIncomplete = 3, erInvalidformat = 4, erInvaliddimensions = 5, erOutofbounds = 6, erInvalidwlbuffer = 7);
    { TWpLinuxBufferParamsV1.TFlags }
    TFlags = object(TBitfield)
    public
      property YInvert: Boolean  index 1 read GetValue write SetValue;
      property Interlaced: Boolean  index 2 read GetValue write SetValue;
      property BottomFirst: Boolean  index 4 read GetValue write SetValue;
    end;

    TDestroyEvent = procedure(Sender: TWpLinuxBufferParamsV1) of object;
    TAddEvent = procedure(Sender: TWpLinuxBufferParamsV1; aFd: TWaylandFdStream; aPlaneIdx: DWord; aOffset: DWord; aStride: DWord; aModifierHi: DWord; aModifierLo: DWord) of object;
    TCreateEvent = procedure(Sender: TWpLinuxBufferParamsV1; aWidth: Integer; aHeight: Integer; aFormat: DWord; aFlags: TFlags) of object;
    TCreateImmedEvent = procedure(Sender: TWpLinuxBufferParamsV1; aBufferId: TWlBuffer; aWidth: Integer; aHeight: Integer; aFormat: DWord; aFlags: TFlags) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _ADD = 1, _CREATE = 2, _CREATE_IMMED = 3);
    TEvents = (EV_CREATED = 0, EV_FAILED = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnAddPriv: TAddEvent;
    FOnCreatePriv: TCreateEvent;
    FOnCreateImmedPriv: TCreateImmedEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleAdd(var AMsg: TWaylandEventMessage); message Ord(TRequests._ADD); virtual;
    procedure HandleCreate(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE); virtual;
    procedure HandleCreateImmed(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_IMMED); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnAdd: TAddEvent read FOnAddPriv write FOnAddPriv;
    property OnCreate: TCreateEvent read FOnCreatePriv write FOnCreatePriv;
    property OnCreateImmed: TCreateImmedEvent read FOnCreateImmedPriv write FOnCreateImmedPriv;
  public
    function Created(aClassType: TWlBufferClass = nil): TWlBuffer;
    procedure Failed;
  private
    FListeners: array of IWpLinuxBufferParamsV1Requests;
  public
    function AddListener(AIntf: IWpLinuxBufferParamsV1Requests): LongInt;
  end;

  IWpLinuxBufferParamsV1Requests = interface
  ['IWpLinuxBufferParamsV1Requests']
    procedure wp_linux_buffer_params_v1_destroy(AWpLinuxBufferParamsV1: TWpLinuxBufferParamsV1);
    procedure wp_linux_buffer_params_v1_add(AWpLinuxBufferParamsV1: TWpLinuxBufferParamsV1; aFd: TWaylandFdStream; aPlaneIdx: DWord; aOffset: DWord; aStride: DWord; aModifierHi: DWord; aModifierLo: DWord);
    procedure wp_linux_buffer_params_v1_create(AWpLinuxBufferParamsV1: TWpLinuxBufferParamsV1; aWidth: Integer; aHeight: Integer; aFormat: DWord; aFlags: TWpLinuxBufferParamsV1.TFlags);
    procedure wp_linux_buffer_params_v1_create_immed(AWpLinuxBufferParamsV1: TWpLinuxBufferParamsV1; aBufferId: TWlBuffer; aWidth: Integer; aHeight: Integer; aFormat: DWord; aFlags: TWpLinuxBufferParamsV1.TFlags);
  end;

  IWpLinuxDmabufFeedbackV1Requests = interface;

  [TWLIntfAttribute('destroy()', 'done(),format_table(hu),main_device(a),tranche_done(),tranche_target_device(a),tranche_formats(a),tranche_flags(u)')]
  { TWpLinuxDmabufFeedbackV1 }
  TWpLinuxDmabufFeedbackV1 = class(TWaylandServerResource)
  public type
    { TWpLinuxDmabufFeedbackV1.TTrancheFlags }
    TTrancheFlags = object(TBitfield)
    public
      property Scanout: Boolean  index 1 read GetValue write SetValue;
    end;

    TDestroyEvent = procedure(Sender: TWpLinuxDmabufFeedbackV1) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0);
    TEvents = (EV_DONE = 0, EV_FORMAT_TABLE = 1, EV_MAIN_DEVICE = 2, EV_TRANCHE_DONE = 3, EV_TRANCHE_TARGET_DEVICE = 4, EV_TRANCHE_FORMATS = 5, EV_TRANCHE_FLAGS = 6);
  private
    FOnDestroyPriv: TDestroyEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
  public
    procedure Done;
    procedure FormatTable(aFd: Integer; aSize: DWord);
    procedure MainDevice(aDevice: TBytes);
    procedure TrancheDone;
    procedure TrancheTargetDevice(aDevice: TBytes);
    procedure TrancheFormats(aIndices: TBytes);
    procedure TrancheFlags(aFlags: TTrancheFlags);
  private
    FListeners: array of IWpLinuxDmabufFeedbackV1Requests;
  public
    function AddListener(AIntf: IWpLinuxDmabufFeedbackV1Requests): LongInt;
  end;

  IWpLinuxDmabufFeedbackV1Requests = interface
  ['IWpLinuxDmabufFeedbackV1Requests']
    procedure wp_linux_dmabuf_feedback_v1_destroy(AWpLinuxDmabufFeedbackV1: TWpLinuxDmabufFeedbackV1);
  end;

implementation
uses
  wayland_stream;

class function TWpLinuxDmabufV1.GetInterfaceVersion: Integer;
begin
  Result := 5;
end;

class function TWpLinuxDmabufV1.GetInterfaceName: String;
begin
  Result := 'zwp_linux_dmabuf_v1';
end;

procedure TWpLinuxDmabufV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_dmabuf_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpLinuxDmabufV1.HandleCreateParams(var AMsg: TWaylandEventMessage);
var
  lParamsId: TWpLinuxBufferParamsV1;
  lListenerIdx: Integer;
begin
  lParamsId := TWpLinuxBufferParamsV1.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnCreateParams) then OnCreateParams(Self,lParamsId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_dmabuf_v1_create_params(Self,lParamsId);
  AMsg.SetHandled;
end;

procedure TWpLinuxDmabufV1.HandleGetDefaultFeedback(var AMsg: TWaylandEventMessage);
var
  lId: TWpLinuxDmabufFeedbackV1;
  lListenerIdx: Integer;
begin
  lId := TWpLinuxDmabufFeedbackV1.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnGetDefaultFeedback) then OnGetDefaultFeedback(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_dmabuf_v1_get_default_feedback(Self,lId);
  AMsg.SetHandled;
end;

procedure TWpLinuxDmabufV1.HandleGetSurfaceFeedback(var AMsg: TWaylandEventMessage);
var
  lId: TWpLinuxDmabufFeedbackV1;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TWpLinuxDmabufFeedbackV1.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetSurfaceFeedback) then OnGetSurfaceFeedback(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_dmabuf_v1_get_surface_feedback(Self,lId,lSurface);
  AMsg.SetHandled;
end;

procedure TWpLinuxDmabufV1.Format(aFormat: DWord);
begin
  SendEvent(Ord(TEvents.EV_FORMAT), [aFormat]);
end;

procedure TWpLinuxDmabufV1.Modifier(aFormat: DWord; aModifierHi: DWord; aModifierLo: DWord);
begin
  SendEvent(Ord(TEvents.EV_MODIFIER), [aFormat,aModifierHi,aModifierLo]);
end;

function TWpLinuxDmabufV1.AddListener(AIntf: IWpLinuxDmabufV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpLinuxBufferParamsV1.GetInterfaceVersion: Integer;
begin
  Result := 5;
end;

class function TWpLinuxBufferParamsV1.GetInterfaceName: String;
begin
  Result := 'zwp_linux_buffer_params_v1';
end;

procedure TWpLinuxBufferParamsV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_buffer_params_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpLinuxBufferParamsV1.HandleAdd(var AMsg: TWaylandEventMessage);
var
  lFd: TWaylandFdStream;
  lPlaneIdx: DWord;
  lOffset: DWord;
  lStride: DWord;
  lModifierHi: DWord;
  lModifierLo: DWord;
  lListenerIdx: Integer;
begin
  lFd := AMsg.NextFdStream;
  lPlaneIdx := AMsg.Args.ReadDWord;
  lOffset := AMsg.Args.ReadDWord;
  lStride := AMsg.Args.ReadDWord;
  lModifierHi := AMsg.Args.ReadDWord;
  lModifierLo := AMsg.Args.ReadDWord;
  if Assigned(OnAdd) then OnAdd(Self,lFd,lPlaneIdx,lOffset,lStride,lModifierHi,lModifierLo);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_buffer_params_v1_add(Self,lFd,lPlaneIdx,lOffset,lStride,lModifierHi,lModifierLo);
  AMsg.SetHandled;
end;

procedure TWpLinuxBufferParamsV1.HandleCreate(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lFormat: DWord;
  lFlags: TFlags;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  lFormat := AMsg.Args.ReadDWord;
  lFlags := TFlags(AMsg.Args.ReadDWord);
  if Assigned(OnCreate) then OnCreate(Self,lWidth,lHeight,lFormat,lFlags);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_buffer_params_v1_create(Self,lWidth,lHeight,lFormat,lFlags);
  AMsg.SetHandled;
end;

procedure TWpLinuxBufferParamsV1.HandleCreateImmed(var AMsg: TWaylandEventMessage);
var
  lBufferId: TWlBuffer;
  lWidth: Integer;
  lHeight: Integer;
  lFormat: DWord;
  lFlags: TFlags;
  lListenerIdx: Integer;
begin
  lBufferId := TWlBuffer.Create(Client, AMsg.Args.ReadDWord, Version);
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  lFormat := AMsg.Args.ReadDWord;
  lFlags := TFlags(AMsg.Args.ReadDWord);
  if Assigned(OnCreateImmed) then OnCreateImmed(Self,lBufferId,lWidth,lHeight,lFormat,lFlags);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_buffer_params_v1_create_immed(Self,lBufferId,lWidth,lHeight,lFormat,lFlags);
  AMsg.SetHandled;
end;

function TWpLinuxBufferParamsV1.Created(aClassType: TWlBufferClass = nil): TWlBuffer;
begin
  if aClassType = nil then aClassType := TWlBuffer;
  Result := TWlBuffer(NewResource(aClassType, Version));
  SendEvent(Ord(TEvents.EV_CREATED), [Integer(Result.GetObjectId)]);
end;

procedure TWpLinuxBufferParamsV1.Failed;
begin
  SendEvent(Ord(TEvents.EV_FAILED), []);
end;

function TWpLinuxBufferParamsV1.AddListener(AIntf: IWpLinuxBufferParamsV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpLinuxDmabufFeedbackV1.GetInterfaceVersion: Integer;
begin
  Result := 5;
end;

class function TWpLinuxDmabufFeedbackV1.GetInterfaceName: String;
begin
  Result := 'zwp_linux_dmabuf_feedback_v1';
end;

procedure TWpLinuxDmabufFeedbackV1.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_linux_dmabuf_feedback_v1_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpLinuxDmabufFeedbackV1.Done;
begin
  SendEvent(Ord(TEvents.EV_DONE), []);
end;

procedure TWpLinuxDmabufFeedbackV1.FormatTable(aFd: Integer; aSize: DWord);
begin
  SendEvent(Ord(TEvents.EV_FORMAT_TABLE), [aFd,aSize], 0);
end;

procedure TWpLinuxDmabufFeedbackV1.MainDevice(aDevice: TBytes);
begin
  SendEvent(Ord(TEvents.EV_MAIN_DEVICE), [Length(aDevice),Pointer(aDevice)]);
end;

procedure TWpLinuxDmabufFeedbackV1.TrancheDone;
begin
  SendEvent(Ord(TEvents.EV_TRANCHE_DONE), []);
end;

procedure TWpLinuxDmabufFeedbackV1.TrancheTargetDevice(aDevice: TBytes);
begin
  SendEvent(Ord(TEvents.EV_TRANCHE_TARGET_DEVICE), [Length(aDevice),Pointer(aDevice)]);
end;

procedure TWpLinuxDmabufFeedbackV1.TrancheFormats(aIndices: TBytes);
begin
  SendEvent(Ord(TEvents.EV_TRANCHE_FORMATS), [Length(aIndices),Pointer(aIndices)]);
end;

procedure TWpLinuxDmabufFeedbackV1.TrancheFlags(aFlags: TTrancheFlags);
begin
  SendEvent(Ord(TEvents.EV_TRANCHE_FLAGS), [DWord(aFlags)]);
end;

function TWpLinuxDmabufFeedbackV1.AddListener(AIntf: IWpLinuxDmabufFeedbackV1Requests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.