// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit presentation_time_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpPresentationFeedbackClass = class of TWpPresentationFeedback;
  { TWpPresentationFeedback }
  TWpPresentationFeedback = class;

  TWpPresentationClass = class of TWpPresentation;
  { TWpPresentation }
  TWpPresentation = class;

  IWpPresentationRequests = interface;

  [TWLIntfAttribute('destroy(),feedback(on)', 'clock_id(u)')]
  { TWpPresentation }
  TWpPresentation = class(TWaylandServerResource)
  public type
    TError = (erInvalidtimestamp = 0, erInvalidflag = 1);
    TDestroyEvent = procedure(Sender: TWpPresentation) of object;
    TFeedbackEvent = procedure(Sender: TWpPresentation; aSurface: TWlSurface; aCallback: TWpPresentationFeedback) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _FEEDBACK = 1);
    TEvents = (EV_CLOCK_ID = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnFeedbackPriv: TFeedbackEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleFeedback(var AMsg: TWaylandEventMessage); message Ord(TRequests._FEEDBACK); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnFeedback: TFeedbackEvent read FOnFeedbackPriv write FOnFeedbackPriv;
  public
    procedure ClockId(aClkId: DWord);
  private
    FListeners: array of IWpPresentationRequests;
  public
    function AddListener(AIntf: IWpPresentationRequests): LongInt;
  end;

  IWpPresentationRequests = interface
  ['IWpPresentationRequests']
    procedure wp_presentation_destroy(AWpPresentation: TWpPresentation);
    procedure wp_presentation_feedback(AWpPresentation: TWpPresentation; aSurface: TWlSurface; aCallback: TWpPresentationFeedback);
  end;

  IWpPresentationFeedbackRequests = interface;

  [TWLIntfAttribute('', 'sync_output(o),presented(uuuuuuu),discarded()')]
  { TWpPresentationFeedback }
  TWpPresentationFeedback = class(TWaylandServerResource)
  public type
    { TWpPresentationFeedback.TKind }
    TKind = object(TBitfield)
    public
      property Vsync: Boolean  index 1 read GetValue write SetValue;
      property HwClock: Boolean  index 2 read GetValue write SetValue;
      property HwCompletion: Boolean  index 4 read GetValue write SetValue;
      property ZeroCopy: Boolean  index 8 read GetValue write SetValue;
    end;

  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TEvents = (EV_SYNC_OUTPUT = 0, EV_PRESENTED = 1, EV_DISCARDED = 2);
  public
    procedure SyncOutput(aOutput: TWlOutput);
    procedure Presented(aTvSecHi: DWord; aTvSecLo: DWord; aTvNsec: DWord; aRefresh: DWord; aSeqHi: DWord; aSeqLo: DWord; aFlags: TKind);
    procedure Discarded;
  private
    FListeners: array of IWpPresentationFeedbackRequests;
  public
    function AddListener(AIntf: IWpPresentationFeedbackRequests): LongInt;
  end;

  IWpPresentationFeedbackRequests = interface
  ['IWpPresentationFeedbackRequests']
  end;

implementation
uses
  wayland_stream;

class function TWpPresentation.GetInterfaceVersion: Integer;
begin
  Result := 2;
end;

class function TWpPresentation.GetInterfaceName: String;
begin
  Result := 'wp_presentation';
end;

procedure TWpPresentation.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_presentation_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpPresentation.HandleFeedback(var AMsg: TWaylandEventMessage);
var
  lSurface: TWlSurface;
  lCallback: TWpPresentationFeedback;
  lListenerIdx: Integer;
begin
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  lCallback := TWpPresentationFeedback.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnFeedback) then OnFeedback(Self,lSurface,lCallback);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_presentation_feedback(Self,lSurface,lCallback);
  AMsg.SetHandled;
end;

procedure TWpPresentation.ClockId(aClkId: DWord);
begin
  SendEvent(Ord(TEvents.EV_CLOCK_ID), [aClkId]);
end;

function TWpPresentation.AddListener(AIntf: IWpPresentationRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpPresentationFeedback.GetInterfaceVersion: Integer;
begin
  Result := 2;
end;

class function TWpPresentationFeedback.GetInterfaceName: String;
begin
  Result := 'wp_presentation_feedback';
end;

procedure TWpPresentationFeedback.SyncOutput(aOutput: TWlOutput);
begin
  SendEvent(Ord(TEvents.EV_SYNC_OUTPUT), [Integer(aOutput.GetObjectId)]);
end;

procedure TWpPresentationFeedback.Presented(aTvSecHi: DWord; aTvSecLo: DWord; aTvNsec: DWord; aRefresh: DWord; aSeqHi: DWord; aSeqLo: DWord; aFlags: TKind);
begin
  SendEvent(Ord(TEvents.EV_PRESENTED), [aTvSecHi,aTvSecLo,aTvNsec,aRefresh,aSeqHi,aSeqLo,DWord(aFlags)]);
end;

procedure TWpPresentationFeedback.Discarded;
begin
  SendEvent(Ord(TEvents.EV_DISCARDED), []);
end;

function TWpPresentationFeedback.AddListener(AIntf: IWpPresentationFeedbackRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.