// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit viewporter_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TWpViewportClass = class of TWpViewport;
  { TWpViewport }
  TWpViewport = class;

  TWpViewporterClass = class of TWpViewporter;
  { TWpViewporter }
  TWpViewporter = class;

  IWpViewporterRequests = interface;

  [TWLIntfAttribute('destroy(),get_viewport(no)', '')]
  { TWpViewporter }
  TWpViewporter = class(TWaylandServerResource)
  public type
    TError = (erViewportexists = 0);
    TDestroyEvent = procedure(Sender: TWpViewporter) of object;
    TGetViewportEvent = procedure(Sender: TWpViewporter; aId: TWpViewport; aSurface: TWlSurface) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_VIEWPORT = 1);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetViewportPriv: TGetViewportEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetViewport(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_VIEWPORT); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetViewport: TGetViewportEvent read FOnGetViewportPriv write FOnGetViewportPriv;
  private
    FListeners: array of IWpViewporterRequests;
  public
    function AddListener(AIntf: IWpViewporterRequests): LongInt;
  end;

  IWpViewporterRequests = interface
  ['IWpViewporterRequests']
    procedure wp_viewporter_destroy(AWpViewporter: TWpViewporter);
    procedure wp_viewporter_get_viewport(AWpViewporter: TWpViewporter; aId: TWpViewport; aSurface: TWlSurface);
  end;

  IWpViewportRequests = interface;

  [TWLIntfAttribute('destroy(),set_source(ffff),set_destination(ii)', '')]
  { TWpViewport }
  TWpViewport = class(TWaylandServerResource)
  public type
    TError = (erBadvalue = 0, erBadsize = 1, erOutofbuffer = 2, erNosurface = 3);
    TDestroyEvent = procedure(Sender: TWpViewport) of object;
    TSetSourceEvent = procedure(Sender: TWpViewport; aX: TWaylandFixed; aY: TWaylandFixed; aWidth: TWaylandFixed; aHeight: TWaylandFixed) of object;
    TSetDestinationEvent = procedure(Sender: TWpViewport; aWidth: Integer; aHeight: Integer) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_SOURCE = 1, _SET_DESTINATION = 2);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetSourcePriv: TSetSourceEvent;
    FOnSetDestinationPriv: TSetDestinationEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetSource(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_SOURCE); virtual;
    procedure HandleSetDestination(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_DESTINATION); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetSource: TSetSourceEvent read FOnSetSourcePriv write FOnSetSourcePriv;
    property OnSetDestination: TSetDestinationEvent read FOnSetDestinationPriv write FOnSetDestinationPriv;
  private
    FListeners: array of IWpViewportRequests;
  public
    function AddListener(AIntf: IWpViewportRequests): LongInt;
  end;

  IWpViewportRequests = interface
  ['IWpViewportRequests']
    procedure wp_viewport_destroy(AWpViewport: TWpViewport);
    procedure wp_viewport_set_source(AWpViewport: TWpViewport; aX: TWaylandFixed; aY: TWaylandFixed; aWidth: TWaylandFixed; aHeight: TWaylandFixed);
    procedure wp_viewport_set_destination(AWpViewport: TWpViewport; aWidth: Integer; aHeight: Integer);
  end;

implementation
uses
  wayland_stream;

class function TWpViewporter.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpViewporter.GetInterfaceName: String;
begin
  Result := 'wp_viewporter';
end;

procedure TWpViewporter.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_viewporter_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpViewporter.HandleGetViewport(var AMsg: TWaylandEventMessage);
var
  lId: TWpViewport;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TWpViewport.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetViewport) then OnGetViewport(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_viewporter_get_viewport(Self,lId,lSurface);
  AMsg.SetHandled;
end;

function TWpViewporter.AddListener(AIntf: IWpViewporterRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TWpViewport.GetInterfaceVersion: Integer;
begin
  Result := 1;
end;

class function TWpViewport.GetInterfaceName: String;
begin
  Result := 'wp_viewport';
end;

procedure TWpViewport.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_viewport_destroy(Self);
  AMsg.SetHandled;
end;

procedure TWpViewport.HandleSetSource(var AMsg: TWaylandEventMessage);
var
  lX: TWaylandFixed;
  lY: TWaylandFixed;
  lWidth: TWaylandFixed;
  lHeight: TWaylandFixed;
  lListenerIdx: Integer;
begin
  lX := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lY := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lWidth := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  lHeight := TWaylandFixed.FromFixed(AMsg.Args.ReadDWord);
  if Assigned(OnSetSource) then OnSetSource(Self,lX,lY,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_viewport_set_source(Self,lX,lY,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TWpViewport.HandleSetDestination(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetDestination) then OnSetDestination(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].wp_viewport_set_destination(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

function TWpViewport.AddListener(AIntf: IWpViewportRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


end.