// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2026 Andrew Haines <https://github.com/andrewd207>
//
// Generated by wayland-gen — do not edit by hand.

unit xdg_shell_server;

{$mode ObjFPC}{$H+}
{$ScopedEnums on}
{$modeswitch advancedrecords}
{$modeswitch prefixedattributes}
{$interfaces corba}

interface
uses
  Classes, Sysutils, wayland_server_core, wayland_queue, wayland_server;

type
  TXdgPopupClass = class of TXdgPopup;
  { TXdgPopup }
  TXdgPopup = class;

  TXdgToplevelClass = class of TXdgToplevel;
  { TXdgToplevel }
  TXdgToplevel = class;

  TXdgSurfaceClass = class of TXdgSurface;
  { TXdgSurface }
  TXdgSurface = class;

  TXdgPositionerClass = class of TXdgPositioner;
  { TXdgPositioner }
  TXdgPositioner = class;

  TXdgWmBaseClass = class of TXdgWmBase;
  { TXdgWmBase }
  TXdgWmBase = class;

  IXdgWmBaseRequests = interface;

  [TWLIntfAttribute('destroy(),create_positioner(n),get_xdg_surface(no),pong(u)', 'ping(u)')]
  { TXdgWmBase }
  TXdgWmBase = class(TWaylandServerResource)
  public type
    TError = (erRole = 0, erDefunctsurfaces = 1, erNotthetopmostpopup = 2, erInvalidpopupparent = 3, erInvalidsurfacestate = 4, erInvalidpositioner = 5, erUnresponsive = 6);
    TDestroyEvent = procedure(Sender: TXdgWmBase) of object;
    TCreatePositionerEvent = procedure(Sender: TXdgWmBase; aId: TXdgPositioner) of object;
    TGetXdgSurfaceEvent = procedure(Sender: TXdgWmBase; aId: TXdgSurface; aSurface: TWlSurface) of object;
    TPongEvent = procedure(Sender: TXdgWmBase; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _CREATE_POSITIONER = 1, _GET_XDG_SURFACE = 2, _PONG = 3);
    TEvents = (EV_PING = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnCreatePositionerPriv: TCreatePositionerEvent;
    FOnGetXdgSurfacePriv: TGetXdgSurfaceEvent;
    FOnPongPriv: TPongEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleCreatePositioner(var AMsg: TWaylandEventMessage); message Ord(TRequests._CREATE_POSITIONER); virtual;
    procedure HandleGetXdgSurface(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_XDG_SURFACE); virtual;
    procedure HandlePong(var AMsg: TWaylandEventMessage); message Ord(TRequests._PONG); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnCreatePositioner: TCreatePositionerEvent read FOnCreatePositionerPriv write FOnCreatePositionerPriv;
    property OnGetXdgSurface: TGetXdgSurfaceEvent read FOnGetXdgSurfacePriv write FOnGetXdgSurfacePriv;
    property OnPong: TPongEvent read FOnPongPriv write FOnPongPriv;
  public
    procedure Ping(aSerial: DWord);
  private
    FListeners: array of IXdgWmBaseRequests;
  public
    function AddListener(AIntf: IXdgWmBaseRequests): LongInt;
  end;

  IXdgWmBaseRequests = interface
  ['IXdgWmBaseRequests']
    procedure xdg_wm_base_destroy(AXdgWmBase: TXdgWmBase);
    procedure xdg_wm_base_create_positioner(AXdgWmBase: TXdgWmBase; aId: TXdgPositioner);
    procedure xdg_wm_base_get_xdg_surface(AXdgWmBase: TXdgWmBase; aId: TXdgSurface; aSurface: TWlSurface);
    procedure xdg_wm_base_pong(AXdgWmBase: TXdgWmBase; aSerial: DWord);
  end;

  IXdgPositionerRequests = interface;

  [TWLIntfAttribute('destroy(),set_size(ii),set_anchor_rect(iiii),set_anchor(u),set_gravity(u),set_constraint_adjustment(u),set_offset(ii),set_reactive(),set_parent_size(ii),set_parent_configure(u)', '')]
  { TXdgPositioner }
  TXdgPositioner = class(TWaylandServerResource)
  public type
    TError = (erInvalidinput = 0);
    TAnchor = (anNone = 0, anTop = 1, anBottom = 2, anLeft = 3, anRight = 4, anTopleft = 5, anBottomleft = 6, anTopright = 7, anBottomright = 8);
    TGravity = (grNone = 0, grTop = 1, grBottom = 2, grLeft = 3, grRight = 4, grTopleft = 5, grBottomleft = 6, grTopright = 7, grBottomright = 8);
    { TXdgPositioner.TConstraintAdjustment }
    TConstraintAdjustment = object(TBitfield)
    public
      property None: Boolean  index 0 read GetValue write SetValue;
      property SlideX: Boolean  index 1 read GetValue write SetValue;
      property SlideY: Boolean  index 2 read GetValue write SetValue;
      property FlipX: Boolean  index 4 read GetValue write SetValue;
      property FlipY: Boolean  index 8 read GetValue write SetValue;
      property ResizeX: Boolean  index 16 read GetValue write SetValue;
      property ResizeY: Boolean  index 32 read GetValue write SetValue;
    end;

    TDestroyEvent = procedure(Sender: TXdgPositioner) of object;
    TSetSizeEvent = procedure(Sender: TXdgPositioner; aWidth: Integer; aHeight: Integer) of object;
    TSetAnchorRectEvent = procedure(Sender: TXdgPositioner; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer) of object;
    TSetAnchorEvent = procedure(Sender: TXdgPositioner; aAnchor: TAnchor) of object;
    TSetGravityEvent = procedure(Sender: TXdgPositioner; aGravity: TGravity) of object;
    TSetConstraintAdjustmentEvent = procedure(Sender: TXdgPositioner; aConstraintAdjustment: TConstraintAdjustment) of object;
    TSetOffsetEvent = procedure(Sender: TXdgPositioner; aX: Integer; aY: Integer) of object;
    TSetReactiveEvent = procedure(Sender: TXdgPositioner) of object;
    TSetParentSizeEvent = procedure(Sender: TXdgPositioner; aParentWidth: Integer; aParentHeight: Integer) of object;
    TSetParentConfigureEvent = procedure(Sender: TXdgPositioner; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_SIZE = 1, _SET_ANCHOR_RECT = 2, _SET_ANCHOR = 3, _SET_GRAVITY = 4, _SET_CONSTRAINT_ADJUSTMENT = 5, _SET_OFFSET = 6, _SET_REACTIVE = 7, _SET_PARENT_SIZE = 8, _SET_PARENT_CONFIGURE = 9);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetSizePriv: TSetSizeEvent;
    FOnSetAnchorRectPriv: TSetAnchorRectEvent;
    FOnSetAnchorPriv: TSetAnchorEvent;
    FOnSetGravityPriv: TSetGravityEvent;
    FOnSetConstraintAdjustmentPriv: TSetConstraintAdjustmentEvent;
    FOnSetOffsetPriv: TSetOffsetEvent;
    FOnSetReactivePriv: TSetReactiveEvent;
    FOnSetParentSizePriv: TSetParentSizeEvent;
    FOnSetParentConfigurePriv: TSetParentConfigureEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_SIZE); virtual;
    procedure HandleSetAnchorRect(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_ANCHOR_RECT); virtual;
    procedure HandleSetAnchor(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_ANCHOR); virtual;
    procedure HandleSetGravity(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_GRAVITY); virtual;
    procedure HandleSetConstraintAdjustment(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_CONSTRAINT_ADJUSTMENT); virtual;
    procedure HandleSetOffset(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_OFFSET); virtual;
    procedure HandleSetReactive(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_REACTIVE); virtual;
    procedure HandleSetParentSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_PARENT_SIZE); virtual;
    procedure HandleSetParentConfigure(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_PARENT_CONFIGURE); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetSize: TSetSizeEvent read FOnSetSizePriv write FOnSetSizePriv;
    property OnSetAnchorRect: TSetAnchorRectEvent read FOnSetAnchorRectPriv write FOnSetAnchorRectPriv;
    property OnSetAnchor: TSetAnchorEvent read FOnSetAnchorPriv write FOnSetAnchorPriv;
    property OnSetGravity: TSetGravityEvent read FOnSetGravityPriv write FOnSetGravityPriv;
    property OnSetConstraintAdjustment: TSetConstraintAdjustmentEvent read FOnSetConstraintAdjustmentPriv write FOnSetConstraintAdjustmentPriv;
    property OnSetOffset: TSetOffsetEvent read FOnSetOffsetPriv write FOnSetOffsetPriv;
    property OnSetReactive: TSetReactiveEvent read FOnSetReactivePriv write FOnSetReactivePriv;
    property OnSetParentSize: TSetParentSizeEvent read FOnSetParentSizePriv write FOnSetParentSizePriv;
    property OnSetParentConfigure: TSetParentConfigureEvent read FOnSetParentConfigurePriv write FOnSetParentConfigurePriv;
  private
    FListeners: array of IXdgPositionerRequests;
  public
    function AddListener(AIntf: IXdgPositionerRequests): LongInt;
  end;

  IXdgPositionerRequests = interface
  ['IXdgPositionerRequests']
    procedure xdg_positioner_destroy(AXdgPositioner: TXdgPositioner);
    procedure xdg_positioner_set_size(AXdgPositioner: TXdgPositioner; aWidth: Integer; aHeight: Integer);
    procedure xdg_positioner_set_anchor_rect(AXdgPositioner: TXdgPositioner; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure xdg_positioner_set_anchor(AXdgPositioner: TXdgPositioner; aAnchor: TXdgPositioner.TAnchor);
    procedure xdg_positioner_set_gravity(AXdgPositioner: TXdgPositioner; aGravity: TXdgPositioner.TGravity);
    procedure xdg_positioner_set_constraint_adjustment(AXdgPositioner: TXdgPositioner; aConstraintAdjustment: TXdgPositioner.TConstraintAdjustment);
    procedure xdg_positioner_set_offset(AXdgPositioner: TXdgPositioner; aX: Integer; aY: Integer);
    procedure xdg_positioner_set_reactive(AXdgPositioner: TXdgPositioner);
    procedure xdg_positioner_set_parent_size(AXdgPositioner: TXdgPositioner; aParentWidth: Integer; aParentHeight: Integer);
    procedure xdg_positioner_set_parent_configure(AXdgPositioner: TXdgPositioner; aSerial: DWord);
  end;

  IXdgSurfaceRequests = interface;

  [TWLIntfAttribute('destroy(),get_toplevel(n),get_popup(n?oo),set_window_geometry(iiii),ack_configure(u)', 'configure(u)')]
  { TXdgSurface }
  TXdgSurface = class(TWaylandServerResource)
  public type
    TError = (erNotconstructed = 1, erAlreadyconstructed = 2, erUnconfiguredbuffer = 3, erInvalidserial = 4, erInvalidsize = 5, erDefunctroleobject = 6);
    TDestroyEvent = procedure(Sender: TXdgSurface) of object;
    TGetToplevelEvent = procedure(Sender: TXdgSurface; aId: TXdgToplevel) of object;
    TGetPopupEvent = procedure(Sender: TXdgSurface; aId: TXdgPopup; aParent: TXdgSurface; aPositioner: TXdgPositioner) of object;
    TSetWindowGeometryEvent = procedure(Sender: TXdgSurface; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer) of object;
    TAckConfigureEvent = procedure(Sender: TXdgSurface; aSerial: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GET_TOPLEVEL = 1, _GET_POPUP = 2, _SET_WINDOW_GEOMETRY = 3, _ACK_CONFIGURE = 4);
    TEvents = (EV_CONFIGURE = 0);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGetToplevelPriv: TGetToplevelEvent;
    FOnGetPopupPriv: TGetPopupEvent;
    FOnSetWindowGeometryPriv: TSetWindowGeometryEvent;
    FOnAckConfigurePriv: TAckConfigureEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGetToplevel(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_TOPLEVEL); virtual;
    procedure HandleGetPopup(var AMsg: TWaylandEventMessage); message Ord(TRequests._GET_POPUP); virtual;
    procedure HandleSetWindowGeometry(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_WINDOW_GEOMETRY); virtual;
    procedure HandleAckConfigure(var AMsg: TWaylandEventMessage); message Ord(TRequests._ACK_CONFIGURE); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGetToplevel: TGetToplevelEvent read FOnGetToplevelPriv write FOnGetToplevelPriv;
    property OnGetPopup: TGetPopupEvent read FOnGetPopupPriv write FOnGetPopupPriv;
    property OnSetWindowGeometry: TSetWindowGeometryEvent read FOnSetWindowGeometryPriv write FOnSetWindowGeometryPriv;
    property OnAckConfigure: TAckConfigureEvent read FOnAckConfigurePriv write FOnAckConfigurePriv;
  public
    procedure Configure(aSerial: DWord);
  private
    FListeners: array of IXdgSurfaceRequests;
  public
    function AddListener(AIntf: IXdgSurfaceRequests): LongInt;
  end;

  IXdgSurfaceRequests = interface
  ['IXdgSurfaceRequests']
    procedure xdg_surface_destroy(AXdgSurface: TXdgSurface);
    procedure xdg_surface_get_toplevel(AXdgSurface: TXdgSurface; aId: TXdgToplevel);
    procedure xdg_surface_get_popup(AXdgSurface: TXdgSurface; aId: TXdgPopup; aParent: TXdgSurface; aPositioner: TXdgPositioner);
    procedure xdg_surface_set_window_geometry(AXdgSurface: TXdgSurface; aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure xdg_surface_ack_configure(AXdgSurface: TXdgSurface; aSerial: DWord);
  end;

  IXdgToplevelRequests = interface;

  [TWLIntfAttribute('destroy(),set_parent(?o),set_title(s),set_app_id(s),show_window_menu(ouii),move(ou),resize(ouu),set_max_size(ii),set_min_size(ii),set_maximized(),unset_maximized(),set_fullscreen(?o),unset_fullscreen(),set_minimized()', 'configure(iia),close(),configure_bounds(ii),wm_capabilities(a)')]
  { TXdgToplevel }
  TXdgToplevel = class(TWaylandServerResource)
  public type
    TError = (erInvalidresizeedge = 0, erInvalidparent = 1, erInvalidsize = 2);
    TResizeEdge = (reNone = 0, reTop = 1, reBottom = 2, reLeft = 4, reTopleft = 5, reBottomleft = 6, reRight = 8, reTopright = 9, reBottomright = 10);
    TState = (stMaximized = 1, stFullscreen = 2, stResizing = 3, stActivated = 4, stTiledleft = 5, stTiledright = 6, stTiledtop = 7, stTiledbottom = 8, stSuspended = 9, stConstrainedleft = 10, stConstrainedright = 11, stConstrainedtop = 12, stConstrainedbottom = 13);
    TWmCapabilities = (wmWindowmenu = 1, wmMaximize = 2, wmFullscreen = 3, wmMinimize = 4);
    TDestroyEvent = procedure(Sender: TXdgToplevel) of object;
    TSetParentEvent = procedure(Sender: TXdgToplevel; aParent: TXdgToplevel) of object;
    TSetTitleEvent = procedure(Sender: TXdgToplevel; aTitle: String) of object;
    TSetAppIdEvent = procedure(Sender: TXdgToplevel; aAppId: String) of object;
    TShowWindowMenuEvent = procedure(Sender: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord; aX: Integer; aY: Integer) of object;
    TMoveEvent = procedure(Sender: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord) of object;
    TResizeEvent = procedure(Sender: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord; aEdges: TResizeEdge) of object;
    TSetMaxSizeEvent = procedure(Sender: TXdgToplevel; aWidth: Integer; aHeight: Integer) of object;
    TSetMinSizeEvent = procedure(Sender: TXdgToplevel; aWidth: Integer; aHeight: Integer) of object;
    TSetMaximizedEvent = procedure(Sender: TXdgToplevel) of object;
    TUnsetMaximizedEvent = procedure(Sender: TXdgToplevel) of object;
    TSetFullscreenEvent = procedure(Sender: TXdgToplevel; aOutput: TWlOutput) of object;
    TUnsetFullscreenEvent = procedure(Sender: TXdgToplevel) of object;
    TSetMinimizedEvent = procedure(Sender: TXdgToplevel) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _SET_PARENT = 1, _SET_TITLE = 2, _SET_APP_ID = 3, _SHOW_WINDOW_MENU = 4, _MOVE = 5, _RESIZE = 6, _SET_MAX_SIZE = 7, _SET_MIN_SIZE = 8, _SET_MAXIMIZED = 9, _UNSET_MAXIMIZED = 10, _SET_FULLSCREEN = 11, _UNSET_FULLSCREEN = 12, _SET_MINIMIZED = 13);
    TEvents = (EV_CONFIGURE = 0, EV_CLOSE = 1, EV_CONFIGURE_BOUNDS = 2, EV_WM_CAPABILITIES = 3);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnSetParentPriv: TSetParentEvent;
    FOnSetTitlePriv: TSetTitleEvent;
    FOnSetAppIdPriv: TSetAppIdEvent;
    FOnShowWindowMenuPriv: TShowWindowMenuEvent;
    FOnMovePriv: TMoveEvent;
    FOnResizePriv: TResizeEvent;
    FOnSetMaxSizePriv: TSetMaxSizeEvent;
    FOnSetMinSizePriv: TSetMinSizeEvent;
    FOnSetMaximizedPriv: TSetMaximizedEvent;
    FOnUnsetMaximizedPriv: TUnsetMaximizedEvent;
    FOnSetFullscreenPriv: TSetFullscreenEvent;
    FOnUnsetFullscreenPriv: TUnsetFullscreenEvent;
    FOnSetMinimizedPriv: TSetMinimizedEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleSetParent(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_PARENT); virtual;
    procedure HandleSetTitle(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_TITLE); virtual;
    procedure HandleSetAppId(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_APP_ID); virtual;
    procedure HandleShowWindowMenu(var AMsg: TWaylandEventMessage); message Ord(TRequests._SHOW_WINDOW_MENU); virtual;
    procedure HandleMove(var AMsg: TWaylandEventMessage); message Ord(TRequests._MOVE); virtual;
    procedure HandleResize(var AMsg: TWaylandEventMessage); message Ord(TRequests._RESIZE); virtual;
    procedure HandleSetMaxSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MAX_SIZE); virtual;
    procedure HandleSetMinSize(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MIN_SIZE); virtual;
    procedure HandleSetMaximized(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MAXIMIZED); virtual;
    procedure HandleUnsetMaximized(var AMsg: TWaylandEventMessage); message Ord(TRequests._UNSET_MAXIMIZED); virtual;
    procedure HandleSetFullscreen(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_FULLSCREEN); virtual;
    procedure HandleUnsetFullscreen(var AMsg: TWaylandEventMessage); message Ord(TRequests._UNSET_FULLSCREEN); virtual;
    procedure HandleSetMinimized(var AMsg: TWaylandEventMessage); message Ord(TRequests._SET_MINIMIZED); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnSetParent: TSetParentEvent read FOnSetParentPriv write FOnSetParentPriv;
    property OnSetTitle: TSetTitleEvent read FOnSetTitlePriv write FOnSetTitlePriv;
    property OnSetAppId: TSetAppIdEvent read FOnSetAppIdPriv write FOnSetAppIdPriv;
    property OnShowWindowMenu: TShowWindowMenuEvent read FOnShowWindowMenuPriv write FOnShowWindowMenuPriv;
    property OnMove: TMoveEvent read FOnMovePriv write FOnMovePriv;
    property OnResize: TResizeEvent read FOnResizePriv write FOnResizePriv;
    property OnSetMaxSize: TSetMaxSizeEvent read FOnSetMaxSizePriv write FOnSetMaxSizePriv;
    property OnSetMinSize: TSetMinSizeEvent read FOnSetMinSizePriv write FOnSetMinSizePriv;
    property OnSetMaximized: TSetMaximizedEvent read FOnSetMaximizedPriv write FOnSetMaximizedPriv;
    property OnUnsetMaximized: TUnsetMaximizedEvent read FOnUnsetMaximizedPriv write FOnUnsetMaximizedPriv;
    property OnSetFullscreen: TSetFullscreenEvent read FOnSetFullscreenPriv write FOnSetFullscreenPriv;
    property OnUnsetFullscreen: TUnsetFullscreenEvent read FOnUnsetFullscreenPriv write FOnUnsetFullscreenPriv;
    property OnSetMinimized: TSetMinimizedEvent read FOnSetMinimizedPriv write FOnSetMinimizedPriv;
  public
    procedure Configure(aWidth: Integer; aHeight: Integer; aStates: TBytes);
    procedure Close;
    [TSince(4)]
    procedure ConfigureBounds(aWidth: Integer; aHeight: Integer);
    [TSince(5)]
    procedure WmCapabilities(aCapabilities: TBytes);
  private
    FListeners: array of IXdgToplevelRequests;
  public
    function AddListener(AIntf: IXdgToplevelRequests): LongInt;
  end;

  IXdgToplevelRequests = interface
  ['IXdgToplevelRequests']
    procedure xdg_toplevel_destroy(AXdgToplevel: TXdgToplevel);
    procedure xdg_toplevel_set_parent(AXdgToplevel: TXdgToplevel; aParent: TXdgToplevel);
    procedure xdg_toplevel_set_title(AXdgToplevel: TXdgToplevel; aTitle: String);
    procedure xdg_toplevel_set_app_id(AXdgToplevel: TXdgToplevel; aAppId: String);
    procedure xdg_toplevel_show_window_menu(AXdgToplevel: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord; aX: Integer; aY: Integer);
    procedure xdg_toplevel_move(AXdgToplevel: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord);
    procedure xdg_toplevel_resize(AXdgToplevel: TXdgToplevel; aSeat: TWlSeat; aSerial: DWord; aEdges: TXdgToplevel.TResizeEdge);
    procedure xdg_toplevel_set_max_size(AXdgToplevel: TXdgToplevel; aWidth: Integer; aHeight: Integer);
    procedure xdg_toplevel_set_min_size(AXdgToplevel: TXdgToplevel; aWidth: Integer; aHeight: Integer);
    procedure xdg_toplevel_set_maximized(AXdgToplevel: TXdgToplevel);
    procedure xdg_toplevel_unset_maximized(AXdgToplevel: TXdgToplevel);
    procedure xdg_toplevel_set_fullscreen(AXdgToplevel: TXdgToplevel; aOutput: TWlOutput);
    procedure xdg_toplevel_unset_fullscreen(AXdgToplevel: TXdgToplevel);
    procedure xdg_toplevel_set_minimized(AXdgToplevel: TXdgToplevel);
  end;

  IXdgPopupRequests = interface;

  [TWLIntfAttribute('destroy(),grab(ou),reposition(ou)', 'configure(iiii),popup_done(),repositioned(u)')]
  { TXdgPopup }
  TXdgPopup = class(TWaylandServerResource)
  public type
    TError = (erInvalidgrab = 0);
    TDestroyEvent = procedure(Sender: TXdgPopup) of object;
    TGrabEvent = procedure(Sender: TXdgPopup; aSeat: TWlSeat; aSerial: DWord) of object;
    TRepositionEvent = procedure(Sender: TXdgPopup; aPositioner: TXdgPositioner; aToken: DWord) of object;
  protected
    class function GetInterfaceVersion: Integer; override;
    class function GetInterfaceName: String; override;
  protected type
    TRequests = (_DESTROY = 0, _GRAB = 1, _REPOSITION = 2);
    TEvents = (EV_CONFIGURE = 0, EV_POPUP_DONE = 1, EV_REPOSITIONED = 2);
  private
    FOnDestroyPriv: TDestroyEvent;
    FOnGrabPriv: TGrabEvent;
    FOnRepositionPriv: TRepositionEvent;
  protected
    procedure HandleDestroy(var AMsg: TWaylandEventMessage); message Ord(TRequests._DESTROY); virtual;
    procedure HandleGrab(var AMsg: TWaylandEventMessage); message Ord(TRequests._GRAB); virtual;
    procedure HandleReposition(var AMsg: TWaylandEventMessage); message Ord(TRequests._REPOSITION); virtual;
  published
    property OnDestroy: TDestroyEvent read FOnDestroyPriv write FOnDestroyPriv;
    property OnGrab: TGrabEvent read FOnGrabPriv write FOnGrabPriv;
    property OnReposition: TRepositionEvent read FOnRepositionPriv write FOnRepositionPriv;
  public
    procedure Configure(aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
    procedure PopupDone;
    [TSince(3)]
    procedure Repositioned(aToken: DWord);
  private
    FListeners: array of IXdgPopupRequests;
  public
    function AddListener(AIntf: IXdgPopupRequests): LongInt;
  end;

  IXdgPopupRequests = interface
  ['IXdgPopupRequests']
    procedure xdg_popup_destroy(AXdgPopup: TXdgPopup);
    procedure xdg_popup_grab(AXdgPopup: TXdgPopup; aSeat: TWlSeat; aSerial: DWord);
    procedure xdg_popup_reposition(AXdgPopup: TXdgPopup; aPositioner: TXdgPositioner; aToken: DWord);
  end;

implementation
uses
  wayland_stream;

class function TXdgWmBase.GetInterfaceVersion: Integer;
begin
  Result := 7;
end;

class function TXdgWmBase.GetInterfaceName: String;
begin
  Result := 'xdg_wm_base';
end;

procedure TXdgWmBase.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_wm_base_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgWmBase.HandleCreatePositioner(var AMsg: TWaylandEventMessage);
var
  lId: TXdgPositioner;
  lListenerIdx: Integer;
begin
  lId := TXdgPositioner.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnCreatePositioner) then OnCreatePositioner(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_wm_base_create_positioner(Self,lId);
  AMsg.SetHandled;
end;

procedure TXdgWmBase.HandleGetXdgSurface(var AMsg: TWaylandEventMessage);
var
  lId: TXdgSurface;
  lSurface: TWlSurface;
  lListenerIdx: Integer;
begin
  lId := TXdgSurface.Create(Client, AMsg.Args.ReadDWord, Version);
  lSurface := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSurface);
  if Assigned(OnGetXdgSurface) then OnGetXdgSurface(Self,lId,lSurface);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_wm_base_get_xdg_surface(Self,lId,lSurface);
  AMsg.SetHandled;
end;

procedure TXdgWmBase.HandlePong(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnPong) then OnPong(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_wm_base_pong(Self,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgWmBase.Ping(aSerial: DWord);
begin
  SendEvent(Ord(TEvents.EV_PING), [aSerial]);
end;

function TXdgWmBase.AddListener(AIntf: IXdgWmBaseRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgPositioner.GetInterfaceVersion: Integer;
begin
  Result := 7;
end;

class function TXdgPositioner.GetInterfaceName: String;
begin
  Result := 'xdg_positioner';
end;

procedure TXdgPositioner.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetSize) then OnSetSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetAnchorRect(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetAnchorRect) then OnSetAnchorRect(Self,lX,lY,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_anchor_rect(Self,lX,lY,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetAnchor(var AMsg: TWaylandEventMessage);
var
  lAnchor: TAnchor;
  lListenerIdx: Integer;
begin
  lAnchor := TAnchor(AMsg.Args.ReadDWord);
  if Assigned(OnSetAnchor) then OnSetAnchor(Self,lAnchor);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_anchor(Self,lAnchor);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetGravity(var AMsg: TWaylandEventMessage);
var
  lGravity: TGravity;
  lListenerIdx: Integer;
begin
  lGravity := TGravity(AMsg.Args.ReadDWord);
  if Assigned(OnSetGravity) then OnSetGravity(Self,lGravity);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_gravity(Self,lGravity);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetConstraintAdjustment(var AMsg: TWaylandEventMessage);
var
  lConstraintAdjustment: TConstraintAdjustment;
  lListenerIdx: Integer;
begin
  lConstraintAdjustment := TConstraintAdjustment(AMsg.Args.ReadDWord);
  if Assigned(OnSetConstraintAdjustment) then OnSetConstraintAdjustment(Self,lConstraintAdjustment);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_constraint_adjustment(Self,lConstraintAdjustment);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetOffset(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  if Assigned(OnSetOffset) then OnSetOffset(Self,lX,lY);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_offset(Self,lX,lY);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetReactive(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnSetReactive) then OnSetReactive(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_reactive(Self);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetParentSize(var AMsg: TWaylandEventMessage);
var
  lParentWidth: Integer;
  lParentHeight: Integer;
  lListenerIdx: Integer;
begin
  lParentWidth := AMsg.Args.ReadInteger;
  lParentHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetParentSize) then OnSetParentSize(Self,lParentWidth,lParentHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_parent_size(Self,lParentWidth,lParentHeight);
  AMsg.SetHandled;
end;

procedure TXdgPositioner.HandleSetParentConfigure(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnSetParentConfigure) then OnSetParentConfigure(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_positioner_set_parent_configure(Self,lSerial);
  AMsg.SetHandled;
end;

function TXdgPositioner.AddListener(AIntf: IXdgPositionerRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgSurface.GetInterfaceVersion: Integer;
begin
  Result := 7;
end;

class function TXdgSurface.GetInterfaceName: String;
begin
  Result := 'xdg_surface';
end;

procedure TXdgSurface.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgSurface.HandleGetToplevel(var AMsg: TWaylandEventMessage);
var
  lId: TXdgToplevel;
  lListenerIdx: Integer;
begin
  lId := TXdgToplevel.Create(Client, AMsg.Args.ReadDWord, Version);
  if Assigned(OnGetToplevel) then OnGetToplevel(Self,lId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_get_toplevel(Self,lId);
  AMsg.SetHandled;
end;

procedure TXdgSurface.HandleGetPopup(var AMsg: TWaylandEventMessage);
var
  lId: TXdgPopup;
  lParent: TXdgSurface;
  lPositioner: TXdgPositioner;
  lListenerIdx: Integer;
begin
  lId := TXdgPopup.Create(Client, AMsg.Args.ReadDWord, Version);
  lParent := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgSurface);
  lPositioner := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgPositioner);
  if Assigned(OnGetPopup) then OnGetPopup(Self,lId,lParent,lPositioner);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_get_popup(Self,lId,lParent,lPositioner);
  AMsg.SetHandled;
end;

procedure TXdgSurface.HandleSetWindowGeometry(var AMsg: TWaylandEventMessage);
var
  lX: Integer;
  lY: Integer;
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetWindowGeometry) then OnSetWindowGeometry(Self,lX,lY,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_set_window_geometry(Self,lX,lY,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgSurface.HandleAckConfigure(var AMsg: TWaylandEventMessage);
var
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnAckConfigure) then OnAckConfigure(Self,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_surface_ack_configure(Self,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgSurface.Configure(aSerial: DWord);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aSerial]);
end;

function TXdgSurface.AddListener(AIntf: IXdgSurfaceRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgToplevel.GetInterfaceVersion: Integer;
begin
  Result := 7;
end;

class function TXdgToplevel.GetInterfaceName: String;
begin
  Result := 'xdg_toplevel';
end;

procedure TXdgToplevel.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetParent(var AMsg: TWaylandEventMessage);
var
  lParent: TXdgToplevel;
  lListenerIdx: Integer;
begin
  lParent := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgToplevel);
  if Assigned(OnSetParent) then OnSetParent(Self,lParent);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_parent(Self,lParent);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetTitle(var AMsg: TWaylandEventMessage);
var
  lTitle: String;
  lListenerIdx: Integer;
begin
  lTitle := AMsg.Args.ReadString;
  if Assigned(OnSetTitle) then OnSetTitle(Self,lTitle);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_title(Self,lTitle);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetAppId(var AMsg: TWaylandEventMessage);
var
  lAppId: String;
  lListenerIdx: Integer;
begin
  lAppId := AMsg.Args.ReadString;
  if Assigned(OnSetAppId) then OnSetAppId(Self,lAppId);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_app_id(Self,lAppId);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleShowWindowMenu(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lX: Integer;
  lY: Integer;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  lX := AMsg.Args.ReadInteger;
  lY := AMsg.Args.ReadInteger;
  if Assigned(OnShowWindowMenu) then OnShowWindowMenu(Self,lSeat,lSerial,lX,lY);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_show_window_menu(Self,lSeat,lSerial,lX,lY);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleMove(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnMove) then OnMove(Self,lSeat,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_move(Self,lSeat,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleResize(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lEdges: TResizeEdge;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  lEdges := TResizeEdge(AMsg.Args.ReadDWord);
  if Assigned(OnResize) then OnResize(Self,lSeat,lSerial,lEdges);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_resize(Self,lSeat,lSerial,lEdges);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetMaxSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetMaxSize) then OnSetMaxSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_max_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetMinSize(var AMsg: TWaylandEventMessage);
var
  lWidth: Integer;
  lHeight: Integer;
  lListenerIdx: Integer;
begin
  lWidth := AMsg.Args.ReadInteger;
  lHeight := AMsg.Args.ReadInteger;
  if Assigned(OnSetMinSize) then OnSetMinSize(Self,lWidth,lHeight);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_min_size(Self,lWidth,lHeight);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetMaximized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnSetMaximized) then OnSetMaximized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_maximized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleUnsetMaximized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnUnsetMaximized) then OnUnsetMaximized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_unset_maximized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetFullscreen(var AMsg: TWaylandEventMessage);
var
  lOutput: TWlOutput;
  lListenerIdx: Integer;
begin
  lOutput := (Client.GetObject(AMsg.Args.ReadDWord) as TWlOutput);
  if Assigned(OnSetFullscreen) then OnSetFullscreen(Self,lOutput);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_fullscreen(Self,lOutput);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleUnsetFullscreen(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnUnsetFullscreen) then OnUnsetFullscreen(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_unset_fullscreen(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.HandleSetMinimized(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnSetMinimized) then OnSetMinimized(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_toplevel_set_minimized(Self);
  AMsg.SetHandled;
end;

procedure TXdgToplevel.Configure(aWidth: Integer; aHeight: Integer; aStates: TBytes);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aWidth,aHeight,Length(aStates),Pointer(aStates)]);
end;

procedure TXdgToplevel.Close;
begin
  SendEvent(Ord(TEvents.EV_CLOSE), []);
end;

procedure TXdgToplevel.ConfigureBounds(aWidth: Integer; aHeight: Integer);
begin
  if Version >= 4 then
  begin
    SendEvent(Ord(TEvents.EV_CONFIGURE_BOUNDS), [aWidth,aHeight]);
  end;
end;

procedure TXdgToplevel.WmCapabilities(aCapabilities: TBytes);
begin
  if Version >= 5 then
  begin
    SendEvent(Ord(TEvents.EV_WM_CAPABILITIES), [Length(aCapabilities),Pointer(aCapabilities)]);
  end;
end;

function TXdgToplevel.AddListener(AIntf: IXdgToplevelRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;

class function TXdgPopup.GetInterfaceVersion: Integer;
begin
  Result := 7;
end;

class function TXdgPopup.GetInterfaceName: String;
begin
  Result := 'xdg_popup';
end;

procedure TXdgPopup.HandleDestroy(var AMsg: TWaylandEventMessage);
var
  lListenerIdx: Integer;
begin
  if Assigned(OnDestroy) then OnDestroy(Self);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_popup_destroy(Self);
  AMsg.SetHandled;
end;

procedure TXdgPopup.HandleGrab(var AMsg: TWaylandEventMessage);
var
  lSeat: TWlSeat;
  lSerial: DWord;
  lListenerIdx: Integer;
begin
  lSeat := (Client.GetObject(AMsg.Args.ReadDWord) as TWlSeat);
  lSerial := AMsg.Args.ReadDWord;
  if Assigned(OnGrab) then OnGrab(Self,lSeat,lSerial);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_popup_grab(Self,lSeat,lSerial);
  AMsg.SetHandled;
end;

procedure TXdgPopup.HandleReposition(var AMsg: TWaylandEventMessage);
var
  lPositioner: TXdgPositioner;
  lToken: DWord;
  lListenerIdx: Integer;
begin
  lPositioner := (Client.GetObject(AMsg.Args.ReadDWord) as TXdgPositioner);
  lToken := AMsg.Args.ReadDWord;
  if Assigned(OnReposition) then OnReposition(Self,lPositioner,lToken);
  for lListenerIdx := 0 to High(FListeners) do FListeners[lListenerIdx].xdg_popup_reposition(Self,lPositioner,lToken);
  AMsg.SetHandled;
end;

procedure TXdgPopup.Configure(aX: Integer; aY: Integer; aWidth: Integer; aHeight: Integer);
begin
  SendEvent(Ord(TEvents.EV_CONFIGURE), [aX,aY,aWidth,aHeight]);
end;

procedure TXdgPopup.PopupDone;
begin
  SendEvent(Ord(TEvents.EV_POPUP_DONE), []);
end;

procedure TXdgPopup.Repositioned(aToken: DWord);
begin
  if Version >= 3 then
  begin
    SendEvent(Ord(TEvents.EV_REPOSITIONED), [aToken]);
  end;
end;

function TXdgPopup.AddListener(AIntf: IXdgPopupRequests): LongInt;
begin
  SetLength(FListeners, Length(FListeners)+1);
  FListeners[High(FListeners)] := AIntf;
  Result := 0;
end;


initialization
  RegisterServerInterface('xdg_wm_base', TXdgWmBase);
  RegisterServerInterface('xdg_positioner', TXdgPositioner);
  RegisterServerInterface('xdg_surface', TXdgSurface);
  RegisterServerInterface('xdg_toplevel', TXdgToplevel);
  RegisterServerInterface('xdg_popup', TXdgPopup);

end.